### ISSUE TITLE
Hydra RESTful JSON API

### ISSUE THREAD

**Issue by chaoflow** [NixOS/hydra#108]
A RESTful API for hydra has been started by @shlevy.

If you need more data, please add to this ticket.

@kikic, @coroa, and @chaoflow are working on [tpv.nix](https://github.com/chaoflow/tpv.nix) to make hydra's data (among other) available to python programmers.

Examples:

```
% curl -s -H 'Accept: application/json' http://hydra.nixos.org | json_pp      
[
...
   {
      "name" : "nix",
      "displayname" : "Nix"
   },
   {
      "name" : "nixops",
      "displayname" : "NixOps"
   },
   {
      "name" : "nixos",
      "displayname" : "NixOS"
   },
   {
      "name" : "nixpkgs",
      "displayname" : "Nixpkgs"
   }
...
]
```

```
% curl -s -H 'Accept: application/json' http://hydra.nixos.org/project/nixpkgs | json_pp 
{
   "owner" : {
      "fullname" : "Eelco Dolstra",
      "username" : "eelco"
   },
   "name" : "nixpkgs",
   "jobsets" : [
...
      {
         "name" : "python-rework"
      },
      {
         "name" : "stdenv"
      },
      {
         "name" : "stdenv-fixes"
      },
      {
         "name" : "syscall-tracing"
      },
      {
         "name" : "systemd"
      },
      {
         "name" : "trunk"
      },
      {
         "name" : "xorg-test"
      }
   ],
   "description" : "Nix Packages collection",
   "homepage" : "http://nixos.org/nixpkgs",
   "views" : [
      {
         "name" : "unstable"
      }
   ],
   "releases" : [
      {
         "timestamp" : 1265410277,
         "name" : "nixpkgs-0.13"
      }
   ],
   "hidden" : 0,
   "displayName" : "Nixpkgs",
   "enabled" : 1
}
```

**Comment by kirelagin** [comment]
http://hydra.nixos.org/jobset/nixpkgs/trunk gives a horrible error =(.

**Comment by rbvermaa** [comment]
@kirelagin How about giving some more information? E.g. what is the error? What request are you performing?

**Comment by kirelagin** [comment]
Ah, now I realised that it was the actual evaluation error that scared me.
What I was looking for is http://hydra.nixos.org/jobset/nixpkgs/trunk/evals, but it is not usable right now as it returns _all the evaluations_ instead of last 10, as @shlevy said.

**Comment by kirelagin** [comment]
What I actually need is a nice overview of a jobset with a list of last `N` evaluations with dates and numbers of succeeded/failed jobs, just like in the web browser. Looks like currently I’ll have to do a separate request for each evaluation (after I figure out how to limit the number of evaluations returned) which is not very convenient =(.

**Comment by lbnielsjanssen** [comment]
I need to be able to retrieve JSONs of specific builds (`https://<url>/build/<build-id>`) based on two known facts:
* The evaluation ID
* The names of the jobs I'm interested in (e.g. 'products')

Current situation: when I retrieve the JSON of an evaluation (`http://<url>/eval/xxx`) I get a list the build IDs within that evaluation: 
```
{ 
  builds : [x,y,z,..], 
  .. 
}
``` 

In my case I would prefer a mapping from job name to these build IDs. For instance, something like: 
```
{ 
  builds : { 
    'products' : { id : xxx },
    ..
  }, 
  .. 
}
```

Is this something that can be added to the JSON API? Would be very helpful! :)

**Comment by gilligan** [comment]
A json api is now available and will soon be more adequately documented when #750 is merged. For specific requests or bugs separate issues should be created.
