### ISSUE TITLE
Regression displaying jobset names on various pages

### ISSUE THREAD

**Issue by grahamc** [NixOS/hydra#1120]
> in https://hydra.nixos.org/machines the jobset column is (still?) broken and the corresponding job links as well.  I believe that's quite a recent regression.
>
> EDIT: also the column in https://hydra.nixos.org/status and https://hydra.nixos.org/all

_Originally posted by @vcunat in https://github.com/NixOS/hydra/issues/1111#issuecomment-1013647784_

Likely broken as a result of one of the PRs taken out of  https://github.com/NixOS/hydra/pull/1093.

**Comment by grahamc** [comment]
I think this is resolved as of #1093 merging.

**Comment by vcunat** [comment]
Yes, all the missing pieces I knew are back on hydra.nixos.org.
