### ISSUE TITLE
trivial content-addressed derivation mildly breaks my hydra

### ISSUE THREAD

**Issue by t184256** [NixOS/hydra#1122]
Hello, I'm trying to write an input-less flake with content-addressed derivations that's buildable on hydra. My current problem trims down to:

```
{
  description = "a broken flake to report a bug";
  outputs = { self }: {
    hydraJobs.test.x86_64-linux = derivation {
      name = "test"; builder = "/bin/sh"; args = ["-c" "/bin/sh -c :> $out"];
      system = "x86_64-linux";
      __contentAddressed = true;
      outputHashAlgo = "sha256"; outputHashMode = "recursive";
    };
  };
}
```

resulting in a queued up build with a page like this

```
500 Internal Server Error
Caught exception in Hydra::Controller::Build->build "[31;1merror:[0m path '[35;1m/0n7ybxvpj24l8c9l5z594rxl1rdx793nw5wixsdrfpwr6jjmppik[0m' is not in the Nix store at /nix/store/89cykv7x5z5c8da3a2kbrigp9c09lx3k-hydra-0.1.20220117.ed1b532/libexec/hydra/lib/Hydra/Controller/Build.pm line 71."
```

and hydra-queue-runner erroring out like this in a loop:
```
checking the queue for builds > 0...
loading build 6360 (test:test:test.x86_64-linux)
download thread waiting for 10000 ms
considering derivation ‘/nix/store/q8c7p8m6d1gmqc0wsbf1xg8a5vnh3f1l-test.drv’
queue monitor: error: '<SHORT BIT OF RANDOM MEMORY GARBAGE>


checking the queue for builds > 0...
loading build 6360 (test:test:test.x86_64-linux)
closing daemon connection because of an exception
queue monitor: error: writing to file: Broken pipe
```

You can try that for yourself by building a flake from git+https://gist.github.com/t184256/808dd47e2f62f764291506c13c8700eb
Not sure what the impact to the hydra instance's health is though.

Observed on both nixpkgs master's hydra-unstable and on today's 0.1.20220117.ed1b532, both using nix-2.6.0pre20220117_fc2443a.

What am I doing wrong?

**Comment by Ericson2314** [comment]
I think https://github.com/NixOS/hydra/pull/875 needs to be merged first?

**Comment by t184256** [comment]
(facepalm) oh yes, indeed. [Lightly patched it](https://gist.github.com/t184256/f1532591033a522d4daba16aa66b5de0), nuked db and it started working. Sorry, IDK how I missed that.
