### ISSUE TITLE
Evaluation error due to left-over tmpdir

### ISSUE THREAD

**Issue by gregkar** [NixOS/hydra#117]
I got the following error on a jobset on Hydra, apparently due to some left-over old tmp-dir:

cannot check out Mercurial repository `ssh://hg@bitbucket.org/Predictix/crate_fr_manager':
mkdir: cannot create directory ‘/tmp/hg-checkout-tmp-25644’: File exists

**Comment by gilligan** [comment]
The relevant code for that is https://github.com/nixos/hydra/blob/master/src/script/nix-prefetch-hg#L38 i think:

```
    tmpPath="$(mktemp -d "${TMPDIR:-/tmp}/hg-checkout-tmp-XXXXXXXX")"
    trap "rm -rf \"$tmpPath\"" EXIT
```

And was committed after this issue was created. I think it is safe to assume that this should fix the reported issue.
