### ISSUE TITLE
aarch64 support

### ISSUE THREAD

**Issue by Mindavi** [NixOS/hydra#1209]
**Is your feature request related to a problem? Please describe.**

I was bumping hydra in nixpkgs and found out that the aarch64 build started failing, due to UUID4-Tiny not building (test failing) on aarch64. It seems like it did (at least) _build_ before.

**Describe the solution you'd like**

- Replace UUID4-Tiny with a dependency that doesn't do direct syscalls
- Help getting a fix in for the package: https://github.com/cv-library/UUID4-Tiny/issues/7

**Describe alternatives you've considered**

- Drop support for aarch64-linux

**Additional context**

See https://github.com/NixOS/nixpkgs/pull/172378#issuecomment-1124282913. Contains some urls to logs.

Note that I'm not using hydra on aarch64-linux, but maybe someone is or would like to in the future.

**Comment by lheckemann** [comment]
Fixed in #1262

**Comment by Mindavi** [comment]
Note that we are still carrying a patch to uuid4-tiny in nixpkgs.
