### ISSUE TITLE
RunCommand doesn't work anymore

### ISSUE THREAD

**Issue by sbourdeauducq** [NixOS/hydra#1217]
After updating Hydra to 2022-05-03, it appears that RunCommands are not executed anymore.

* The defined commands do show up in "RunCommand Logs" tab for the jobsets
* However, clicking one of the log buttons shows an error "The RunCommand log file is not available." and the area where the log should have been displayed "(Unavailable)".
* Attempting to create files from the RunCommand has no effect.
* This suggests RunCommands are not executed anymore for some reason.
* I cannot find anything relevant in the systemd journal of hydra-queue-runner.

**Comment by sbourdeauducq** [comment]
```
error running build_finished hooks: Died while trying to process RunCommand (44d3700b-e0ee-4c55-9fce-90b175615b67): mkdir /var/lib/hydra/runcommand-logs: Permission denied at /nix/store/i78czcxdzdxqxdlpkxs1jh4xsd7njxb4-hydra-2022-05-03/libexec/hydra/lib/Hydra/Plugin/RunCommand.pm line 254.
```

**Comment by sbourdeauducq** [comment]
``chown hydra-queue-runner /var/lib/hydra`` solved it. Thanks for the hint.

But shouldn't this have been done by ``hydra-init``?

**Comment by grahamc** [comment]
Yes, it should have, thanks. Are you running Hydra using the NixOS module in NixOS, or using the module provided by this repository's flake?

**Comment by sbourdeauducq** [comment]
I'm using the NixOS module in 22.05.

**Comment by grahamc** [comment]
It looks like these need to be ported over to the NixOS module: https://github.com/NixOS/hydra/blob/master/hydra-module.nix#L278-L284 vs. https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/continuous-integration/hydra/default.nix#L311-L314. Would you mind either opening a PR or ticket on nixpkgs?
