### ISSUE TITLE
Incorrect MIME type for .css and .js files breaks rendering of HTML reports

### ISSUE THREAD

**Issue by knedlsepp** [NixOS/hydra#1267]
**Describe the bug**
HTML reports are no longer rendered correctly since https://github.com/NixOS/hydra/pull/1240 was merged, as the `Content-Type` of `.css` and `.js` files changed from `text/css` or `application/javascript` to  `text/plain`.

Firefox reports: 

```
The stylesheet was not loaded because its MIME type, "text/plain" is not "text/css"
```

**To Reproduce**

Visit https://hydra.nixos.org/build/203389362 and click [Manual](https://hydra.nixos.org/build/203389362/download/1/manual/). Or try visiting one of the following:

- https://nixos.org/nixops/manual
- https://nixos.org/hydra/manual

**Screenshots**
![Screenshot_20221229_215348](https://user-images.githubusercontent.com/3287933/210010369-7bb8be5a-3726-443a-8b71-1da35222f4da.png)

**Hydra Server:**

- OS and version: e.g. NixOS 22.11.20221229.ad35830
- Version of Hydra: hydra-unstable 2022-10-22
- Version of Nix Hydra is built against: nix-2.11.1
- Version of the Nix daemon: nix-2.11.1

**Comment by peacememories** [comment]
It seems not only the `css` and `js` MIME-types are broken. When trying to view the page on an iPhone, it is instead downloaded, because the content type header looks like this:

```
content-type: cannot  open  `/nix/store/mp2x9s34n3m2lyd7hk9x15l1sry5qkda-hydra-manual-0.1.20221021.312cb42/share/doc/hydra/index.html'  (No such file or directory); charset=cannot open  `/nix/store/mp2x9s34n3m2lyd7hk9x15l1sry5qkda-hydra-manual-0.1.20221021.312cb42/share/doc/hydra/index.html'  (No such file or directory)
```

My desktop browser ignores this, but mobile Safari refuses to open the page and instead opens the download dialog.
