### ISSUE TITLE
NixOS hydra build failure due to JS file conflict 

### ISSUE THREAD

**Issue by benaryorg** [NixOS/hydra#1334]
**Describe the bug**
[Upstream hydra reports a failure](https://hydra.nixos.org/build/244423276/nixlog/1) and the reasons seems to be that the minified jQuery files get installed twice.

**To Reproduce**
1. for now I have only [seen this happen on the NixOS Hydra instance](https://hydra.nixos.org/build/244423276/nixlog/1)

**Expected behavior**
*hydra_unstable* should build on hydra.nixos.org.

**Screenshots**
Here's the relevant log bit:

```text
[…]
/nix/store/bblyj5b3ii8n6v4ra0nb37cmi3lf8rz9-coreutils-9.3/bin/install -c -m 644  static/js/jquery/jquery-3.4.1.min.js static/js/jquery/jquery-ui-1.10.4.min.js '/nix/store/kwdjj8isn1khycrblmhawkl4ssiavylg-hydra-2023-11-17/libexec/hydra/root/static/js/jquery'
'./static/js/flot/jquery.min.js' -> '/nix/store/kwdjj8isn1khycrblmhawkl4ssiavylg-hydra-2023-11-17/libexec/hydra/root/static/js/flot/jquery.min.js'
'./static/js/flot/LICENSE.txt' -> '/nix/store/kwdjj8isn1khycrblmhawkl4ssiavylg-hydra-2023-11-17/libexec/hydra/root/static/js/flot/LICENSE.txt'
'./static/js/flot/Makefile' -> '/nix/store/kwdjj8isn1khycrblmhawkl4ssiavylg-hydra-2023-11-17/libexec/hydra/root/static/js/flot/Makefile'
'./static/js/flot/NEWS.md' -> '/nix/store/kwdjj8isn1khycrblmhawkl4ssiavylg-hydra-2023-11-17/libexec/hydra/root/static/js/flot/NEWS.md'
'./static/js/flot/PLUGINS.md' -> '/nix/store/kwdjj8isn1khycrblmhawkl4ssiavylg-hydra-2023-11-17/libexec/hydra/root/static/js/flot/PLUGINS.md'
'./static/js/flot/README.md' -> '/nix/store/kwdjj8isn1khycrblmhawkl4ssiavylg-hydra-2023-11-17/libexec/hydra/root/static/js/flot/README.md'
'./static/js/jquery/jquery-3.4.1.min.js' -> '/nix/store/kwdjj8isn1khycrblmhawkl4ssiavylg-hydra-2023-11-17/libexec/hydra/root/static/js/jquery/jquery-3.4.1.min.js'
'./static/js/jquery/jquery-ui-1.10.4.min.js' -> '/nix/store/kwdjj8isn1khycrblmhawkl4ssiavylg-hydra-2023-11-17/libexec/hydra/root/static/js/jquery/jquery-ui-1.10.4.min.js'
cp: cannot create regular file '/nix/store/kwdjj8isn1khycrblmhawkl4ssiavylg-hydra-2023-11-17/libexec/hydra/root/static/js/jquery/jquery-ui-1.10.4.min.js': File exists
[…]
```

As you can see the first line runs *install* to place the jQuery files there.
Then the second to last line seems to run a regular cp to copy the files, which due to the previous install fails.

[Here's the rough timeline of the build failures](https://hydra.nixos.org/jobset/nixos/release-23.11#tabs-jobs) in case this helps somehow.

**Hydra Server:**

Please fill out this data as well as you can, but don't worry if you can't -- just do your best.

- OS and version: ?
- Hydra 0.1.20230823.00d3087
- Version of Nix Hydra is built against: ?
- nix 2.17.0

**Additional context**

Since there seems to be a copy copying over these files already I think there's either a superfluous copy somewhere, or the [install invocation (presumably originating here)](https://github.com/NixOS/hydra/blob/02e453fc8c39751843220eaecdeaf7d539b7e765/src/root/Makefile.am#L8-L9) is too much.
I don't know which one is the one that's supposed to run though.

**Comment by Mindavi** [comment]
Possibly fixed while build system was changed to meson.
