### ISSUE TITLE
Keep latest successful build

### ISSUE THREAD

**Issue by shlevy** [NixOS/hydra#140]
Sometimes the latest successful build will be more than `keepnr` evaluations ago, but it would be nice if hydra would keep at least 1 (and possibly a configurable number) of previous successful builds even if they aren't in the most recent evals.

**Comment by shlevy** [comment]
@edolstra @rbvermaa Any good idea of how to implement this? Bitten by it again recently.

**Comment by shlevy** [comment]
@edolstra Anything I can help with?

**Comment by rbvermaa** [comment]
@shlevy I would just assign it to yourself.

**Comment by edolstra** [comment]
I'm working on it now.

**Comment by edolstra** [comment]
Note however that this may cause Hydra to keep a lot more garbage around, which given our current disk space problems might not be ideal.

**Comment by rbvermaa** [comment]
@edolstra just make 0/1 the default (depending on the semantics)
