### ISSUE TITLE
Add pass/fail badge

### ISSUE THREAD

**Issue by ndmitchell** [NixOS/hydra#163]
The Travis integration tool has support for badges, for example:

```
![Build Status](https://travis-ci.org/ndmitchell/shake.png)
```

Gives

![Build Status](https://travis-ci.org/ndmitchell/shake.png)

That way I can include a visual indicator in my readme of whether Shake is passing the Travis build or not. It would be good to get the same kind of thing from Hydra.

**Comment by PierreR** [comment]
:+1:

**Comment by ndmitchell** [comment]
Note that I now use http://shields.io/, which might be easier to integrate.
