### ISSUE TITLE
Configure Projects and JobSets declaratively

### ISSUE THREAD

**Issue by brendanhay** [NixOS/hydra#168]
Is it possible to create projects, jobsets, and any other sensical domain models declaratively?

The use case is to provision a hydra farm, projects, and jobsets pre-configured without having to use the Web UI.

**Comment by copumpkin** [comment]
:+1:

**Comment by domenkozar** [comment]
See https://github.com/NixOS/hydra/pull/277

**Comment by shlevy** [comment]
Note that #277 is not all you need for this, as projects are still configured in the web UI. But a fully declarative hydra is an easy next step.

**Comment by ledettwy** [comment]
Would also really like to see fully declarative project configuration, e.g., through the hydra configuration file.

**Comment by gavinrogers** [comment]
I think that doing it in nix [is the right approach](https://github.com/NixOS/hydra/pull/277#issuecomment-200310283). The path of least surprise would be: I'm setting up hydra, I'm putting a bunch of stuff into that machine's configuration.nix, then I add a services.hydra section, and then I add an array of jobs in there. basically nixos.services.hydra.jobsets should exist.

**Comment by gilligan** [comment]
declarative configuration has been implemented.
