### ISSUE TITLE
./configure failed

### ISSUE THREAD

**Issue by jimstutt** [NixOS/hydra#196]
My failed experiments report:

[jim@nixos:~/hydra]$ ./configure
/configure: line 3516: AC_PROG_LIBTOOL: command not found
checking for g++... g++
checking whether we are using the GNU C++ compiler... yes
checking whether g++ accepts -g... yes
checking dependency style of g++... gcc3
checking for dblatex... /home/jim/.nix-profile/bin/dblatex
checking for xsltproc... no
checking for perl... /run/current-system/sw/bin/perl
checking for nix-store... /nix/var/nix/profiles/default/bin/nix-store
checking whether /nix/var/nix/profiles/default/bin/nix-store is recent enough...yes
./configure: line 4110: syntax error near unexpected token `NIX,'
./configure: line 4110: `PKG_CHECK_MODULES(NIX, nix-main nix-expr nix-store)'

[jim@nixos:~/hydra]$ ./bootstrap
autoreconf: Entering directory `.'
autoreconf: configure.ac: not using Gettext
autoreconf: running: aclocal --force 
autoreconf: configure.ac: tracing
autoreconf: configure.ac: not using Libtool
autoreconf: running: /nix/store/kslbs5n87i6hlf4a33h7w6fcp2ydv81d-autoconf-2.69/bin/autoconf --force
configure.ac:10: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /nix/store/kslbs5n87i6hlf4a33h7w6fcp2ydv81d-autoconf-2.69/bin/autoconf failed with exit status: 1

[jim@nixos:~/hydra]$ autoconf --trace=AC_INIT

[jim@nixos:~/hydra]$ autoreconf --force --install
configure.ac:10: error: possibly undefined macro: AC_PROG_LIBTOOL
      If this token and others are legitimate, please use m4_pattern_allow.
      See the Autoconf documentation.
autoreconf: /nix/store/kslbs5n87i6hlf4a33h7w6fcp2ydv81d-autoconf-2.69/bin/autoconf failed with exit status: 1

[jim@nixos:~/hydra]$ cat config.log
cc version 4.8.4 (GCC) 
onfigure:3649: $? = 0
configure:3638: g++ -V >&5
g++: error: unrecognized command line option '-V'
g++: fatal error: no input files
compilation terminated.
configure:3649: $? = 1
configure:3638: g++ -qversion >&5
g++: error: unrecognized command line option '-qversion'
g++: fatal error: no input files
compilation terminated.

**Comment by rbvermaa** [comment]
You are missing ome dependencies, e.g. libtool. Please use the dev-shell script in the root of the directory, which will put you in a shell with all needed dependencies set up.

**Comment by rbvermaa** [comment]
https://github.com/NixOS/hydra/commit/e211e7771e80015bc3593989a0adc0540fd64b28

**Comment by jimstutt** [comment]
Tnx for the README.md; dev-shell worked fine. I did have automake, autoconf
and libtools already installed
