### ISSUE TITLE
A nixos service for hydra would make it easier to try out

### ISSUE THREAD

**Issue by copumpkin** [NixOS/hydra#197]
I'd imagine hydra.nixos.org is managed as a nixos service, so it seems like that module would just need to be moved into nixpkgs. Filing it here instead of there because it feels more relevant to hydra than to nixpkgs, but I'm happy to move it if someone suggests that.

**Comment by shlevy** [comment]
https://github.com/NixOS/hydra/blob/master/hydra-module.nix ?

**Comment by copumpkin** [comment]
Oh, not sure how I missed that, sorry!

**Comment by copumpkin** [comment]
Out of curiosity, why is it not in nixos?

**Comment by copumpkin** [comment]
Or perhaps a bit of readme space dedicated to how to install/run it in your average NixOS? The hydra manual makes it look pretty manual.

**Comment by copumpkin** [comment]
Also, is there a similar module for the build machines? It seems like it could be the quintessential NixOps example: spin up a hydra and a dozen build machines that talk to it seamlessly.

**Comment by domenkozar** [comment]
For anyone hitting this: https://github.com/peti/hydra-tutorial

**Comment by utdemir** [comment]
Now hydra module is on nixpkgs thanks to @domenkozar : https://github.com/NixOS/nixpkgs/blob/master/nixos/modules/services/continuous-integration/hydra/default.nix

I think this issue can be closed.

**Comment by copumpkin** [comment]
Thanks @domenkozar!
