### ISSUE TITLE
Please add pagination for hydra.nixos.org/queue

### ISSUE THREAD

**Issue by blueyed** [NixOS/hydra#199]
The page is (currently) really huge (44M) and causes problems for both Firefox and Chrome/Chromium to display because of its size.

There should be pagination, where only e.g. 50 jobs are being displayed per page.

**Comment by domenkozar** [comment]
This can be closed as queue page has been rewritten http://hydra.nixos.org/queue-summary

**Comment by blueyed** [comment]
Thanks!
