### ISSUE TITLE
jobset overview doesn't show input changes of build output

### ISSUE THREAD

**Issue by chrismelman** [NixOS/hydra#20]
When you look at a job overview, you don't  see the input changes of the input type build output.

example : 
[overview](http://hydra.nixos.org/jobset/webdsl/webdsl-editor)
[actual input change](http://hydra.nixos.org/build/2633281#tabs-buildinputs)

**Comment by domenkozar** [comment]
This appears to work now. Can you confirm?

**Comment by gilligan** [comment]
This does seem to work and the issue author hasn't reported back. i'll go ahead and close it.
