### ISSUE TITLE
Check interval doesn't work correctly

### ISSUE THREAD

**Issue by domenkozar** [NixOS/hydra#202]
Check interval:	10800 (http://hydra.nixos.org/jobset/nixos/trunk-combined#tabs-configuration)

Yet two jobs have 40min difference:

- http://hydra.nixos.org/eval/1180041
- http://hydra.nixos.org/eval/1180035

**Comment by rbvermaa** [comment]
Perhaps eval is triggered externally? Eg. in a github service hook?

**Comment by domenkozar** [comment]
Do we have services configured for that?

**Comment by rbvermaa** [comment]
Seems there was, I have removed them.

**Comment by domenkozar** [comment]
Thanks!
