### ISSUE TITLE
ike machine disk full

### ISSUE THREAD

**Issue by auntieNeo** [NixOS/hydra#209]
http://hydra.nixos.org/build/21493579/nixlog/7

Just wondering if anyone caught this.

@edolstra

**Comment by edolstra** [comment]
GC is failing due to an I/O error :frowning: 
```
[root@ike:~]# nix-store --gc
finding garbage collector roots...
deleting garbage...
deleting ‘/nix/store/jrjysi6dz5kzmm3jwjp29csxzkpvlzgg-etc’
error: unable to rename ‘/nix/store/jrjysi6dz5kzmm3jwjp29csxzkpvlzgg-etc’ to ‘/nix/store/trash/jrjysi6dz5kzmm3jwjp29csxzkpvlzgg-etc’: Input/output error
1 store paths deleted, 0.00 MiB freed
```

**Comment by shlevy** [comment]
Sometimes I've needed to delete some file manually first.

**Comment by edolstra** [comment]
With an I/O error?

**Comment by shlevy** [comment]
Yup.

**Comment by shlevy** [comment]
Could also be an actual IO error of course :D

**Comment by edolstra** [comment]
`dmesg` shows nothing, so I guess it's a filesystem issue.

**Comment by edolstra** [comment]
Fixed.

**Comment by edolstra** [comment]
Did get a kernel message after all:
```
[Mon Apr 20 14:20:15 2015] EXT4-fs warning (device dm-0): empty_dir:2492: bad directory (dir #12404594) - no `.' or `..'
[Mon Apr 20 14:20:15 2015] EXT4-fs warning (device dm-0): ext4_rmdir:2726: empty directory has too many links (3)
```
I think that happened when I manually removed the empty directory `/nix/store/jrjysi6dz5kzmm3jwjp29csxzkpvlzgg-etc` (after which GC worked again).
