### ISSUE TITLE
Improved documentation

### ISSUE THREAD

**Issue by copumpkin** [NixOS/hydra#210]
In the absence of #197, perhaps the documentation could be improved a bit with a simple step-by-step getting-started guide. I've found lots of out-of-date pages on the wiki and elsewhere but none of them seem to explain how to get it running from beginning to end. The manual seems pretty patchy.

For example, none of the guides I've been able to find (including the manual) explain how to add build machines to hydra. The UI shows me a list containing no machines and no apparent way to add them. It's not a configuration option in the hydra service, and I'm not sure where else to put it.

Even once I find out the answer to that particular issue, I've encountered many others. It seems like we have all the machinery in place to be able to automate this process to be nearly painless (basically #197) but that it isn't there yet, and there isn't documentation in place to help someone who might want to help finish the missing automation.

**Comment by boothead** [comment]
I've run into documentation problems as well and I'm struggling to get it running. Happy to document the process as I work through it. @ryantrinkle/@ocharles I think you've managed to get it working any pointers?

**Comment by copumpkin** [comment]
This is the basic `configuration.nix` I have sorta kinda working:

```nix
{ config, pkgs, ...}:

let
  hydra-git = pkgs.fetchFromGitHub {
    owner  = "NixOS";
    repo   = "hydra";
    rev    = "4c0e3e47034545ad3e9e86dd069138bcebb8ccee";
    sha256 = "08vc76xb7f42hh65j7qvjf58hw36aki5ml343170pq94vk75b1nh";
  };
in {
  imports = [ 
    "${hydra-git}/hydra-module.nix"
  ];

  services.hydra = {
    enable   = true;
    package  = (import "${hydra-git}/release.nix" {}).build.x86_64-linux;
    port     = 3000;
    hydraURL = "http://some-url";
    notificationSender = "some-email@example.com"; 
  };

  services.postgresql = {
    enable = true;
    package = pkgs.postgresql;
  };
}
```

Set `nix.buildMachines` to get remote machines.

**Comment by boothead** [comment]
Thanks @copumpkin I still can't even get it to build though:

```
iles=305, Tests=26572, 177 wallclock secs ( 3.70 usr  0.33 sys + 143.15 cusr 15.66 csys = 162.84 CPU)
Result: FAIL
Failed 1/305 test programs. 1/26572 subtests failed.
Makefile:1715: recipe for target 'test_dynamic' failed
make: *** [test_dynamic] Error 255
builder for ‘/nix/store/izmcc4hrhdswnqn5cdid4aqkprl7xdnr-perl-DBIx-Class-0.082801.drv’ failed with exit code 2
cannot build derivation ‘/nix/store/l1cvb9z0si3gzryldngdl0l6h1jcfaz8-perl-Catalyst-Authentication-Store-DBIx-Class-0.1506.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/2qf1cdnx7fz8idx7lngpz3xlwqs3v7vd-hydra-perl-deps.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/5cpszmrwr191xg07wrpba5y5x4klgq88-hydra-0.1pre1234-abcdef.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/7nx6hai8gb47akmm57g2snd42pqjgy7s-system-path.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/kycp8dw36xica91a51wja54ywmx85w5k-unit-hydra-evaluator.service.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/l7dwsdhm3bqa5bvm09qc4ky231mwsjzy-unit-hydra-init.service.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/05qw6pbgjfaj8ywwn02gsnykphazh8l0-unit-hydra-queue-runner.service.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/hsr154papmy4ghqvb9c5ismbmr5ab4g5-unit-hydra-server.service.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/76qw96adw41jnrjdn88r2fjk7ami7hsr-unit-hydra-update-gc-roots.service.drv’: 1 dependencies couldn't be built
cannot build derivation ‘/nix/store/b4yrmmps17w69gpi87rkx83g9hplhfrv-nixos-15.05pre61966.75ebc3c.drv’: 1 dependencies couldn't be built
```

**Comment by mschristiansen** [comment]
I've added some documentation to the wiki at https://nixos.org/wiki/Installing_hydra_as_nixos_module, would certainly be great with better official documentation, but in the meantime please review and add to the wiki.

**Comment by domenkozar** [comment]
Note there is now https://github.com/peti/hydra-tutorial

**Comment by qknight** [comment]
Note there is also https://nixos.org/wiki/Installing_hydra_as_nixos_module

**Comment by domenkozar** [comment]
@qknight that was linked 2 posts above. I believe that it's best to have a nixops deployment that people can copy around (as hydra-tutorial does it). The rest of the documentation should be united and added to the manual.

**Comment by gilligan** [comment]
Luckily things have become easier and i feel it is OK to closet his issue given the steps and info that has been included in the README now.
