### ISSUE TITLE
Prevent Hydra from building packages based on license

### ISSUE THREAD

**Issue by edolstra** [NixOS/hydra#22]
Hydra (at least the TUD instance) shouldn't build unfree, non-redistributable packages, since that will cause them to end up in public channels. (Alternatively, Hydra should not make them available in channels.)  What makes this tricky is that Hydra doesn't see the meta.license attributes of dependencies, so it can't determine whether a package has an unfree dependency.

One hacky way would be to add an assertion to stdenv.mkDerivation that, conditionally on an environment variable, checks meta.license to throw an exception if the license is unfree.

**Comment by domenkozar** [comment]
This is now implemented.
