### ISSUE TITLE
Allow 'unfree' projects

### ISSUE THREAD

**Issue by mschristiansen** [NixOS/hydra#223]
I'm having problems building a unfree project with Hydra on Nixos with the following in my `/etc/configuration.nix`:
```
 services.hydra = {
      enable = true;
      package = (import /root/hydra/release.nix {}).build.x86_64-linux;
      # dbi = "dbi:Pg:dbname=hydra;host=localhost;user=hydra;";
      hydraURL = "https://someurl.com";
      notificationSender = "my@email.com";
      extraEnv = { HYDRA_DISALLOW_UNFREE = "0"; };
    };
```
I've tried different environment variables in different places for the hydra user and changing both the nix and nixos config. Nothing seems to work.

I've now changed the license to get it to build, but would rather keep the real license.

**Comment by domenkozar** [comment]
You should be able to pass `true` as build input and set it in `release.nix`

**Comment by mschristiansen** [comment]
Thanks, have since started using Circle CI, although I really like how Hydra works. Documentation and general information on Hydra is a bit light and I get the impression that not much is happening on the project.

**Comment by erictapen** [comment]
@domenkozar Could you provide some more information about the fix?

* Is there any doc/source about `HYDRA_DISALLOW_UNFREE`? I can't find it in the `nix`, `nixpkgs` or `hydra` source code.
* Do I need to pass the option (set to false probably?) in the jobset config **or** in my `release.nix`? 

I'm struggling with this for half a year now, so a hint would really help.

**Comment by dtzWill** [comment]
https://github.com/NixOS/nixpkgs/search?q=hydra_disallow_unfree&type=Commits&utf8=✓

Looks like maybe you could set NIXPKGS_ALLOW_UNFREE=1.

I think @domenkozar was referring to the "allowUnfree" config option.

**Comment by tfc** [comment]
Hi there,

i just ran into this problem. So far i tried:

- setting `services.hydra.extraEnv = { NIXPKGS_ALLOW_UNFREE = "1"; };` in `/etc/nixos/configuration.nix`
- pushing `{ config.allowUnfree = true; }` as function arguments into the `import <nixpkgs>` call of my `release.nix`

both to no avail.

(`nixpkgs.config.allowUnfree = true;` is globally set for the whole system.)

Got the `NIXPKGS_ALLOW_UNFREE` from https://github.com/NixOS/nixpkgs/blob/master/pkgs/stdenv/generic/check-meta.nix

But i wonder why both the `release.nix` patch and the extraEnv thing have no effect?
