### ISSUE TITLE
Questions from a potential user

### ISSUE THREAD

**Issue by lukego** [NixOS/hydra#227]
Hydra looks very interesting and I am wondering whether we should consider adopting it for our [Snabb Switch](https://github.com/SnabbCo/snabbswitch/) project. I am writing for advice on whether this might be a sensible idea for us.

Currently we have five servers in our test lab of which one is dedicated to CI (using a [homebrew bash CI](https://github.com/SnabbCo/snabbswitch/tree/master/src/scripts/snabb_bot)) and the others are used for ad-hoc testing. Our current CI requires about an hour per week to maintain and only runs a test every few hours. Currently we are experimenting with NixOS and my initial impression is positive.

Our CI currently does this:

1. Execute a series of pass/fail test cases.
2. Execute benchmarks and check for regressions compared with the reference branch.
3. Log benchmark results for future reference (e.g. ad-hoc gnuplot'ery).
4. Test with QEMU virtual machines using a pre-bootstrapped kernel and disk image.

Some worthy improvements would be:

1. Execute across multiple machines.
2. Run performance regression tests separately on different hardware environments e.g. Sandy Bridge, Ivy Bridge, Haswell, and Skylake CPUs to detect regressions related to hardware features like SIMD and IOMMU.
3. Run tests that depend on specific hardware (our network card device drivers) on machines that have such hardware.
4. Be able to test with multiple reproducible VM kernel and disk images. (Very impressed with the VM bootstrapping examples in the Hydra paper.)

Questions on my mind are whether Hydra would require a lot more time and effort to operate, whether there is an existing way to express our hardware dependencies, and whether it would be easy to integrate with Github.

cc @eugeneia who is the person I would have to sell this concept to.

**Comment by tohl** [comment]
>  4. Test with QEMU virtual machines using a pre-bootstrapped
>     kernel and disk image.
>
> [...]
>
>  4. Be able to test with multiple reproducible VM kernel and
>     disk images. (Very impressed with the VM bootstrapping
>     examples in the Hydra paper.)

Many hydra tests run in QEMU and there is a good support for building
the VMs from nix expressions.  For example NixOS modules (systemd
services) are tested like this.  Letting nix to build the images might
be even more convenient than building the images in adhoc way.

>  1. Execute across multiple machines.

This is a feature of nix.  See buildMachines in nix-daemon.

>  2. Run performance regression tests separately on different
>     hardware environments e.g. Sandy Bridge, Ivy Bridge,
>     Haswell, and Skylake CPUs to detect regressions related to
>     hardware features like SIMD and IOMMU.
>  3. Run tests that depend on specific hardware (our network card
>     device drivers) on machines that have such hardware.

supportedFeatures and mandatoryFeatures might be interesting here.

> Questions on my mind are whether Hydra would require a lot more time
> and effort to operate,

The biggest effort is to write all nix expressions for your packages,
VMs and tests.

**Comment by lukego** [comment]
Thanks! I reckon I will get some more experience with NixOS and NixOps before looking more closely at Hydra.
