### ISSUE TITLE
Implement simple dogpile caching

### ISSUE THREAD

**Issue by avnik** [NixOS/hydra#230]
Problem
--------------

Hydra serves  `.nar` and `.narinfo` directly from local `/nix/store`, so each request take a lot of CPU cycles and disk IO on build machine.

Possible solutions
----------------------------

As we can see in code: https://github.com/NixOS/hydra/blob/master/src/lib/Hydra/View/NixNAR.pm#L16 it simple use pipe to `nix-store --dump`, so change it for 
something like this:

```perl
my $cache = "$cacheDir/$nar";
my $lock = "$cacheDir/.$nar.lock";
if(file_exists("$cache")) {
    open $fh, "$cache";
} else {
    if(mkdir($lock)) {
          system("nix-store --dump '$storePath' | bzip2 >$lock/nar")
          move("$lock/nar", "$cache")
          rmdir($lock)
          open $fh, "$cache";
    } else {
           # Old path for time when cache not ready yet
           open $fh, "nix-store --dump '$storePath' | bzip2 |";
     }
}
```
And likewise for `.narinfo
Cleanup for $cacheDir can be implemented via simple GC agains /nix/store

Another possible solution, is populate static cache by `.nar` right after build completed.

PS I am not very familiar with perl, so treat code above as pseudocode.
But I can try to fix all myself, if someone guide me a bit, how build proper setup for debugging.

**Comment by edolstra** [comment]
What we do on hydra.nixos.org is to have a reverse proxy (Apache httpd) in front of hydra-server to do the caching: https://github.com/NixOS/nixos-org-configurations/blob/master/delft/delft-webserver.nix#L75

In the future, the plan is to have hydra-queue-runner write NARs directly to a binary cache (which could be in the local filesystem or an S3 bucket), so then serving the cache statically becomes trivial.

**Comment by avnik** [comment]
Thanks for explanation.
It goes from discussion on irc, that using hydra as cache overload it too much.
