### ISSUE TITLE
dev-shell uses broken syntax (?) and requires nix-daemon to be running (needlessly?)

### ISSUE THREAD

**Issue by axb21** [NixOS/hydra#236]
This issue concerns commit b0c8eecd3732c09563342a159d31e14cf9bee59e

Cloning the source of this commit and attempting to run

```
    $ ./dev-shell
    $ ./configure $configureFlags --prefix=/opt/hydra
    $ make
    $ make install
```

as suggested in the README.md, I encounter several errors.

One is one line 3: `./dev-shell: 3: exec: -p:: not found`; it seems bash is OK with that syntax, but this script begins with /bin/sh. Changing that line to `$s=$HOME/.nix-profile/bin/nix-shell` works around that issue. The same problem exists on line 6, `export NIX_BUILD_SHELL=$(type -p bash)`.

However, working around that issues then results in the following when `dev-shell` is run

```
$ ./dev-shell
error: cannot connect to daemon at ‘/nix/var/nix/daemon-socket/socket’: Connection refused
(use ‘--show-trace’ to show detailed location information)
```
Starting `nix-daemon` fixes this issue and one can proceed. But why  must `nix-daemon` be running? I have a single-user install and don't use `nix-daemon`.

**Comment by axb21** [comment]
These are still issues as of the latest commit this morning, 7a654259ff996348672729975b49b684d1ab2f8a

```
~/dev/hydra$ ./dev-shell
./dev-shell: 3: exec: -p:: not found
```

After harcoding `s=$HOME/.nix-profile/bin/nix-shell` on line 2:

```
~/dev/hydra$ ./dev-shell
bash: is: No such file or directory
error: cannot connect to daemon at ‘/nix/var/nix/daemon-socket/socket’: Connection refused
(use ‘--show-trace’ to show detailed location information)
```

After harcoding `export NIX_BUILD_SHELL=/bin/bash` on line 2:

```
~/dev/hydra$ ./dev-shell
error: cannot connect to daemon at ‘/nix/var/nix/daemon-socket/socket’: Connection refused
(use ‘--show-trace’ to show detailed location information)
```

After starting `nix-daemon` and the two changes above, `dev-shell` works fine.

**Comment by rbvermaa** [comment]
@axb21 can you test if this fixes the error for you. I suspect your /bin/sh is not bash, like it is on NixOS.

**Comment by axb21** [comment]
@rbvermaa yes, that fixes it. Thank you.

Maybe this is my lack of understanding, and I don't mean to drag out this particular issue, but is there a specific need to run `nix-daemon` to make `dev-shell` work? I can comment out the `export NIX_REMOTE=daemon` and `dev-shell` appears to run as expected; of course, `nix-shell` runs fine without `nix-daemon`.

**Comment by edolstra** [comment]
I think it's for `nix-shell --pure`, but I rarely use that myself when hacking on Hydra. So I would be fine with removing it.

**Comment by rbvermaa** [comment]
I also never use --pure for hydra development. So I vote for removing it.
