### ISSUE TITLE
upgrade to hydra 0.1pre2058-c1dd3fe generates DBI Exception on systemstatus and other tables

### ISSUE THREAD

**Issue by axb21** [NixOS/hydra#241]
After upgrading to hydra 0.1pre2058-c1dd3fe (using nix-1.10pre4212_e12cf82) from hydra-0.1pre1863-fed1cc8, I receive the following error on a variety of pages under the Status menu. Here are two examples.

Status->Queue results in:
```
DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR: column me.globalpriority does not exist
LINE 1: ...nt, me.nixexprinput, me.nixexprpath, me.priority, me.globalp...
^ [for Statement "SELECT me.id, me.finished, me.timestamp, me.project, me.jobset, me.job, me.nixname, me.description, me.drvpath, me.system, me.license, me.homepage, me.maintainers, me.maxsilent, me.timeout, me.iscurrent, me.nixexprinput, me.nixexprpath, me.priority, me.globalpriority, me.busy, me.locker, me.logfile, me.starttime, me.stoptime, me.iscachedbuild, me.buildstatus, me.errormsg, me.size, me.closuresize, me.releasename, me.keep FROM Builds me WHERE ( finished = ? ) ORDER BY globalpriority desc, id" with ParamValues: 1='0'] at /nix/store/n4wq5fh4wsibmr7lhlab3yrh2mnyla9i-hydra-0.1pre2058-c1dd3fe/libexec/hydra/lib/Hydra/Controller/Root.pm line 90
```

Status->Machine Status results in this error:
```
DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR: relation "systemstatus" does not exist
LINE 1: SELECT me.what, me.status FROM SystemStatus me WHERE ( me.wh...
^ [for Statement "SELECT me.what, me.status FROM SystemStatus me WHERE ( me.what = ? )" with ParamValues: 1='queue-runner'] at /nix/store/n4wq5fh4wsibmr7lhlab3yrh2mnyla9i-hydra-0.1pre2058-c1dd3fe/libexec/hydra/lib/Hydra/Controller/Root.pm line 116
```

There were no such errors when I used hydra-0.1pre1863-fed1cc8, and I've verified that rolling back to hydra-0.1pre1863-fed1cc8 eliminates these errors.

There's some database update step required, apparently. However, the usual `nix-env --upgrade` command did not perform that upgrade, nor throw a warning that it was necessary (if it did my bad because I didn't see it).

In the short term, could someone please point me to information regarding what I need to do to the postgres database to getting hydra functioning again? In the longer term, wouldn't it make sense to have `nix-env --upgrade` take care of necessary database migrations or warn the user that one is necessary?

**Comment by rbvermaa** [comment]
Did you run hydra-init? http://hydra.nixos.org/build/25709093/download/1/hydra/manual.html#idm140737316821328

**Comment by axb21** [comment]
@rbvermaa: thank you for this. I have to *facepalm* because I forgot to do that. It did not work for me at first, however, so I figured I'd detail what happened. I do have the new hydra working now, so might as well close this issue. 

The previous version of hydra I mentioned worked fine on my postgres 9.1 cluster, whereas this new one requires postgres 9.3 or better. The postgres upgrade is not exactly trivial, though proceeded without error for me. This might affect other people so here's some info that was helpful for me.

When I ran `hydra-init`, I was given this error:
```
upgrading Hydra schema from version 32 to 33
executing SQL statement: create table FailedPaths (
    path text primary key not null
)
NOTICE:  CREATE TABLE / PRIMARY KEY will create implicit index "failedpaths_pkey" for table "failedpaths"
executing SQL statement: create rule IdempotentInsert as on insert to FailedPaths
  where exists (select 1 from FailedPaths where path = new.path)
  do instead nothing
upgrading Hydra schema from version 33 to 34
executing SQL statement: create table SystemStatus (
    what text primary key not null,
    status json not null
)
schema upgrade failed: main::run_(): DBI Exception: DBD::Pg::db do failed: ERROR:  type "json" does not exist
LINE 3:     status json not null
                   ^ at /nix/store/n4wq5fh4wsibmr7lhlab3yrh2mnyla9i-hydra-0.1pre2058-c1dd3fe/bin/.hydra-init-wrapped line 59
```

A bit of googling the errors in that failure revealed the `json` type mentioned was introduced in postgres 9.3. I had server version 9.1.13. You can check this by using `psql` and then `SELECT version();`; the version number of psql need not match the version of the cluster you're running. Mine said:
```
                                                   version                                                    
--------------------------------------------------------------------------------------------------------------
 PostgreSQL 9.1.13 on x86_64-unknown-linux-gnu, compiled by gcc (Ubuntu/Linaro 4.8.1-10ubuntu9) 4.8.1, 64-bit
(1 row)
```

I use Ubuntu vivid (15.04), and the default postgres sever version is 9.1.13 I guess. So, I had to add a PPA, then explicitly install a couple postgres 9.4 packages.

The not-obvious part of the upgrade is that you have to stop the cluster you're running, upgrade that to version 9.4 (or 9.3 if you opted for that one), and then restart the cluster. I followed the guide in http://nixmash.com/postgresql/upgrading-postgresql-9-1-to-9-3-in-ubuntu/, which worked fine for me.
