### ISSUE TITLE
hydra-queue-runner: Use substitutes

### ISSUE THREAD

**Issue by peti** [NixOS/hydra#243]
`hydra.cryp.to` happily re-builds the entire stdenv from scratch after the recent staging merge (http://hydra.cryp.to/build/1307569) despite the fact that it those binaries are available for download from `hydra.nixos.org`, and this fact is *known* to Nix because I `nix-pull`ed the appropriate manifest. In fact, when I run a build as a local user on `hydra.cryp.to`, then it *does* take advantage of the binary cache:

~~~~~
[simons@hydra:~/src/nixpkgs]$ nix-build --no-out-link . -A stdenv --dry-run
these paths will be fetched (0.00 MiB download, 150.72 MiB unpacked):
  /nix/store/060gkj72sjplr0r7bvbnkyibk7biflc3-diffutils-3.3
  /nix/store/1ahc5vcckbr9sbgrma14w15jgs0g3a0b-ed-1.12
  /nix/store/4n9yj90rdggqcx34ylbshryg3rf9cqpj-gcc-wrapper-4.9.3
  /nix/store/6vv7kcy88p49yzkbkqqg76mdinjkyb45-findutils-4.4.2
  /nix/store/8xfxnm4a7jvyh0i1sd967z6rws8lh21a-coreutils-8.24
  /nix/store/8z667vv1agvpd3iknmk94j0ix6bv413i-attr-2.4.47
  /nix/store/9zp90x611wgkw3zq920yj3vgvfgl1dqn-gnused-4.2.2
  /nix/store/cn92yjk95597cd92rpjaly5pmr9mhsak-paxctl-0.9
  /nix/store/g2pkpyil8a36waw1w57swj7r2a7qlk5z-gawk-4.1.3
  /nix/store/h84kc62s87mknjrln5rd6s332zfxfrk5-stdenv
  /nix/store/hhyaq5l6a7arifi2siq08m2bbqq074zi-xz-5.2.1
  /nix/store/i9nn1fkcy95dzf0hb9wi8gbkid3iw1sa-gcc-4.9.3
  /nix/store/ihk41s2ffyb0bnl20wl20srjcgnr7f19-patchelf-0.8
  /nix/store/kp8jj4jfm27sw5y1snx1wi2x38g81q34-gnumake-4.1
  /nix/store/kxf1p7l7lgm6j5mjzkiwcwzc98s9f1az-binutils-2.23.1
  /nix/store/mld9mwhxzrvj828h17cl384alk250h7i-gnutar-1.28
  /nix/store/nzjshzqi2vczk146hfixxgz8x0lhya4q-gzip-1.6
  /nix/store/rgfqh21a4sv0vq75pckd355chfqxbyrg-pcre-8.37
  /nix/store/sk0b1r840b686zc2m8mzyw8yyq1aymqh-acl-2.2.52
  /nix/store/viaj0jy9xvn7jjr6m6b24r7mvg4irmzf-gnugrep-2.21
  /nix/store/x03rsglrx6810jyj64np01j5ynsf27m6-patch-2.7.5
  /nix/store/xag5ayq906w9zhlxs8wayv4kvpiyqphq-bash-4.3-p42
  /nix/store/zjrzznvaa10kli1bfak52857s8wi34zg-bzip2-1.0.6
~~~~~

Is there an obvious explanation for this phenomenon? And more importantly, is there a way to revert to the old behavior where Hydra would download those binaries instead of re-building them itself?

I'm running the `hydra-0.1pre2062-ae2cc61`, the latest available version from the channel.

**Comment by edolstra** [comment]
The new queue runner doesn't support substitutes at the moment. The only workaround is to revert to version cf9516baa456c037b8faf0d3af1641ddd78774d1 (the last commit before the queue runner merge).

**Comment by peti** [comment]
The older commit will still work with the updated PostgreSQL database schema?

**Comment by edolstra** [comment]
Hm no, you'd have to undo the effect of a bunch of schema changes :-(

**Comment by peti** [comment]
OK. That's not really practical. I'll just live with the re-builds. Thank you for the quick response!

**Comment by ctheune** [comment]
Not sure whether I can work on this, but I'm being bitten by this, too. Why did it go away? What's the issue in bringing it back?

**Comment by ctheune** [comment]
W00t! Trying this out right away ... :) Thanks!
