### ISSUE TITLE
Commit b8ff29f0db6d31c70a3c6593277573d4054b46ea (2015-10-07) doesnt compile

### ISSUE THREAD

**Issue by tohl** [NixOS/hydra#245]
g++ -DHAVE_CONFIG_H -I. -I../..    -I/nix/store/x8l1vvq8fbwlx1iizf5sx2blb4fqcrlh-boehm-gc-7.2f/include -I/nix/store/nnzngkxwy4q4yb5p33jrzg8xnlmb3an4-nix-1.10pre4212_e12cf82/include/nix  -Wall -g -O2 -std=c++11 -c -o builder.o builder.cc
builder.cc: In member function 'bool State::doBuildStep(std::shared_ptr<nix::StoreAPI>, Step::ptr, Machine::ptr)':
builder.cc:303:38: error: 'LogLimitExceeded' is not a member of 'nix::BuildResult'
                     result.status == BuildResult::LogLimitExceeded ? bsLogLimitExceeded :
                                      ^
builder.cc:308:38: error: 'LogLimitExceeded' is not a member of 'nix::BuildResult'
                     result.status == BuildResult::LogLimitExceeded ? bssLogLimitExceeded :
                                      ^
builder.cc:318:38: error: 'LogLimitExceeded' is not a member of 'nix::BuildResult'
                     result.status == BuildResult::LogLimitExceeded)
                                      ^
make[3]: *** [builder.o] Error 1
make[3]: Leaving directory `/tmp/nix-build-hydra-0.1pre1234-abcdef.drv-0/hydra-0.1pre1234-abcdef/src/hydra-queue-runner'
make[2]: *** [all-recursive] Error 1
make[2]: Leaving directory `/tmp/nix-build-hydra-0.1pre1234-abcdef.drv-0/hydra-0.1pre1234-abcdef/src'
make[1]: *** [all-recursive] Error 1
make[1]: Leaving directory `/tmp/nix-build-hydra-0.1pre1234-abcdef.drv-0/hydra-0.1pre1234-abcdef'
make: *** [all] Error 2
build time elapsed:  0m0.095s 0m0.032s 0m18.778s 0m2.764s
builder for ‘/nix/store/sn9misvva39jam9zhbngymdwydq1vgfx-hydra-0.1pre1234-abcdef.drv’ failed with exit code 2

**Comment by edolstra** [comment]
Yeah, I need to bump `nixUnstable` in Nixpkgs.

**Comment by edolstra** [comment]
Done.
