### ISSUE TITLE
problem with remote building of i686-linux packages

### ISSUE THREAD

**Issue by tohl** [NixOS/hydra#246]
Hi,

since a few weeks ago, my hydra is not able to test i686-linux packages.  A i686-linux package gets evaluated, put in a queue and schedulled for build on a remote machine, but it just stays like that for ever until I cancel the build manually.  Has something changed in this regard and what do i need to do to get it to work again?  The i686-linux packages used to work, they build and work even now on my nixos desktop, but somehow hydra doesn't seem to get them to be build by the remote build slaves.  I have no problem with x86_64-linux packages.

I'm on commit ae2cc61be63550e0b67ea82c60defdaf2da5d99b.

Here is relevant hydra configuration:

<pre>
  nix = {
    distributedBuilds = true;
    buildMachines = [
      {
        hostName = "slave1";
        maxJobs = 4;
        sshKey = "/var/lib/hydra/queue-runner/.ssh/id_rsa";
        sshUser = "root";
        system = "x86_64-linux";
        supportedFeatures = ["kvm" "nixos-test"];
      }
      {
        hostName = "slave2";
        maxJobs = 2;
        sshKey = "/var/lib/hydra/queue-runner/.ssh/id_rsa";
        sshUser = "root";
        system = "x86_64-linux";
        supportedFeatures = [];
      }
    ];
    gc = {
      automatic = true;
      dates = "03:15";
    };
  };
  programs.ssh.extraConfig = "ConnectTimeout 30";
</pre>

**Comment by tohl** [comment]
sorry for the noise, looks like another access rights problem that i still need to chase down

**Comment by tohl** [comment]
hmm that was some old log that hydra was showing

with the current issue, i dont get any log yet

**Comment by edolstra** [comment]
You need to say `system = "x86_64-linux,i686-linux";`.

**Comment by tohl** [comment]
that helped, thank you!
