### ISSUE TITLE
"Restart all aborted builds" exceeds PostgreSQL size limits for sufficiently many builds

### ISSUE THREAD

**Issue by peti** [NixOS/hydra#247]
http://hydra.nixos.org/eval/1223770 has 40,000+ aborted builds, and the web front-end cannot restart them. When I try, I get an "internal error" because the database server can't cope with the size of the generated SQL statement.

**Comment by domenkozar** [comment]
This is fixed now right?

**Comment by domenkozar** [comment]
I've managed now to restart the builds (canceled them right after). So this is working correctly now.
