### ISSUE TITLE
nixexprs.tar.bz2 contains broken channel/default.nix with else<EOF>

### ISSUE THREAD

**Issue by calbrecht** [NixOS/hydra#254]
At this very moment this happens for https://hydra.mayflower.de/jobset/nixos/hydra-jobs/channel/latest
you may verify this with:

```
channel=https://hydra.mayflower.de/jobset/nixos/hydra-jobs/channel/latest
curl $channel/nixexprs.tar.bz2 | tar -j -x channel/default.nix -f - -O | tail
```

though this has happened for http://hydra.nixos.org/jobset/gnu/emacs-trunk/channel/latest before as well.

One thing they both have in common (i guess) is that in configuration there is only one system defined.

https://github.com/mayflower/hydra-jobs/blob/master/default.nix

```
supportedSystems ? [ "x86_64-linux" ]
```

and http://hydra.nixos.org/jobset/gnu/emacs-trunk#tabs-configuration

```
system  String value    "x86_64-linux"
```

next guess is that in combination with failing jobs within a jobset this leads to a broken default.nix which ends without newline with else

**Comment by calbrecht** [comment]
This is the perl script that creates the tar https://github.com/NixOS/hydra/blob/master/src/lib/Hydra/View/NixExprs.pm

**Comment by domenkozar** [comment]
Is this still happening?

**Comment by calbrecht** [comment]
Yes, just tried the two cmd lines from description right now:
    
    channel=https://hydra.mayflower.de/jobset/nixos/hydra-jobs/channel/latest
    curl $channel/nixexprs.tar.bz2 | tar -j -x channel/default.nix -f - -O | tail
