### ISSUE TITLE
staging-small full failure due to https url in bzip2 package

### ISSUE THREAD

**Issue by mcmtroffaes** [NixOS/hydra#257]
Hydra is fully failing on staging-small:

https://hydra.nixos.org/jobset/nixos/staging-small

On this build log:

https://hydra.nixos.org/build/28020172/nixlog/1

you can see that the failure this is due to curl not supporting https when fetching a recently introduced patch from github. The apparently offending https url for the patch was introduced in https://github.com/NixOS/nixpkgs/pull/11127 (which I authored). As far as I can tell, github enforces https (see curl log below), so I suspect that just changing https to http in the url will not fix this problem. Is there anything I can do to help resolving this?

cc @peti

```
$ curl -v http://raw.githubusercontent.com/niXman/mingw-builds/17ae841dcf6e72badad7941a06d631edaf687436/patches/bzip2/bzip2-1.0.6-autoconfiscated.patch
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0*   Trying 185.31.19.133...
* Connected to raw.githubusercontent.com (185.31.19.133) port 80 (#0)
> GET /niXman/mingw-builds/17ae841dcf6e72badad7941a06d631edaf687436/patches/bzip2/bzip2-1.0.6-autoconfiscated.patch HTTP/1.1
> User-Agent: curl/7.40.0
> Host: raw.githubusercontent.com
> Accept: */*
> 
< HTTP/1.1 301 Moved Permanently
< Server: Varnish
< Retry-After: 0
< Location: https://raw.githubusercontent.com/niXman/mingw-builds/17ae841dcf6e72badad7941a06d631edaf687436/patches/bzip2/bzip2-1.0.6-autoconfiscated.patch
< Content-Length: 0
< Accept-Ranges: bytes
< Date: Mon, 23 Nov 2015 10:47:05 GMT
< Via: 1.1 varnish
< Connection: close
< X-Served-By: cache-lhr6320-LHR
< X-Cache: HIT
< X-Cache-Hits: 0
< Access-Control-Allow-Origin: *
< Expires: Mon, 23 Nov 2015 10:52:05 GMT
< Vary: Authorization,Accept-Encoding
< 
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
* Closing connection 0
```

**Comment by peti** [comment]
Would it be possible to move that patch into the `crossAttrs` section? Our `curl` binary has support for HTTPS -- only the `stdenv` bootstrapping version lacks this feature, and since we don't have a pure `stdenv` on mingw the platform shouldn't run into this issue like Linux does.

**Comment by mcmtroffaes** [comment]
Absolutely. We can revert https://github.com/NixOS/nixpkgs/pull/11127 and instead merge https://github.com/NixOS/nixpkgs/pull/11126 - I'll set up a new pull request for it.

**Comment by peti** [comment]
Thank you for the quick fix! I merged https://github.com/NixOS/nixpkgs/pull/11221 a moment ago.

**Comment by mcmtroffaes** [comment]
You're welcome, thanks for the quick merge.
