### ISSUE TITLE
Compute closure size for hydra jobs

### ISSUE THREAD

**Issue by copumpkin** [NixOS/hydra#258]
It looks like it can already show us the runtime dependency graph, so computing the closure size doesn't seem much harder. Computing the runtime closure size for a set of things can easily be memoized so it doesn't take nearly as much work as doing the naive thing for each package.

I'm thinking of this in the context of @edolstra adding a Hydra jobset for @vcunat's multiple outputs work, where it would probably be valuable to watch output sizes shrink (visually in a nice chart!) as improvements are made.

**Comment by vcunat** [comment]
Hydra shows graphs of closure sizes already ;-)

**Comment by copumpkin** [comment]
Oh! Where? I poked around a bit and must've missed it.

**Comment by vcunat** [comment]
See the charts: http://hydra.nixos.org/job/nixos/trunk-combined/nixpkgs.firefox.x86_64-linux#tabs-charts

**Comment by copumpkin** [comment]
@vcunat thanks!! I feel like I've gained a new superpower :smile:

**Comment by vcunat** [comment]
A pity that the new jobset will start anew, so we won't see the drop on the graph (until we merge to some staging or master).
