### ISSUE TITLE
The option `inputType' defined in `<unknown-file>' does not exist.

### ISSUE THREAD

**Issue by nckx** [NixOS/hydra#260]
Hi,

I haven't a clue how to debug [this](http://hydra.is.my/jobset/nixos/dm1#tabs-errors). Everything evaluates fine manually. Any ideas?

```
in job ‘options’:
The option `inputType' defined in `<unknown-file>' does not exist.

in job ‘vmWithBootLoader’:
The option `inputType' defined in `<unknown-file>' does not exist.

in job ‘nixFallback’:
The option `inputType' defined in `<unknown-file>' does not exist.

in job ‘vm’:
The option `inputType' defined in `<unknown-file>' does not exist.

in job ‘config’:
The option `inputType' defined in `<unknown-file>' does not exist.

in job ‘system’:
The option `inputType' defined in `<unknown-file>' does not exist.
```

**Comment by nckx** [comment]
[Latest HEAD](https://github.com/NixOS/hydra/commit/8f7614030e6950f389e04d8077e7793cde1e6305), by the way.

**Comment by domenkozar** [comment]
@nckx did you resolve this issue?

**Comment by nckx** [comment]
I switched from Hydra to a 10-line `while true; do nix-build ...; done` script not long after, and have been much happier ever since. I'll close this now.

Thanks for going through these!
