### ISSUE TITLE
Persona will shutdown in November 2016

### ISSUE THREAD

**Issue by domenkozar** [NixOS/hydra#265]
https://mail.mozilla.org/pipermail/persona-notices/2016/000005.html

**Comment by edolstra** [comment]
Some possible alternatives:
* Passwordless login.
* OAuth2.

**Comment by domenkozar** [comment]
I see two possibilities:

- someone else will officially take over Persona (since it's OSS)
- use Github OAuth since we use it already

**Comment by domenkozar** [comment]
https://github.com/NixOS/hydra/commit/bbe45ed8443d49bec45f333ed210ee127cb667e6
