### ISSUE TITLE
Install nixops on ubuntu hit Curl error 22

### ISSUE THREAD

**Issue by LiliDeng** [NixOS/hydra#274]
Use below steps install nix and nixops, hit issue, could you help resolve it? Thanks! 
  1  curl https://nixos.org/nix/install | sh
   2  nix-channel --add http://nixos.org/channels/nixos-unstable
   3  nix-channel --update
   4  export NIX_PATH=/nix/var/nix/profiles/per-user/root/channels/nixos
   5  nix-install-package --non-interactive --url http://hydra.nixos.org/build/26457165/nix/pkg/nixops-1.3-x86_64-linux.nixpkg

Installing package...
warning: the group ‘nixbld’ specified in ‘build-users-group’ does not exist
installing ‘nixops-1.3’
download-from-binary-cache.pl: could not download ‘http://hydra.nixos.org/nix-cache-info’ (Curl error 22)
don't know how to build these paths:
  /nix/store/5h1654v8jjfwjry40lbym18p8vdw58ax-nixops-1.3
error: path ‘/nix/store/5h1654v8jjfwjry40lbym18p8vdw58ax-nixops-1.3’ does not exist and cannot be created

Installation failed: nix-env failed: 256

**Comment by domenkozar** [comment]
@edolstra hmm why is it hitting hydra cache?
