### ISSUE TITLE
All build input information is lost when validation fails

### ISSUE THREAD

**Issue by karltk** [NixOS/hydra#28]
When I create a new jobset with an invalid input name, then hit Create, I get to an error page. When I hit 'back', the form is emptied and all my build inputs are lost.

This can be reproduced by creating a new job set, then adding an input with a "name" starting with a number, e.g. 3rdparty, that points to an arbitrary local path, then hitting the Create button, then hitting the browser's back button.

I would expect the validation to happen as I type, so that I didn't lose my inputs when I hit Create.

**Comment by gilligan** [comment]
This has been fixed in 232f46c750af491ac80ab845ef36182d7bc88e48
i just verified it locally.
