### ISSUE TITLE
Cannot add individual builds to releases

### ISSUE THREAD

**Issue by svanderburg** [NixOS/hydra#282]
When clicking on a build (e.g. disnix:disnixos-trunk, http://hydra.nixos.org/build/33130082), unfolding the 'Actions' bar and selecting 'Add to release', I get the following error:

500 Internal Server Error 

This build is no longer available.

Could it be the case that builds can't be added, since their results are not stored locally anymore (since the S3 binary cache has been introduced)?

**Comment by edolstra** [comment]
Yes, that sounds correct.

**Comment by svanderburg** [comment]
So is this a bug? Or should releases be created in a different way from now on?

**Comment by edolstra** [comment]
It's a bug (or unimplemented feature, take your pick), but I've also been thinking about removing the release feature since it's not all that useful or widely used.
