### ISSUE TITLE
no match in usermap "hydra-users" for user "hydra" authenticated as "nscd"

### ISSUE THREAD

**Issue by peti** [NixOS/hydra#284]
I'm seeing a lot of errors like the following in my systemd journal:

~~~~~
Mar 16 14:07:03 hydra postgresql-start[32428]: LOG:  no match in usermap "hydra-users" for user "hydra" authenticated as "nscd"
Mar 16 14:07:03 hydra postgresql-start[32428]: FATAL:  Peer authentication failed for user "hydra"
Mar 16 14:07:03 hydra hydra-send-stats[2104]: error: FATAL:  Peer authentication failed for user "hydra"
Mar 16 14:07:03 hydra hydra-send-stats[2104]: cannot get queue runner stats
~~~~~~

Is there an easy way to fix that?

**Comment by edolstra** [comment]
Can you check /etc/passwd? Maybe there is a UID clash between `hydra` and `nscd`.

**Comment by peti** [comment]
You are right. They both use uid 499.

**Comment by edolstra** [comment]
Hm, that's worrying, maybe there is a bug in `nixos/modules/config/update-users-groups.pl` (unless you manually specified the 499 uid).

**Comment by peti** [comment]
Yeah, I think this is my fault. When I installed my machine ~2 years ago, NixOS picked uid 499 because it was free at the time. At some point, I switched to declarative user management and basically just hard-coded that choice in `configuration.nix` without realizing that it conflicts with `nscd`.

Anyway, thank very much you for the quick response!
