### ISSUE TITLE
No channel for hydra on http://hydra.nixos.org/project/hydra?

### ISSUE THREAD

**Issue by axb21** [NixOS/hydra#287]
I used to update my hydra install via `nix-channel --update` and `nix-env --upgrade`. However, at some time I couldn't pinpoint, this stopped working. This is the error I see when I `nix-channel --update`:

```
error: unable to download ‘http://hydra.nixos.org/jobset/hydra/master/channel/latest/nixexprs.tar.bz2’: HTTP response code said error (22)
cannot fetch ‘http://hydra.nixos.org/jobset/hydra/master/channel/latest/nixexprs.tar.bz2’
```
It appears the most recent builds of hydra are failing on http://hydra.nixos.org/jobset/hydra/master#tabs-evaluations; see attached screencap, or that link. 

![hydra](https://cloud.githubusercontent.com/assets/3464572/14061889/fe03e0bc-f362-11e5-9b77-53fd96b37218.png)

Is there a suggested way to keep hydra up to date? Use a different channel? Build and install from source? Leave hydra at current installed version?  Thanks.

**Comment by domenkozar** [comment]
See https://github.com/peti/hydra-tutorial/blob/master/hydra-master.nix#L7

**Comment by axb21** [comment]
@domenkozar: hi thanks for the Info. My question was more about the hydra channel on hydra.nixos.org. It used to work, now it does not. Is that known/planned, or not? Is it going to stay that way, or is it going to be fixed? I'd like to know so that I an decide to wait it out till it's fixed and then keep using nix to update hydra; or, switch to another method for updating hydra.

**Comment by domenkozar** [comment]
See a74251af2b64fed879a0f933d450149c3a1d0ef4

**Comment by axb21** [comment]
@domenkozar: thanks for this info, it makes sense now. I am not sure whether to close this or leave it open? If it is intended behavior then I'm happy to close it (or someone else can). Mainly I wanted to put this here in case it was an actual bug.
