### ISSUE TITLE
Display build products in table format

### ISSUE THREAD

**Issue by rickynils** [NixOS/hydra#288]
If a build produces several products, the current design looks kind of messy. See my attached screenshot below. I propose formatting the build products like a table instead, just as "Changes" and "Previous builds". That would also allow for more info (like product size) to be displayed directly without clicking "Details".

Possibly, the build products could even have a dedicated tab (like "Inputs", "Build steps" etc).

**Current look:**

![build_products](https://cloud.githubusercontent.com/assets/16779/14200764/7d1d956c-f7ed-11e5-96a2-3aec11d21bec.png)

**Comment by domenkozar** [comment]
Closing in favor of PR.

**Comment by domenkozar** [comment]
This is now in master.
