### ISSUE TITLE
Add a button to cancel a build in progress

### ISSUE THREAD

**Issue by edolstra** [NixOS/hydra#29]
The only way right now to cancel a running build is to log in to the server, figure out the right pid, and kill it. Would be nice to have a way to do that from the web interface.

**Comment by domenkozar** [comment]
Pretty sure this duplicates https://github.com/NixOS/hydra/issues/44

**Comment by Taneb** [comment]
Has there been any work on this? It's something I would have found useful at work.

**Comment by edolstra** [comment]
Closing this issue, since build cancellation was implemented quite a while ago (b3169ce4389701fc77ee3e142ebb0cdd7a9fea18).
