### ISSUE TITLE
Substitutes from upstream Hydra don't always happen

### ISSUE THREAD

**Issue by domenkozar** [NixOS/hydra#297]
I'm having a hard time with Hydra not substituting from upstream.

Upstream Hydra package for R: http://hydra.nixos.org/build/34357339#tabs-details
Snabb Hydra package for R: https://hydra.snabb.co/build/80#tabs-details

So Snabb Hydra goes and builds R from source, but then hits https://github.com/NixOS/nixpkgs/issues/10026

I'm using the latest commit in master (https://github.com/NixOS/hydra/commit/b2b978eda098be656f43a82b99c6b49d52137832).

Is this expected behavior? I would expect R to be substituted from cache.nixos.org.

**Comment by domenkozar** [comment]
cc @edolstra 

Configuration for binary caches: https://github.com/snabblab/snabblab-nixos/blob/master/modules/common.nix#L51

If I run the command manually on the Hydra master it does substitute:

```
[domenkozar@eiger:~/nixpkgs]$ nix-build -A R
these paths will be fetched (27.90 MiB download, 43.64 MiB unpacked):
  /nix/store/iyabbnf9l4dlail058v5achhlic4ppwv-R-3.2.3
fetching path ‘/nix/store/iyabbnf9l4dlail058v5achhlic4ppwv-R-3.2.3’...

*** Downloading ‘https://cache.nixos.org/nar/0qcrskjvcdiqlrr9xjbdkc1j14rk7q48py1pkq8k9nz76h6ly874.nar.xz’ (signed by ‘cache.nixos.org-1’) to ‘/nix/store/iyabbnf9l4dlail058v5achhlic4ppwv-R-3.2.3’...
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0 27.9M    0 17037    0     0  28595      0  0:17:03 --:--:--  0:17:03 28585^Cerror: interrupted by the user
```

**Comment by edolstra** [comment]
Try removing `--option build-use-substitutes false` in `hydra-module.nix`.

**Comment by domenkozar** [comment]
@edolstra indeed that works. Should we change the NixOS module? Not sure what the original intention was beyond saving a few HTTP requests

**Comment by edolstra** [comment]
Well, those few HTTP requests significantly slow down the queue monitor thread, which is why it's disabled.

Also, I think currently Hydra will sign binaries that it got via substitution (rather than building), which is not desirable.

**Comment by peti** [comment]
See https://github.com/NixOS/hydra/pull/298.
