### ISSUE TITLE
/api/push-github broken

### ISSUE THREAD

**Issue by edolstra** [NixOS/hydra#309]
Github reports a 500 response from http://hydra.nixos.org/api/push-github for the NixOS/nix repo.

**Comment by expipiplus1** [comment]
In `push_github` `$c->{stash}` is `undef`.

**Comment by domenkozar** [comment]
#331 fixes this

**Comment by domenkozar** [comment]
I'm still getting 500:

```
Aug 16 22:03:07 eiger hydra-server[21593]: [error] Couldn't render template "file error - api/push_github.tt: not found"
```

**Comment by expipiplus1** [comment]
Ah, sorry. My PR fixed an issue unrelated to the 500 response. Good to see this is fixed though!
