### ISSUE TITLE
Update to new Nix logo

### ISSUE THREAD

**Issue by copumpkin** [NixOS/hydra#313]
The public Hydra still uses the old logo in the upper left corner. Can we point it at the new logo to get more consistent branding across the projects?

**Comment by domenkozar** [comment]
Somebody make a PR with tiny new logo and let's go? :)

**Comment by copumpkin** [comment]
https://github.com/NixOS/nixos-org-configurations/pull/25#event-993111825 should fix it next time Hydra gets deployed
