### ISSUE TITLE
Hydra module doesn't build

### ISSUE THREAD

**Issue by abbradar** [NixOS/hydra#319]
When trying to switch to a new configuration with a latest Hydra checkout and current nixos-unstable channel I get this:

```
checking for NIX... no
configure: error: Package requirements (nix-main nix-expr nix-store) were not met:

No package 'nix-main' found
No package 'nix-expr' found
No package 'nix-store' found
```

When I run `nix-shell` inside of hydra root, I have:
```
[nix-shell:~/hydra]$ nix --version
nix (Nix) 1.12pre4523_3b81b26
```

This clearly satisfies [the version requirement](https://github.com/NixOS/hydra/blob/master/release.nix#L36). I'm not sure what's going on here; could it be that [my nixpkgs commit](https://github.com/NixOS/nixpkgs/commit/be5b596deb7f619fdc47dc2d39940bed8bf9a44d) is too old? I haven't noticed any Nix updates from that point. Also, I don't have `nix.package = pkgs.nixUnstable` in my configuration FWIW.

**Comment by domenkozar** [comment]
See #307

**Comment by domenkozar** [comment]
This should be fixed in master now.
