### ISSUE TITLE
Store both the submission and the termination date of builds

### ISSUE THREAD

**Issue by civodul** [NixOS/hydra#32]
Currently the `timestamp' slot of`Builds' stores either the time a build was queued, or the time at which it finished.

What about storing both the time at which it was queued, the time at which it was scheduled, and the time at which it finished building?

This would allow Hydra admins to "profile" their build farm.

**Comment by gilligan** [comment]
we now actually have `starttime`, `stoptime` and `timestamp`. I think this should be sufficient to carry out profiling as you envisioned.
