### ISSUE TITLE
Post build hooks are not triggered when a build has been cached.

### ISSUE THREAD

**Issue by expipiplus1** [NixOS/hydra#342]
## Steps to reproduce using the Slack plugin as an example
- Create a repo and hydra instance set up to post to a Slack channel
- Push an initial change to the repo
- Observe that the build has changed to success and hydra posts to Slack
- Push a change to break the build
- Observe that the build has changed to failure and hydra posts to Slack
- Use `git revert HEAD` to undo the last change and push
- _Observe that Slack does not post about the build becoming successful to Slack_
## What I think is happening

The hash of the build inputs is the same since we're not using KEEP_DOT_GIT, hydra uses the prebuilt derivation so the `buildFinished` plugin hook never fires, so nothing gets posted to slack.

CC @shlevy

**Comment by shlevy** [comment]
This isn't specific to slack plugin. @edolstra thoughts on hooks for cached builds?

**Comment by expipiplus1** [comment]
I've also had this happen with declarative projects, but reproducing it is a little more tricky. A hook for cached builds would be great.

**Comment by expipiplus1** [comment]
Have there been any thoughts on this? It makes it hard to depend on Hydra for giving the OK to merge a PR on Github.
