### ISSUE TITLE
Allowing the definition of a minimum version control poll delay

### ISSUE THREAD

**Issue by civodul** [NixOS/hydra#35]
Would be nice if a delay between version control polls ("svn up"  and such) could be set, so as to reduce bandwidth consumption and avoid DoS-looking behavior (a couple of svn admins have already reported being annoyed.)

Ideally, one would say, per-project or per-jobset, "poll every 30 seconds, at most."  The evaluator would thus need an actual scheduler for all the polls.

**Comment by gilligan** [comment]
this has been available for a while.
