### ISSUE TITLE
Hydra should enqueue dependencies of failed jobs being restarted

### ISSUE THREAD

**Issue by obadz** [NixOS/hydra#369]
If a and b depend on c, and c failed due to some spurious reasons, restarting c should lead to a and b being built.

Most common usecase is a transient failing test holding up a release. Restarting the test should lead to a release if the test succeeds.

**Comment by domenkozar** [comment]
Duplicates https://github.com/NixOS/hydra/issues/169

**Comment by obadz** [comment]
Fair enough though I think mine was more carefully worded :-D
