### ISSUE TITLE
[question] use cases for jobsets default channels?

### ISSUE THREAD

**Issue by ericsagnes** [NixOS/hydra#374]
Jobsets default channels are using `mkFakeDerivation` that give them a very limited usage as it seems impossible to source build a package using these channels.

- What are the use cases for jobset default channels?
- In case their usage is limited or overtaken by [channel expressions](https://github.com/NixOS/hydra/pull/211), should they be deprecated?

**Comment by domenkozar** [comment]
@ericsagnes see https://github.com/NixOS/hydra/issues/141

**Comment by ericsagnes** [comment]
@domenkozar Thanks, that was helpful.

Just a thought, but in the future it might be useful to rename the jobset default channels to "binary channel" or "automatic binary channel" to have a better differentiation between the two channel types.

To summarize, in case someone find this issue and is interested in the answers.

#### What are the use cases for jobset default channels?

Default channels can be used with `nix-env`, but only if a binary substitute is available as `mkFakeDerivation` doesn't know how to do source builds.

When #141 will be merged, the use case will widen as packages in default channels could be used as build inputs to other packages.

#### In case their usage is limited or overtaken by channel expressions, should they be deprecated?

Default channels are easier to set up than channel expressions as they are automatically set up for every jobset.
Also they don't require a special setup on the source side like channels expressions do.

**Comment by sbourdeauducq** [comment]
> Also they don't require a special setup on the source side like channels expressions do.

What should that "special setup" be?
