### ISSUE TITLE
can't download trunk darwin builds

### ISSUE THREAD

**Issue by l2dy** [NixOS/hydra#385]
<https://hydra.nixos.org/build/38954002/nix/pkg/nix-1.11.2-x86_64-darwin.nixpkg> from <https://hydra.nixos.org/build/38954002> shows me
```
404 Not Found
Path /nix/store/bsxlbixs5w66qnpw7sn4b42yc6livz3d-nix-1.11.2-dev is no longer available.
```

**Comment by domenkozar** [comment]
@l2dy why do you want those links exactly?

**Comment by l2dy** [comment]
So why were those 404 links on that page?

**Comment by domenkozar** [comment]
hydra.nixos.org uses S3 as build store, so you can't access the build products.

See https://github.com/NixOS/hydra/issues/321

**Comment by l2dy** [comment]
Because the nixpkgs-unstable channel hasn't been updated for days and I wanted to try out some trunk builds.

**Comment by domenkozar** [comment]
You can do:

- `nix-store -r /nix/store/zpbd7i57gsqvk0is5l0x9c4wrv1ryhmi-nix-1.11.2` to download it
- `nix-env -i /nix/store/zpbd7i57gsqvk0is5l0x9c4wrv1ryhmi-nix-1.11.2` to install the build
