### ISSUE TITLE
hydra.nixos.org's web service has been slow all day

### ISSUE THREAD

**Issue by obadz** [NixOS/hydra#388]
Loading a page like http://hydra.nixos.org/job/nixos/trunk-combined/tested#tabs-constituents takes ≈ 1 minute

**Comment by edolstra** [comment]
Takes about 2 seconds here.

**Comment by domenkozar** [comment]
Same here

**Comment by copumpkin** [comment]
Are there logs and/or some sort of shared log aggregator service like datadog? Those might help track down issues like this even after they go away.

**Comment by grahamc** [comment]
http://hydra.nixos.org/eval/1291207 has been loading for 2.9 minutes. A second load took about 20 seconds. Attached is the timeline from Chromium's Timeline. 
[TimelineRawData-20160906T194141.json.gz](https://github.com/NixOS/hydra/files/458001/TimelineRawData-20160906T194141.json.gz)

**Comment by obadz** [comment]
I guess I'm not crazy :-)

**Comment by grahamc** [comment]
Here is a HAR for the 2.9 minute one.
[hydra.nixos.org.har.gz](https://github.com/NixOS/hydra/files/458105/hydra.nixos.org.har.gz)

**Comment by grahamc** [comment]
Examination of the HAR shows 2.9min was the time to first byte.
