### ISSUE TITLE
What does the "copumpkin-wip" jobset on hydra.nixos.org do?

### ISSUE THREAD

**Issue by peti** [NixOS/hydra#389]
I noticed http://hydra.nixos.org/jobset/nixpkgs/copumpkin-wip today and wondered what it is and whether it's still needed? Can we maybe disable that jobset for the time being?

Ping @copumpkin.

**Comment by domenkozar** [comment]
@copumpkin asked me a few weeks ago if he can have a jobset for testing bootstrapping changes, so I created it for him.

**Comment by copumpkin** [comment]
Yep, I was just going to use it this week actually 😄  since my previous attempt to update the bootstrap broke the rest of (darwin) nixpkgs (hydra tests) for everyone else.
