### ISSUE TITLE
The documentation is not available

### ISSUE THREAD

**Issue by hce** [NixOS/hydra#399]
The documentation link in the README.md file does not work:

https://hydra.nixos.org/job/hydra/master/tarball/latest/download-by-type/doc/manual#chap-hacking

I was unable to find a working link to the documentation...

**Comment by domenkozar** [comment]
Agreed. Opened https://github.com/NixOS/nixos-homepage/issues/105

Workaround is to:

```
$ nix-store -r /nix/store/h29mjjgiw0jwg62f4xw61k94m73sb05d-hydra-manual-0.1.2311.7221bd7e5a2237c65df44910058a44d315fe3784/
$ chromium /nix/store/h29mjjgiw0jwg62f4xw61k94m73sb05d-hydra-manual-0.1.2311.7221bd7e5a2237c65df44910058a44d315fe3784/share/doc/hydra/index.html 
```

**Comment by edolstra** [comment]
Yeah, I'm working on this.

**Comment by hce** [comment]
Thanks, your workaround worked around the issue just fine for the moment :-)

**Comment by domenkozar** [comment]
Available now at http://nixos.org/hydra/manual/
