### ISSUE TITLE
Add configure option to load all .js files locally

### ISSUE THREAD

**Issue by hce** [NixOS/hydra#402]
Some files are retrieved from google, such as: https://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js

It'd be nice to have a configuration option to load all files locally. This has IMHO four advantages:
- No "leaking" of i.e. company internal URLs to external js cdns
- No instant compromise of the site in case the CDN is compromized
- No dependency on a working internet connection for the site to work
- "More nix style": An externally included js file can change independently of the nix expression that builds hydra.

**Comment by montag451** [comment]
It is really annoying and it keeps me from using Hydra in my company. Before this [commit](https://github.com/NixOS/hydra/commit/17d30cd1790d2c1b46c833056387186253cac441#diff-fd8714942efd414f4af6e5a69fcb63ce), jquery was distributed with Hydra and I don't understand why it was changed.

**Comment by domenkozar** [comment]
If this is preventing you to use hydra, it's really 2min to fix this and make a PR.

**Comment by jpierre03** [comment]
Same issue. Hydra on a laptop without full-time internet connexion.

@domenkozar the "2min PR" is here.
If something is wrong, please tell us. Otherwise, can this PR be merged ?

cc @montag451

**Comment by domenkozar** [comment]
@jpierre03 did you test the PR?
