### ISSUE TITLE
Improve accessibility of Hydra

### ISSUE THREAD

**Issue by grahamc** [NixOS/hydra#406]
With the current iconset of Hydra, I have a very difficult time deciphering the build statuses. It is difficult for me to discern:
-  ? and the check-mark icons (similar color, small interior symbol inside the circle)
- The different "X" and "!" icons
- sometimes, even the check (pass) and X (failed) -- see the second two types of color blindness.

Here is an example of how users with different types of color-blindness perceive Hydra build icons: 

![color-blind](https://cloud.githubusercontent.com/assets/76716/19626654/6a961b5e-9904-11e6-9e0f-78f961b2d7b9.png)

Note that when viewing a build matrix, the icons are _much_ smaller.

I'd propose changing the icons to:
1. Not have a colored circle around the symbol
2. Use a larger symbol

Perhaps also using different symbols for different build failures.

Here is such an example of proposal items 1 and 2:
![proposed](https://cloud.githubusercontent.com/assets/76716/19626707/47cd64be-9905-11e6-8c61-fda5c9c58eac.png)

Note that in this proposed version, there is also screen-reader specific indicators of build status, and on-hover tool-tips.

Before I put forth the effort to get it in to hydra proper, I'd like to know that the change would be accepted in the first place. May I have some feedback regarding that? If this change is unwanted, I would rather spend the effort implementing this change as a greasemonkey script.

Thank you!
Graham

**Comment by groxxda** [comment]
Yes please. I don't think there are valid reasons against cosmetic changes that improve accessibility.


Here is a list of the states that are currently distinguished (at least in alt) and a selection of icons that could be used in my opinion (to support the discussion).

Queued | Succeeded | Cancelled | Failed | Failed with output | Other failure | Dependency failed | Aborted | Timed out | Log limit exceeded | Output size limit exceeded
--- | --- | --- | --- | --- | --- | --- | --- | --- | --- | ---
![Queued](https://github.com/NixOS/hydra/raw/fb5e7f95707e58207c7ed696d462247f5e37c9c9/src/root/static/images/help_256.png) | ![Succeeded](https://github.com/NixOS/hydra/raw/fb5e7f95707e58207c7ed696d462247f5e37c9c9/src/root/static/images/checkmark_256.png) | ![Cancelled](https://github.com/NixOS/hydra/raw/fb5e7f95707e58207c7ed696d462247f5e37c9c9/src/root/static/images/forbidden_256.png) | ![Failed](https://github.com/NixOS/hydra/raw/fb5e7f95707e58207c7ed696d462247f5e37c9c9/src/root/static/images/error_256.png) | ![Failed with output](https://github.com/NixOS/hydra/raw/fb5e7f95707e58207c7ed696d462247f5e37c9c9/src/root/static/images/error_256.png) | ![Other failure](https://github.com/NixOS/hydra/raw/fb5e7f95707e58207c7ed696d462247f5e37c9c9/src/root/static/images/error_256.png) | ![Dependency failed](https://raw.githubusercontent.com/NixOS/hydra/fb5e7f95707e58207c7ed696d462247f5e37c9c9/src/root/static/images/dependency_256.png) | ![Aborted](https://github.com/NixOS/hydra/raw/fb5e7f95707e58207c7ed696d462247f5e37c9c9/src/root/static/images/warning_256.png) | ![Timed out](https://github.com/NixOS/hydra/raw/fb5e7f95707e58207c7ed696d462247f5e37c9c9/src/root/static/images/warning_256.png) | ![Log limit exceeded](https://github.com/NixOS/hydra/raw/fb5e7f95707e58207c7ed696d462247f5e37c9c9/src/root/static/images/warning_256.png) | ![Output size limit exceeded](https://github.com/NixOS/hydra/raw/fb5e7f95707e58207c7ed696d462247f5e37c9c9/src/root/static/images/warning_256.png)
![zzz](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f4a4.png) | ![white check mark](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/2705.png) | ![octogonal sign](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f6d1.png) | ![negative squared cross mark](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/274e.png) | --- | --- | ![no entry sign](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f6ab.png) | ![stop button](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/23f9.png) | ![stopwatch](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/23f1.png) | ![warning](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/26a0.png) | ---
![grey question](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/2754.png) | ![heavy check mark](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/2714.png) | ![heavy minus sign](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/2796.png) | ![x](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/274c.png) | --- | --- | ![heavy multiplication x](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/2716.png) | ![grey exclamation](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/2755.png) | --- | --- | ---

I think using different base shapes (circle, square, ...) already helps distinguishing the icons.

Btw: Does cancelled mean that it should be built as part of this evaluation and aborted means it was cancelled during a previous evaluation?

**Comment by grahamc** [comment]
I like:

1. "ZZZ"s for queued
2. The black checkmark, but wish it were green. I just used a utf-8 character in my screenshot. This is because of the symbol inside the color block is difficult to see as-is.
3. The "stop" sign for cancelled
4. The red "X" (same as #2)
5. The other failures can be the same "X" I think.
6. I like the gray "X" I think for dependency failed
7. The gray "!" but maybe make it orange.

Just my $0.02 :) I'm happy to submit patches if I can get confirmation it'd be taken.

**Comment by grahamc** [comment]
@groxxda I rotated your table so it is long instead of wide. Would you like to replace yours with this? I didn't realize it was wide:

```

| Represents                 | Current                                                                                                                              | Option 1                                                                          | Option 2                                                                         |
|----------------------------|--------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------|----------------------------------------------------------------------------------|
| Queued                     | ![](https://github.com/NixOS/hydra/raw/fb5e7f95707e58207c7ed696d462247f5e37c9c9/src/root/static/images/help_32.png)                  | ![](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f4a4.png) | ![](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/2754.png) |
| Suceeded                   | ![](https://github.com/NixOS/hydra/raw/fb5e7f95707e58207c7ed696d462247f5e37c9c9/src/root/static/images/checkmark_32.png)             | ![](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/2705.png)  | ![](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/2714.png) |
| Cancelled                  | ![](https://github.com/NixOS/hydra/raw/fb5e7f95707e58207c7ed696d462247f5e37c9c9/src/root/static/images/forbidden_32.png)             | ![](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f6d1.png) | ![](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/2796.png) |
| Failed                     | ![](https://github.com/NixOS/hydra/raw/fb5e7f95707e58207c7ed696d462247f5e37c9c9/src/root/static/images/error_32.png)                 | ![](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/274e.png)  | ![](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/274c.png) |
| Failed with Output         | ![](https://github.com/NixOS/hydra/raw/fb5e7f95707e58207c7ed696d462247f5e37c9c9/src/root/static/images/error_32.png)                 |                                                                                   |                                                                                  |
| Other Failure              | ![](https://github.com/NixOS/hydra/raw/fb5e7f95707e58207c7ed696d462247f5e37c9c9/src/root/static/images/error_32.png)                 |                                                                                   |                                                                                  |
| Dependency Failed          | ![](https://raw.githubusercontent.com/NixOS/hydra/fb5e7f95707e58207c7ed696d462247f5e37c9c9/src/root/static/images/dependency_32.png) | ![](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f6ab.png) | ![](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/2716.png) |
| Aborted                    | ![](https://github.com/NixOS/hydra/raw/fb5e7f95707e58207c7ed696d462247f5e37c9c9/src/root/static/images/warning_32.png)               | ![](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/23f9.png)  | ![](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/2755.png) |
| Timed Out                  | ![](https://github.com/NixOS/hydra/raw/fb5e7f95707e58207c7ed696d462247f5e37c9c9/src/root/static/images/warning_32.png)               | ![](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/23f1.png)  |                                                                                  |
| Log Limit Exceeded         | ![](https://github.com/NixOS/hydra/raw/fb5e7f95707e58207c7ed696d462247f5e37c9c9/src/root/static/images/warning_32.png)               | ![](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/26a0.png)  |                                                                                  |
| Output Size Limit Exceeded | ![](https://github.com/NixOS/hydra/raw/fb5e7f95707e58207c7ed696d462247f5e37c9c9/src/root/static/images/warning_32.png)               |                                                                                   |                                                                                  |

```

**Comment by grahamc** [comment]
What if we just used these:
| Represents                 | Proposal                                                                                     |
|----------------------------|----------------------------------------------------------------------------------------------|
| Queued                     | ![](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f4a4.png)            |
| Suceeded                   | ![](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/2714.png) (but green) |
| Cancelled                  | ![](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f6d1.png)            |
| Failed                     | ![](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/274c.png)             |
| Failed with Output         | ![](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/274c.png)             |
| Other Failure              | ![](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/274c.png)             |
| Dependency Failed          | ![](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/2716.png)             |
| Aborted                    | ![](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/1f6d1.png)            |
| Timed Out                  | ![](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/274c.png)             |
| Log Limit Exceeded         | ![](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/274c.png)             |
| Output Size Limit Exceeded | ![](https://raw.githubusercontent.com/Ranks/emojione/master/assets/png/274c.png)             |

I think it cuts down the various options, without substantially reducing the ability to scan and understand what's going on.

**Comment by domenkozar** [comment]
Zzz doesn't quite represent `in queue`, I'd rather stick with question mark.

**Comment by grahamc** [comment]
PR opened: https://github.com/NixOS/hydra/issues/407

**Comment by edolstra** [comment]
How about using Unicode characters? (E.g. ✓, ✗, ⌛, ...).

**Comment by grahamc** [comment]
I looked in to that, and definitely could. An accessible version using Unicode would look something like this:

```
<span title="succeeded" aria-label="succeeded"><span aria-hidden="true">✓</span></span>
```
