### ISSUE TITLE
Declarative project not being scheduled

### ISSUE THREAD

**Issue by basvandijk** [NixOS/hydra#411]
@shlevy I'm trying out declarative projects. When I create a declarative project based on your example in: https://github.com/NixOS/hydra/pull/277 I see that a `.jobsets` jobset is created. That jobset contains a single job `jobsets`. However that job stays in thje "Scheduled to be built" state. When I cancel it and restart it I see the following in my journal:

```
Oct 25 23:36:50 hera nix-daemon[1435]: accepted connection from pid 5772, user hydra-www
Oct 25 23:36:50 hera hydra-queue-runner[5007]: got notification: builds restarted
Oct 25 23:36:50 hera hydra-queue-runner[5007]: checking the queue for builds > 0...
Oct 25 23:36:50 hera hydra-queue-runner[5007]: loading build 2 (declarative-hydra-example:.jobsets:jobsets)
Oct 25 23:36:58 hera hydra-evaluator[5012]: starting evaluation of jobset ‘declarative-hydra-example:.jobsets’
Oct 25 23:36:58 hera hydra-evaluator[5012]: considering jobset declarative-hydra-example:.jobsets (last checked 0s ago)
Oct 25 23:36:59 hera nix-daemon[1435]: accepted connection from pid 8939, user hydra
Oct 25 23:37:00 hera hydra-evaluator[5012]:   jobset is unchanged, skipping
Oct 25 23:37:00 hera hydra-evaluator[5012]: evaluation of jobset ‘declarative-hydra-example:.jobsets’ finished with status 0
```

Note that I'm using the [latest](https://github.com/NixOS/hydra/commit/a12e9478e76400881e9c0d12c5dd6e4a218652ee) hydra.

**Comment by shlevy** [comment]
@edolstra any idea here? This was working back when I added this...

**Comment by basvandijk** [comment]
I'm pretty sure this was caused by the same problem as described in #413.
