### ISSUE TITLE
Erroneous behaviour when creating jobset

### ISSUE THREAD

**Issue by basvandijk** [NixOS/hydra#412]
I'm trying to create a jobset containing the following two inputs:
- `lumi` `git@github.com:LumiGuide/lumi.git feat-nixos-16.09`
- `nixpkgs` `git@github.com:NixOS/nixpkgs-channels.git nixos-16.09-small`

When I click "Apply changes" I see the following JSON being sent by my browser:

``` json
{
   "description" : "",
   "input--name" : "lumi",
   "input--value" : "git@github.com:LumiGuide/lumi.git feat-nixos-16.09",
   "visible" : "on",
   "nixexprpath" : "release.nix",
   "keepnr" : "3",
   "nixexprinput" : "lumi",
   "input--type" : "git",
   "schedulingshares" : "1",
   "name" : "feat-nixos-16.09",
   "inputs" : {
      "nixpkgs" : {
         "value" : "git@github.com:NixOS/nixpkgs-channels.git nixos-16.09-small",
         "type" : "git"
      }
   },
   "checkinterval" : "60",
   "emailoverride" : "engineering@lumiguide.nl",
   "enabled" : "1"
}
```

The `input--name`, `input--value` and `input--type` fields seem incorrect. Shouldn't the `lumi` input be listed in the `inputs` field?

Also when the resulting jobset is evaluated I get the following error message:

> cannot find the input containing the job expression

Which is to be expected if you look at the configuration of the jobset which shows not a single input.

Note I'm using the [latest](https://github.com/NixOS/hydra/commit/a12e9478e76400881e9c0d12c5dd6e4a218652ee) hydra.

**Comment by basvandijk** [comment]
I think the error is in [/src/root/edit-jobset.tt#L50](https://github.com/NixOS/hydra/blob/master/src/root/edit-jobset.tt#L50). Apparently when creating a jobset `inputs` is not empty causing the `FOREACH` loop to iterate once and call `renderJobsetInput`. However `input.name` is empty causing the template:

```
<input type="text" id="[% baseName %]-name" name="[% baseName %]-name"
``` 

to render to:

```
<input type="text" id="input--name" name="input--name"
```

This then causes trouble in the [submit-jobset callback](https://github.com/NixOS/hydra/blob/master/src/root/edit-jobset.tt#L188) because the regexp won't match `"input--name"`.

@edolstra the question is: why is `jobset.jobsetinputs` initially non-empty?

**Comment by basvandijk** [comment]
I discovered a workaround: if you remove the first input row (the one with the wrong `input--...` names) and add it again it will have the correct `input-template-...` names and the jobset JSON will be correct.

**Comment by domenkozar** [comment]
@basvandijk can you try reverting https://github.com/NixOS/hydra/commit/c103163825340e7e8af2ecbc50489384a2346a01 ? It was the only recent addition in this part of the codebase.

**Comment by basvandijk** [comment]
@domenkozar reverting https://github.com/NixOS/hydra/commit/c103163825340e7e8af2ecbc50489384a2346a01 fixes the problem. 

Apparently `inputs.sort('name')` results in an single element array even when `inputs` is empty!

**Comment by domenkozar** [comment]
@edolstra huh, thoughts?

**Comment by basvandijk** [comment]
Thanks!
