### ISSUE TITLE
builds do not run when http://hydra.nixos.org unavailable

### ISSUE THREAD

**Issue by axb21** [NixOS/hydra#417]
As of this moment, [http://hydra.nixos.org](http://hydra.nixos.org) does not respond to network requests where I am. A bunch of builds are clogged in my local hydra queue, and hydra-queue-runner has been logging messages like this:

```
Oct 30 12:24:29 mymachine hydra-queue-runner[16990]: download-from-binary-cache.pl: could not download ‘http://hydra.nixos.org/dbyvcdjv0mpqv8c1rs6hk997cml5g75j.narinfo’ (Curl error 7)
Oct 30 12:24:36 mymachine hydra-queue-runner[16990]: download-from-binary-cache.pl: still waiting for ‘http://hydra.nixos.org/m5qv7yabkjxxs1bz06mkv5jxdsqn4bbp.narinfo’ after 5 seconds...
```

My builds rely only on my own code and nixpkgs, the latter of which I mirror locally. I'm currently running `hydra-2016-04-15` locally, which is the newest version of hydra available through nix. I am having trouble building hydra from source--configure fails with an error I don't understand yet--so I have not been able to try a newer version.

Why does hydra hang completely like this? Is there a way to get some better error reporting so I know what is going wrong? Are there other places hydra might try fetching whatever it is trying to fetch so that there is not a single point of failure?

**Comment by domenkozar** [comment]
@edolstra can we pass `--fallback` to the queue-runner?

**Comment by edolstra** [comment]
Hm, why is your Hydra instance using `hydra.nixos.org` at all? Note that it no longer provides a binary cache (it uploads build results to cache.nixos.org directly) so it's not useful to use it anyway.

**Comment by axb21** [comment]
I don't know. I'll have to poke around. I wasn't sure if that was normal 
behavior or not but it sounds like it's not?

I installed hydra with `nix-env -i hydra` and keep it up to date with nix 
as well. I've only done minimal configuration on it to e. g. set up some 
remote machines. Any suggestions for where I might look to figure out why 
it's using nixos.org? Thanks.

**Comment by domenkozar** [comment]
Can you paste `/etc/nix/nix.conf`?

**Comment by axb21** [comment]
@domenkozar I do not have a file there on my system. I have installed nix under my username only, not globally. I do not have a file named `nix.conf` in any of the `.nix*` folders in my home directory. Should I have such a file? Could that be part of the problem?

**Comment by domenkozar** [comment]
@axb21 you'll have to describe your Hydra+Nix setup for us to be able to understand what's going on here.

**Comment by axb21** [comment]
@domenkozar do you require more information that I've already provided? I use Ubuntu 16.04, installed nix under my own user account only using the curl method to pull down the bootstrap shell file, installed hydra with `nix-env --install` and have used `nix-channel --update` and `nix-env --upgrade` to keep everything up-to-date. The `hydra-server` web page reports `Hydra 2016-04-15 (using nix-1.12pre4523_3b81b26)`. If there's any other information that would be helpful please let me know, thanks!
