### ISSUE TITLE
setting journal mode: attempt to write a readonly database in Build.pm

### ISSUE THREAD

**Issue by karltk** [NixOS/hydra#42]
I am trying to run hydra on a nix installation with chroot enabled.

I run the nix-worker in daemon mode, as root.

I run hydra-queue-runner, hydra-evaluator as hydra. 

When I inspect the build queue in the web UI, I notice that the first job in the queue fails with:

Caught exception in Hydra::Controller::Build->view_build "setting journal mode: attempt to write a readonly database at /nix/store/z59x87dkg5llg15qg023ky9flp8mv3i8-hydra-0.1pre1086-396a356/libexec/hydra/lib/Hydra/Controller/Build.pm line 44."

When I strace, I see that the nix-worker opens /nix/var/nix/db/db.sqlite just fine

[pid 24079] open("/nix/var/nix/db/db.sqlite", O_RDWR) = 6

The hydra-queue-runner never attempts to open this file. 

The file is owned by root, with world having read access.

**Comment by gilligan** [comment]
Since the issue was reported 8 years ago and there is no way to reproduce it and no responses back then i'll close this.
