### ISSUE TITLE
hydra.nixos.org disk space issues

### ISSUE THREAD

**Issue by edolstra** [NixOS/hydra#421]
Hydra.nixos.org is running out of disk space frequently. Here are the biggest directories:
```
 44 GiB /nix/store
105 GiB /var/lib/hydra/build-logs
 13 GiB /var/lib/hydra/queue-runner/.cache/nix
 20 GiB /var/lib/hydra/scm/
178 GiB /var/db/postgresql
 39 GiB /var/cache/hydra-binary-cache
```
`/var/cache/hydra-binary-cache` is unnecessary since we no longer generate a binary cache on the fly, so I've removed it.

Not much we can do about PostgreSQL.

Build logs should be stored in the binary cache in S3.

When hydra-queue-runner crashes, it can generate a huge core dump. We could disable core dumps, but they're very useful in diagnosing the issue.

**Comment by domenkozar** [comment]
@edolstra afaik this is now resolved (logs are in S3)?

**Comment by edolstra** [comment]
Yeah, let's close.
