### ISSUE TITLE
Config parser in hydra-queue-runner ignores options

### ISSUE THREAD

**Issue by griff** [NixOS/hydra#425]
The config parser in hydra-queue-runner only parses options that use = while the perl module ```Config::General``` also supports having only a whitespace between the option and the value.

This leads to some very subtle issues since hydra-queue-runner only supports the two options ```store_uri``` and ```use-substitutes``` and the config in hydra-module.nix only uses the format without = so the ```use-substitutes``` option there looks right but isn't because

```
use-substitutes ${if cfg.useSubstitutes then "1" else "0"}
```

must be

```
use-substitutes = ${if cfg.useSubstitutes then "1" else "0"}
```

for hydra-queue-runner to correctly parse the option

**Comment by domenkozar** [comment]
cc @edolstra

**Comment by dtzWill** [comment]
This is still an issue FWIW.

**Comment by dtzWill** [comment]
(And easily fixed as mentioned in the original bug report, for example: https://github.com/dtzWill/hydra/commit/5d16159d24a65098d75cb671f229255c8c001e32 (ignore the other commits :P))

**Comment by dtzWill** [comment]
Thanks! :+1:
