### ISSUE TITLE
Getting 404s or 410s for everything on Hydra

### ISSUE THREAD

**Issue by vimuel** [NixOS/hydra#437]
For any of the packages I select on Hydra, I get

> Build X is no longer available.

or

> Path /nix/store/xyz is no longer available.

I'm just clicking on the package name on the latest channel or on the build one-install link, respectively.

What am I doing wrong?

**Comment by edolstra** [comment]
Yeah, downloading packages from hydra.nixos.org is no longer supported. We should really remove those links from the web interface.

**Comment by vimuel** [comment]
The manual probably needs to be updated then. Is the manual on GitHub?
