### ISSUE TITLE
Declarative projects are broken

### ISSUE THREAD

**Issue by globin** [NixOS/hydra#443]
Nothing happens after "building" the `.jobsets` jobset.

Calling `hydra-notify` by hand doesn't change anything either.

See https://hydra.mayflower.de/project/mayflower, configuration at:
https://github.com/mayflower/hydra-jobs/blob/master/spec.json
and https://github.com/mayflower/hydra-jobs/blob/master/jobsets.nix

ping @shlevy 

(cc @fpletz, @fadenb)

**Comment by shlevy** [comment]
Any idea when they last worked?

**Comment by shlevy** [comment]
Ah, this error seems interesting :grin: 

>read_file '/nix/store/6pb9m6n8wgrl8a75qh99mxryazkm5kzd-spec.json' - sysopen: No such file or directory at /nix/store/7gsnylj1jjbrk0jmzfvdifpmgsrzzcs4-hydra-2016-12-09/libexec/hydra/lib/Hydra/Helper/AddBuilds.pm line 514.

**Comment by shlevy** [comment]
Ah, are you using an s3 store or some such? @edolstra is there a way from perl to read a file via fsaccessor methods?

**Comment by globin** [comment]
@shlevy nope:
```
      extraConfig = ''
        store_uri = file:///var/lib/hydra/cache?secret-key=/etc/binary-cache.secret
        binary_cache_secret_key_file = /etc/binary-cache.secret
        binary_cache_dir = /var/lib/hydra/cache
```

**Comment by shlevy** [comment]
Hmm, so does that store path exist on the machine where the queue runner is running?

**Comment by globin** [comment]
```
[root@hydra:~]# ls '/nix/store/6pb9m6n8wgrl8a75qh99mxryazkm5kzd-spec.json'
ls: cannot access '/nix/store/6pb9m6n8wgrl8a75qh99mxryazkm5kzd-spec.json': No such file or directory
```

Related to #321 then probably?

**Comment by jpierre03** [comment]
Maybe related to #445

**Comment by globin** [comment]
Nope, we have that commit reverted :)

**Comment by basvandijk** [comment]
May be related to: https://github.com/NixOS/hydra/issues/411.

**Comment by globin** [comment]
Nope, other jobs are built on our build slaves :)

**Comment by shlevy** [comment]
@edolstra Is there a way we can plausibly expose fsaccessor stuff to perl?

**Comment by edolstra** [comment]
@shlevy What for?

**Comment by shlevy** [comment]
The evaluator needs access to the output of the declartaive job build.

**Comment by edolstra** [comment]
To be honest, it would be better to rewrite the evaluator in C++. Much of it (the top-level hydra-evaluator, and hydra-eval-jobs) is already in C++, only hydra-eval-jobset remains. This would also simplify a bit - hydra-eval-jobs and hydra-eval-jobset could be merged, so no more need to pass JSON around between them.

Otherwise, you might be able to use `nix cat-store` and `nix ls-store` as an interface to the fsaccessor API.

**Comment by shlevy** [comment]
OK, thanks.

**Comment by domenkozar** [comment]
Thanks @shlevy
