### ISSUE TITLE
Jobset inputs not persisted

### ISSUE THREAD

**Issue by sjmackenzie** [NixOS/hydra#445]
# steps to reproduce:
- create a jobset, navigate to the configuration page.
- fill out details
- fill out the inputs section at the bottom 
- click `apply changes`

# expected behaviour
- the input is persisted 

# actual behaviour
- upon navigating back to the jobset configuration page the input is not present
- this message `cannot find the input containing the job expression` appears in the `evaluation errors` tab.

**Comment by sjmackenzie** [comment]
This commit introduces the error: https://github.com/NixOS/hydra/commit/c103163825340e7e8af2ecbc50489384a2346a01 @domenkozar

**Comment by sjmackenzie** [comment]
still getting the `cannot find the input containing the job expression` error though.

**Comment by jpierre03** [comment]
+1

**Comment by basvandijk** [comment]
May also be related to: https://github.com/NixOS/hydra/issues/412

**Comment by domenkozar** [comment]
Sadly I do not know enough Perl to fix this.

**Comment by sjmackenzie** [comment]
All I did was remove your modifications and it worked.

**Comment by basvandijk** [comment]
Shall we just revert https://github.com/NixOS/hydra/commit/c103163825340e7e8af2ecbc50489384a2346a01 since it fixes both this issue and https://github.com/NixOS/hydra/issues/412?

**Comment by domenkozar** [comment]
Sure

**Comment by domenkozar** [comment]
Make a PR and I'll push buttons :)

**Comment by sjmackenzie** [comment]
You should be able to click the revert button.

**Comment by sjmackenzie** [comment]
Ah wait, you probably committed the code directly and not via a PR.

**Comment by edolstra** [comment]
Closed by 63d8c8d631299b19a066d0f8b464a4dd4322f6f8.
