### ISSUE TITLE
I can download nothing from the site hydra.nixos.org

### ISSUE THREAD

**Issue by antmak** [NixOS/hydra#447]
For example I'd like to download src.rpm from https://hydra.nixos.org/build/45209679
But I see "File /nix/store/9930gs80awdvpwh2cq4ph303fxisg4sh-nix-rpm-fedora-21-x86_64-1.12pre4933_3a4bd32/rpms/fedora-21-x86_64/nix-1.12pre4933_3a4bd32-2.fc21.src.rpm has disappeared."

Every links on tar, deb, rpm are broken. 404

**Comment by domenkozar** [comment]
https://github.com/NixOS/hydra/issues/321
