### ISSUE TITLE
Build slaves don't seem to pull from cache.nixos.org

### ISSUE THREAD

**Issue by shlevy** [NixOS/hydra#452]
`cache.nixos.org` is in my build slaves' `binary-caches` but everything keeps getting rebuilt from scratch on each stdenv merge even when binaries are available.

**Comment by shlevy** [comment]
@edolstra

**Comment by domenkozar** [comment]
https://github.com/snabblab/snabblab-nixos/blob/master/modules/hydra-master.nix#L72

**Comment by shlevy** [comment]
We already have that set...

**Comment by edolstra** [comment]
What Hydra version?

**Comment by shlevy** [comment]
Ah ha, I'll try latest `master`
