### ISSUE TITLE
Output limit exceeded

### ISSUE THREAD

**Issue by jokogr** [NixOS/hydra#467]
Hello,

I have just set up a Hydra server on current NixOS (17.03) and set `max_output_size` to `4294967296` (as in 4GB) in hydra.conf.

Nevertheless I still get `Output limit exceeded`, e.g. for packages like `/nix/store/kb38s09cwc1ayd6b0vab7sy5vls8msxh-idea-ultimate-2017.1` and `/nix/store/08c3yivdc5y9iqv7sqz0kd48icr1sn1f-ghc-7.10.3`.

I am checking the build machines and those derivations are 1.3GB and 886MB respectively, any idea what's the actual problem?

**Comment by edolstra** [comment]
What version are you on? This may be fixed by 73900e9f5fe18153a8d7a5eeaaedb6721653b53b.

**Comment by jokogr** [comment]
I am on Hydra 2017-03-21 or 57bc0eaead8c76ffd71ddc49adfacc47bb8a75ac, so I suppose this commit is already integrated.

@edolstra Does it make sense trying a newer version?

**Comment by jokogr** [comment]
As a workaround I am manually copying closures from the build machines to the Hydra server.

In case anyone wants to replicate the issue, let me give you more info:

* I am running the same versions on a Hydra server and three build machines:

```
# nixos-version
17.03.1024.2af7c40ed9 (Gorilla)
# nix-env --version
nix-env (Nix) 1.11.8
# nix-instantiate --eval '<nixpkgs>' -A lib.nixpkgsVersion
"17.03.1024.2af7c40ed9"
```

* Hydra web pages report the following:

```
Hydra 2017-03-21 (using nix-1.12pre5152_915f62fa).
```

* Hydra server has the following Hydra-related configuration (I have omitted IPs etc.):

```
  nix.extraOptions = "auto-optimise-store = true";
  services.hydra = {
    useSubstitutes = true;
    extraConfig = ''
      store-uri = file:///nix/store?secret-key=/etc/nixos/private/my-hydra-1/secret
      max_output_size = 4294967296
    '';
  };
```

* The build machines have the following nix-related configuration (again, I am omitting keys etc.):

```
  nix.useSandbox = true;
  nix.buildCores = 0;
  nix.gc = {
    automatic = true;
    dates = "05:15";
    # Try to ensure that system has 10 GB of free space
    options = ''--max-freed "$((10 * 1024**3 - 1024 * $(df -P -k /nix/store | tail -n 1 | ${pkgs.gawk}/bin/awk '{ print $4 }')))"'';
  };
  systemd.timers.nix-gc.timerConfig.RandomizedDelaySec = "1800";
```

**Comment by jokogr** [comment]
Some extra stuff that are reported:

```
hydra-server[760]: Argument "" isn't numeric in numeric gt (>) at /nix/store/aq7j5jsim11h943mwmj83717apr9kjng-hydra-2017-03-21/libexec/hydra/root/build.tt line 64.
```

My Perl-fu is not that great, but I suppose this has to do with `step.timesbuilt` being set to "" instead of 0.

**Comment by luke-clifton** [comment]
4294967296 will overflow a 32 bit value. Try a smaller number?

**Comment by jokogr** [comment]
I did so, but still no luck.

After all, one of the failing closures is 1.3 GB, so it's already beyond the default value of that variable (presumably 2GB).

**Comment by jokogr** [comment]
Anything else I could try? If I try to restart, then queue runner reports something like the following:

```
Apr 30 16:18:27 prometheus hydra-queue-runner[767]: loading build 8 (joko-nixos:master:machines.munch.system)
Apr 30 16:18:32 prometheus hydra-queue-runner[767]: performing step ‘/nix/store/i3pjn5q0cfhgfmparfqywd39cmj7i8zc-ghc-8.0.2.drv’ 1 times on ‘builder@xxx’ (needed by build 8 and 0 others)
Apr 30 16:18:33 prometheus hydra-queue-runner[767]: outputs of ‘/nix/store/i3pjn5q0cfhgfmparfqywd39cmj7i8zc-ghc-8.0.2.drv’ substituted or already valid on ‘builder@xxx’
Apr 30 16:18:33 prometheus hydra-queue-runner[767]: will disable machine ‘builder@xxx’ for 84s
Apr 30 16:18:33 prometheus hydra-queue-runner[767]: marking build 8 as failed
Apr 30 16:18:36 prometheus hydra-queue-runner[767]: Died at /nix/store/gkyn1m470f55inqyjnya5cv686459bc5-hydra-2017-03-21/bin/.hydra-notify-wrapped line 58.
Apr 30 16:18:36 prometheus hydra-queue-runner[767]: notification sender: hydra-build returned exit code 65280 notifying about build 8
```

**Comment by domenkozar** [comment]
I have bumped Hydra on 17.03 (to HEAD), try latest commit and report back.

**Comment by jokogr** [comment]
The official 17.03 channel is still at NixOS/nixpkgs-channel@4aab5c5798 (one commit before what @domenkozar mentions), but using this and NixOS/hydra@1f94f036 fixed this issue.

Thanks, @domenkozar! I'll close this issue once the channel gets updated to NixOS/nixpkgs@1f94f036 and verify it works.

**Comment by jokogr** [comment]
I am afraid this issue was not actually resolved, it seems I had copied the closure earlier and this is why it was not complaining.

Anyway, I've tried to debug it a bit on my own and I think this is the error: `requesting more tokens (2646014992) than exist (2059864064)`.

**Comment by jokogr** [comment]
So it appears that the issue was memory-related, this Hydra didn't not have enough memory to compress big closures. Once I set up another Hydra instance with more RAM (16 vs 4 GB), the same configuration worked as intended.
