### ISSUE TITLE
build slave wendy: No space left on device

### ISSUE THREAD

**Issue by tohl** [NixOS/hydra#473]
http://hydra.nixos.org/build/51570620

Build 51570620 of job nixpkgs:cross-trunk:bootstrapTools.aarch64.build 

++ mkdir -p /nix/store/h03qg3bqvpslhcv0n75vzc0wcyhc4cvq-stdenv-bootstrap-tools-cross/bin /nix/store/h03qg3bqvpslhcv0n75vzc0wcyhc4cvq-stdenv-bootstrap-tools-cross/lib /nix/store/h03qg3bqvpslhcv0n75vzc0wcyhc4cvq-stdenv-bootstrap-tools-cross/libexec
mkdir: cannot create directory '/nix/store/h03qg3bqvpslhcv0n75vzc0wcyhc4cvq-stdenv-bootstrap-tools-cross': No space left on device
mkdir: cannot create directory '/nix/store/h03qg3bqvpslhcv0n75vzc0wcyhc4cvq-stdenv-bootstrap-tools-cross': No space left on device
mkdir: cannot create directory '/nix/store/h03qg3bqvpslhcv0n75vzc0wcyhc4cvq-stdenv-bootstrap-tools-cross': No space left on device
+ exitHandler
+ exitCode=1
+ set +e
+ closeNest
+ '[' 0 -gt 0 ']'
+ '[' -n '' ']'
+ '[' 1 '!=' 0 ']'
+ runHook failureHook
+ local hookName=failureHook
+ shift
+ local var=failureHook
+ [[ failureHook =~ Hook$ ]]
+ var+=s
+ eval 'local -a dummy=("${failureHooks[@]}")'
++ dummy=("${failureHooks[@]}")
++ local -a dummy
+ for hook in "_callImplicitHook 0 $hookName" "${dummy[@]}"
+ _eval '_callImplicitHook 0 failureHook'
+ local 'code=_callImplicitHook 0 failureHook'
+ shift
++ type -t _callImplicitHook 0 failureHook
+ '[' function = function ']'
+ eval '_callImplicitHook 0 failureHook "$@"'
++ _callImplicitHook 0 failureHook
++ local def=0
++ local hookName=failureHook
++ case "$(type -t $hookName)" in
+++ type -t failureHook
++ '[' -z '' ']'
++ return 0
+ return 0
+ '[' -n '' ']'
+ exit 1
builder for ‘/nix/store/ba5j99w230drzypfs2ars118p0g2k16a-stdenv-bootstrap-tools-cross.drv’ failed with exit code 1
note: build failure may have been caused by lack of free disk space

**Comment by domenkozar** [comment]
cc @rbvermaa @edolstra

**Comment by spinus** [comment]
is this still relevant?

**Comment by dtzWill** [comment]
Hopefully this has since been resolved one way or the other?
