### ISSUE TITLE
nixos-unstable seems to be stuck

### ISSUE THREAD

**Issue by primeos** [NixOS/hydra#476]
#### Possible source of the error:

https://hydra.nixos.org/jobset/nixos/trunk-combined#tabs-errors:
> hydra-eval-jobs returned signal 6:
> Too many heap sections: Increase MAXHINCR or MAX_HEAP_SECTS

**Comment by primeos** [comment]
The error is gone and nixos-unstable is updating again :smile: .

**Comment by primeos** [comment]
> Errors occurred at 2017-04-29 17:38:36.
> > hydra-eval-jobs returned signal 6:
> > trace: warning: bond0.mode is deprecated, use bond0.driverOptions
> > trace: warning: bond0.mode is deprecated, use bond0.driverOptions
> > trace: warning: bond0.mode is deprecated, use bond0.driverOptions
> > trace: warning: bond0.mode is deprecated, use bond0.driverOptions
> > Too many heap sections: Increase MAXHINCR or MAX_HEAP_SECTS

**Comment by domenkozar** [comment]
Doesn't seem to be the case anymore atm: http://hydra.nixos.org/jobset/nixos/trunk-combined#tabs-errors

**Comment by primeos** [comment]
> Errors occurred at 2017-05-06 13:50:16.
> 
>> hydra-eval-jobs returned exit code 1:
>> error: undefined variable ‘vmchale’ at /nix/store/1yz5a2m86rd72n073d782pwh8cj7qyl9-git-export/pkgs/misc/tw-rs/default.nix:21:39
>> (use ‘--show-trace’ to show detailed location information)

The channel seems to be pretty unstable atm or is this normal for the `nixos-unstable` branch (latest successful evaluation is from 2017-05-03 20:26:37 (i.e. all of the subsequent seven jobs failed))?

**Comment by primeos** [comment]
https://hydra.nixos.org/job/nixos/trunk-combined/tested/all?page=1 - Looking at the `tested` job this seems to be normal. But imho we should try to improve the percentage of successful builds.
