### ISSUE TITLE
hydra-server binary cache gives 500s with no error message in logs

### ISSUE THREAD

**Issue by shlevy** [NixOS/hydra#477]
This is intermittent and really hard to trace as a result.

**Comment by tohl** [comment]
Not sure if this is the right issue but I get the logs from hydra as
binary mess instead of text, e.g.

   https://hydra.nixos.org/build/52111129

It is impossible to see what went wrong during build.

**Comment by shlevy** [comment]
Closing this to clear up my open issues list, please open a new one if interested in pursuing this.
