### ISSUE TITLE
Interactive testing on Hydra build slaves

### ISSUE THREAD

**Issue by lukego** [NixOS/hydra#478]
I have a Hydra cluster with many build slaves that each have interesting "features" (hardware.) I would like to be able to interactively run tests on these machines, in addition to the Hydra tests.

For example I would like to be able to run `nix-build` on my laptop and have it execute the test on one of the build slaves that can satisfy the required features. Ideally an interactive test would be time limited (e.g. `timeout 60 nix-build ...`) and would preempt any automatic build from Hydra (but in such a way that it will be automatically retried later.) The idea is that most of the time machines will be running automatically scheduled tests but occasionally this will be interrupted for an interactive test.

How realistic is this dream? :-)

**Comment by domenkozar** [comment]
Missed this one :) @lukego in what sense do you mean interactive here?

**Comment by lukego** [comment]
By "interactively" I suppose that I mean "synchronously and with low latency."

So I would write `nix-build-on-hydra foo.nix` to submit a job for Hydra to run _now_ and the command would wait while it builds and then finally import the results into my local nix store.

This differs from normal distributed nix via the build hook because Hydra is the one keeping track of what build slaves exist, what are their supported features, how they should prioritize work, etc. also in that the derivations will be built completely with only the final result being imported into my local store.

**Comment by domenkozar** [comment]
Hercules will support that in https://github.com/hercules-ci/hercules/issues/12

For Hydra, someone would need to code together using API:

- create a new one-off jobset
- bump it to the beginning of the queue
- poll on results
- print status report as it goes

**Comment by lukego** [comment]
Thanks for the feedback. Just happy to have this idea floating around :).
