### ISSUE TITLE
Build logs messed up in Safari

### ISSUE THREAD

**Issue by matthewbauer** [NixOS/hydra#480]
The build logs don't display properly when you're in Safari. It's probably an encoding issue. The problem can be avoided by just using Chrome.

<img width="916" alt="screen shot 2017-05-20 at 2 17 39 pm" src="https://cloud.githubusercontent.com/assets/19036/26278728/19af6eea-3d67-11e7-96a1-4d923bab7f05.png">

**Comment by matthewbauer** [comment]
Update on this: it appears that S3 is serving up "brotli" encoded files. Those aren't supported on Safari yet:

http://caniuse.com/#feat=brotli

It is also not supported by CURL which is why you get the same thing when you run:

```
curl https://nix-cache.s3.amazonaws.com/log/ggnfdgd0gg93hs51a1sx9ym8fyay7xwd-nixpkgs-tarball-17.09pre107697.bb37fc90c7.drv
```

Any way to turn this off on S3?

**Comment by veprbl** [comment]
I remember the first time this happened when aarch64 was just out. Now it's everywhere and S3 ignores content negotiation here:
```
nix-shell -p curl --run 'curl -H "Vary: Accept-Encoding" --compress -L -v https://hydra.nixos.org/log/16hcg2gcrrj36r8yc30c9bnxy4c2bzpm-allegro-4.4.2.drv > /dev/null' 2>&1 | grep Encoding
> Accept-Encoding: deflate, gzip
> Vary: Accept-Encoding
> Accept-Encoding: deflate, gzip
> Vary: Accept-Encoding
< Content-Encoding: br
```

**Comment by matthewbauer** [comment]
I think it's a problem with 'log-compression' in the build machines /etc/nix.conf file.

See: https://github.com/NixOS/nix/blob/a1355917ecf75e1f1f37101505a351743d590121/src/libstore/s3-binary-cache-store.cc#L296

/cc @rbvermaa @edolstra

**Comment by edolstra** [comment]
According to http://caniuse.com/#feat=brotli the next version of Safari will support Brotli.

Indeed S3 does not do negotiation, the files are served in their original, compressed form. (CloudFront has some support for negotiation but it doesn't handle brotli.)

**Comment by matthewbauer** [comment]
Ok looks like it's fixed now.
