### ISSUE TITLE
Mysterious "regex_error" when evaluating this build

### ISSUE THREAD

**Issue by Zer0-** [NixOS/hydra#481]
I have set up a trivial repo that hydra chokes on:
https://github.com/Zer0-/hydra-tomltest/blob/master/default.nix

Building this with nix-build works perfectly, but hydra simply says "error: regex_error".
From `journal -xe -u hydra-evaluator`:

```
May 21 18:26:15 dussel hydra-evaluator[22649]: starting evaluation of jobset ‘ruma:tomltest’
May 21 18:20:27 dussel hydra-evaluator[22649]: considering jobset ruma:tomltest (last checked 2s ago)
May 21 18:20:34 dussel hydra-evaluator[22649]: hydra-eval-jobs returned exit code 1:
May 21 18:20:34 dussel hydra-evaluator[22649]: error: regex_error
May 21 18:20:34 dussel hydra-evaluator[22649]: evaluation of jobset ‘ruma:tomltest’ failed with exit code 1
```

the parseTOML.nix file comes from nixpkgs-mozilla from here:
https://github.com/mozilla/nixpkgs-mozilla/blob/master/lib/parseTOML.nix

 which I was going to use for building rust nightly.

**Comment by Chakerbh** [comment]
How did you configured the jobset in hydra? I tried to add it in a local hydra instance and it says: 
`Jobset contains a job with an empty name. Make sure the jobset evaluates to an attrset of jobs.`
which is expected!

**Comment by edolstra** [comment]
https://github.com/NixOS/nix/commit/e46090edb101acac20ab1e6260a0ba98c177206a improves the error message. See also https://github.com/NixOS/nix/issues/1331.

**Comment by rimmington** [comment]
May be related to https://github.com/mozilla/nixpkgs-mozilla/issues/40.
