### ISSUE TITLE
Unable to compile on Darwin

### ISSUE THREAD

**Issue by rgmorris** [NixOS/hydra#483]
Hi,

I'm at my wits end trying to get http://hydra.nixos.org/jobset/gnu/emacs-trunk to build on Darwin, and would really appreciate some help.

If I don't specify a compiler, it uses Clang, and configure fails (eg http://hydra.nixos.org/build/53652004) with "C compiler cannot create executables". The actual error is:
  xcode-select: error: no developer tools were found at '/Applications/Xcode.app', and no install could be requested (perhaps no UI is present), please install manually from 'developer.apple.com'.

If I pass CC=gcc via configureFlags (eg http://hydra.nixos.org/build/53651998) it fails with "gcc: command not found", even if I add pkgs.gcc to the buildInputs.

If I pass CC="${pkgs.gcc}/bin/gcc" (eg http://hydra.nixos.org/build/53651999), it fails with
"/nix/store/bs97qhkb2ls1r554pjxnvl5ahl7ldvx8-clang-wrapper-3.3/bin/gcc: No such file or directory"

Help?

**Comment by domenkozar** [comment]
This repository contains the source code for Hydra, the CI. If you are having problems with packaging, open an issue at https://github.com/NixOS/nixpkgs repo

**Comment by rgmorris** [comment]
I'm having problems constructing a config file for CI testing on hydra. This doesn't seem like a Nix packaging issue to me.  AFAICS every Darwin build on http://hydra.nixos.org/project/gnu has been failing for months. They used to work at some point. Is there a working C compiler available for hydra Darwin builds, and if so, how do I specify it?

**Comment by LnL7** [comment]
The hydra machines don't have xcode, the build shouldn't be trying to use it.
We an expression for [emacs in nixpkgs](https://github.com/NixOS/nixpkgs/blob/master/pkgs/applications/editors/emacs/default.nix) and that builds fine on [hydra](http://hydra.nixos.org/job/nixpkgs/trunk/emacs25.x86_64-darwin).
