### ISSUE TITLE
When a build step can't be queued, report that in hydra-queue-runner

### ISSUE THREAD

**Issue by domenkozar** [NixOS/hydra#502]
For example I had a 64bit linux build that dependend on i686 step, but that wasn't clear from Hydra, had to lookup source.

**Comment by dtzWill** [comment]
Are the steps not queued or added to the queue but never executed? (related: #266, #413, #433)

But yes improving how this is handled would be great, it seems most everyone runs into this when setting up a Hydra instance (especially re:i686/x86-64).

**Comment by domenkozar** [comment]
Yeah another bug I hit then is that you need to specify `systems = [ ... ]` instead of two slaves with `system = ..`

**Comment by domenkozar** [comment]
Duplicates #266
