### ISSUE TITLE
deepClone option in gitInput troubles

### ISSUE THREAD

**Issue by nlewo** [NixOS/hydra#510]
Consider two jobsets with the same git input, one without the `deepClone` option while the other one have the `deepClone` enabled.
If the first jobset is evaluated before the second one, the second one will not have the `.git` directory since it reuses the store path of the first evaluation.

To reproduce, create two jobset with gitinput such as:
```
input of jobset 1: git-repo master
input of jobset 2: git-repo master deepClone
```
Next, evaluate jobset1 before jobset2 and check the content of the clone directory.

**Comment by Mirroregg123** [comment]
Hi,

I just want to revive this topic, since I have the same problem right now.
For one jobset I need the .git directory, for the other I would like it to be filtered.

Thats why I have two input sources, ohne with deepClone and one without.
But the result is still not deterministic.

Cheers
