### ISSUE TITLE
Github PR plugin fails with permission error

### ISSUE THREAD

**Issue by phile314-fh** [NixOS/hydra#531]
Using the Github PR plugin started to fail with a permission error:

```
Jan 31 00:04:25 hydra hydra-evaluator[19337]: starting evaluation of jobset ‘viskar:.jobsets’ (last checked 30 s ago)
Jan 31 00:04:32 hydra hydra-evaluator[19337]: hydra-eval-jobs returned exit code 1:
Jan 31 00:04:32 hydra hydra-evaluator[19337]: warning: Nix search path entry '/nix/store/x9lnkcwbanf0v2jandppmp9rkw90sipb-github-pulls-sorted.json
Jan 31 00:04:32 hydra hydra-evaluator[19337]: ' does not exist, ignoring
Jan 31 00:04:32 hydra hydra-evaluator[19337]: error: access to path '/nix/store/x9lnkcwbanf0v2jandppmp9rkw90sipb-github-pulls-sorted.json' is forbidden in restricted mode
Jan 31 00:04:32 hydra hydra-evaluator[19337]: (use '--show-trace' to show detailed location information)
Jan 31 00:04:32 hydra hydra-evaluator[19337]: evaluation of jobset ‘viskar:.jobsets’ failed with exit code 1
Jan 31 00:04:35 hydra hydra-evaluator[19337]:   jobset is unchanged, skipping
```

I have setup the Github PR plugin about a week ago and it worked fine for the first week, but in the last few days it always fails with this error. I was running hydra with ``useSandbox = "relaxed"``. I changed it now to ``useSandbox = false`` and it appears to work again. However, I would find it nice if I could have both Github PRs and the sandbox enabled at the same time.

**Comment by phile314-fh** [comment]
The error is back again, no idea why though. I have the sandbox disabled for the Hydra machine. I aslo checked if the file ``/nix/store/x9lnkcwbanf0v2jandppmp9rkw90sipb-github-pulls-sorted.json`` exists, and it is indeed there.

Does anybody have any ideas how to debug this?

**Comment by phile314-fh** [comment]
NixOS configuration excerpt:
```
  system.stateVersion = "17.09";

  nix = {
    extraOptions = "auto-optimise-store = true";

    # pull request plugin for hydra fails with relaxed
    useSandbox = false; #"relaxed";

    # build slave options
    distributedBuilds = true;

    buildMachines = [{
      hostName = "localhost";
      maxJobs = 2;
      systems = [ "i686-linux" "x86_64-linux"];
      supportedFeatures = [ "kvm" "nixos-test" "big-parallel" ];
    }];
  };
  environment.etc = {
    "nix/id_buildfarm" = {
      target = "nix/id_buildfarm";
      source = ../keys/id_buildfarm;
      uid = config.ids.uids.hydra;
      gid = config.ids.gids.hydra;
      mode = "0440";
    };
  };

  system.autoUpgrade = {
    enable = true;
    channel = "https://nixos.org/channels/nixos-17.09";
  };

services.hydra = {
    enable = true;
    hydraURL = "https://XYZ/";
    notificationSender = "xyz@xyz";
    port = 8080;
    extraConfig = ''
      using_frontend_proxy 1
      binary_cache_secret_key_file = ...
      max_output_size = 4294967296
      <githubstatus>
        jobs = viskar:.*:.*
        inputs = viskarSrc
        authorization = Basic XYZ==
        excludeBuildFromContext = 1
      </githubstatus>
      <github_authorization>
        XYZ_GH_ORG = Basic XYZ
      </github_authorization>
      '';
    buildMachinesFiles = [ "/etc/nix/machines" ];
  };

  services.postgresql = {
    enable = true;
    package = pkgs.postgresql96;
  };
```

Project Declarative Config (spec.json):
```
{ "enabled": 1
, "hidden": false
, "description": "PR jobsets"
, "nixexprinput": "viskar-ops"
, "nixexprpath": "ci/jobsets.nix"
, "checkinterval": "30"
, "schedulingshares": 20
, "enableemail": false
, "emailoverride": ""
, "keepnr": 3
, "inputs":
  { "nixpkgs":
    { "type": "git"
    , "value": "https://github.com/NixOS/nixpkgs-channels.git nixos-17.09"
    , "emailresponsible": false
    }
  , "viskar-ops":
    { "type": "git"
    , "value": "https://KEY@github.com/XYZ_GITHUB_ORG/viskar-ops.git"
    , "emailresponsible": false
    }
  , "pulls":
    { "type": "githubpulls"
    , "value": "XYZ_GITHUB_ORG VISKAR"
    , "emailresponsible": false
    }
  }
}
```

PR Nix file (jobsets.nix):
```
{ pulls }:
let
  pkgs = import <nixpkgs>{};
in with (import ./lib.nix { inherit pkgs; });
with pkgs.lib;
let
  defaults = {
    enabled = 1;
    hidden = false;
    keepnr = 10;
    schedulingshares = 100;
    checkinterval = 60;
    enableemail = false;
    emailoverride = "";
    nixexprinput = "viskar-ops";
    nixexprpath = "ci/jobs.nix";
  };

  makeViskarJobset = branch: viskarEnv: defaults // {
    description = "viskar ${branch}";
    inputs = {
      "viskar-ops" = mkFetchGithub "https://KEY@github.com/XYZ_GITHUB_ORG/viskar-ops.git ${branch}";
      viskarSrc = mkFetchGithub "https://KEY@github.com/ZYX_GITHUB_ORG/VISKAR.git ${branch}";
      nixpkgs = mkFetchGithub "https://github.com/nixos/nixpkgs-channels.git nixos-17.09";
      viskarEnv = {
        type = "string";
        value = viskarEnv;
        emailresponsible = false;
      };
    };
  };

  primary_jobsets = {
    develop = makeViskarJobset "develop" "CI";
    master = makeViskarJobset "master" "Prod";
  };
  pr_data = builtins.fromJSON (builtins.readFile pulls);
  makePr = num: info: {
    name = "viskar-${num}";
    value = defaults // {
      description = "PR ${num}: ${info.title}";
      inputs = {
        viskarSrc = mkFetchGithub "https://KEY@github.com/${info.head.repo.owner.login}/${info.head.repo.name}.git ${info.head.ref}";
        "viskar-ops" = mkFetchGithub "https://KEY@github.com/ISSKA/viskar-ops.git develop";
        nixpkgs = mkFetchGithub "https://github.com/nixos/nixpkgs-channels.git nixos-17.09";
        viskarEnv = {
          type = "string";
          value = "CI";
          emailresponsible = false;
        };
      };
    };
  };
  pull_requests = listToAttrs (mapAttrsToList makePr pr_data);
  jobsetsAttrs =  pull_requests // primary_jobsets;
in {
  jobsets = pkgs.writeText "spec.json" (builtins.toJSON jobsetsAttrs);
}
```

**Comment by vcanadi** [comment]
@phile314-fh Any progress? I am experiencing the same problem with similar setup. github-pulls-sorted.json also exist in the store.

**Comment by phile314-fh** [comment]
No, not so far. I just now enabled the HYDRA_DEBUG flag and this is what I get in the log:
<pre>
evaluator: 'hydra-eval-jobs' '/nix/store/hfkwf9bybm11ah1czd4vk3hgghzgyald-git-export/ci/jobsets.nix' '--gc-roots-dir' '/nix/var/nix/gcroots/hydra' '-j' '1' '-I' 'declInput=/nix/store/hfkwf9bybm11ah1czd4vk3hgghzgyald-git-export' '--arg' 'declInput' '{ outPath = builtins.storePath /nix/store/hfkwf9bybm11ah1czd4vk3hgghzgyald-git-export; inputType = "git"; uri = "https://6a8f60e9d37281eaf2aa8707d4c0b1a1b6d40be1@github.com/ISSKA/viskar-ops.git"; rev = "236b727e6845040bd76624a0d2117844cc28d7f8"; revCount = 242; gitTag = "236b727"; shortRev = "236b727";}' '-I' 'nixpkgs=/nix/store/dxfqv180fhnh12qcd0mhr2mvp75lcybm-git-export' '--arg' 'nixpkgs' '{ outPath = builtins.storePath /nix/store/dxfqv180fhnh12qcd0mhr2mvp75lcybm-git-export; inputType = "git"; uri = "https://github.com/NixOS/nixpkgs-channels.git"; rev = "59890bb135162c86f2c70314c2cc285a521898f8"; revCount = 117270; gitTag = "59890bb135"; shortRev = "59890bb135";}' '-I' 'pulls=/nix/store/5xld5m7mcjsyp98jahr9y8slqn4w96xc-github-pulls-sorted.json
' '--arg' 'pulls' '{ outPath = builtins.storePath /nix/store/5xld5m7mcjsyp98jahr9y8slqn4w96xc-github-pulls-sorted.json
; inputType = "githubpulls"; rev = "20180212075013";}' '-I' 'viskar-ops=/nix/store/hfkwf9bybm11ah1czd4vk3hgghzgyald-git-export' '--arg' 'viskar-ops' '{ outPath = builtins.storePath /nix/store/hfkwf9bybm11ah1czd4vk3hgghzgyald-git-export; inputType = "git"; uri = "https://6a8f60e9d37281eaf2aa8707d4c0b1a1b6d40be1@github.com/ISSKA/viskar-ops.git"; rev = "236b727e6845040bd76624a0d2117844cc28d7f8"; revCount = 242; gitTag = "236b727"; shortRev = "236b727";}'
accepted connection from pid 31403, user hydra
GitInput: Unable to load git-input section
GitInput: Using default values
hydra-eval-jobs returned exit code 1:
warning: Nix search path entry '/nix/store/5xld5m7mcjsyp98jahr9y8slqn4w96xc-github-pulls-sorted.json
' does not exist, ignoring
error: access to path '/nix/store/5xld5m7mcjsyp98jahr9y8slqn4w96xc-github-pulls-sorted.json' is forbidden in restricted mode
(use '--show-trace' to show detailed location information)
evaluation of jobset ‘viskar:.jobsets’ failed with exit code 1
  jobset is unchanged, skipping
</pre>

**Comment by phile314-fh** [comment]
It appears the problem is a superfluous newline in the
<pre>
'-I' 'pulls=/nix/store/5xld5m7mcjsyp98jahr9y8slqn4w96xc-github-pulls-sorted.json
'
</pre> argument. If I remove the trailing newline and execute the command manually it succeeds.

**Comment by phile314-fh** [comment]
I suspect the problem happens at https://github.com/NixOS/hydra/blob/master/src/lib/Hydra/Plugin/GithubPulls.pm#L59 . ``nix-store --add`` seems to return a trailing LF when I look at the output with a hex viewer.

**Comment by dalaing** [comment]
I'm seeing this and I'm not using the GitHub PR functionality.  I just changed a project from using the release-17.09 branch of nixpkgs to the master branch and it appeared.  It seems to still be erroring after I changed back, which seems bad.

**Comment by dalaing** [comment]
I'm seeing this and I'm not using the GitHub PR functionality (although I am using declarative builds).  I just updated Hydra, and since then I'm seeing:

```
hydra-eval-jobs returned exit code 1:
error: access to path '/nix/store/7byq5kc9zyjwnzvyfxacld4nrvijb3zz-cabal2nix-transformers-0.5.4.0' is forbidden in restricted mode
(use '--show-trace' to show detailed location information)
```

for some of my jobs.

The strange things is that is turning up as an evaluation error, although it is still triggering a build (and the build is going ahead successfully).

**Comment by ck3d** [comment]
Same problem on my Hydra 2017-11-21 (using nix-unstable-1.12pre5873_b76e282d).

My workaround was setting build-use-sandbox from "relaxed" to false.

**Comment by ck3d** [comment]
My problem is related to restrict-eval. The new Hydra uses nixUnstable which forbids accessing /nix/store.

**Comment by ck3d** [comment]
I boiled down my problem to following Hydra issue https://github.com/NixOS/hydra/issues/537 .

**Comment by ElvishJerricco** [comment]
I'm still seeing this with the PR functionality, though I suspect now the cause is the same as #537.
