### ISSUE TITLE
broken imports during job eval

### ISSUE THREAD

**Issue by ck3d** [NixOS/hydra#537]
After upgrading from Hydra based on Nix stable to unstable, I got a lot of 'forbidden in restricted mode' problems.

Hydra based on Nix unstable fails to eval following job, lets name it _realse.nix_:
```
{ nixpkgs ? <nixpkgs> }: 
with (import nixpkgs {}); {
  job = runCommand "hydra-import-issue" {} ''
    echo ${(import "${path}/lib").toUpper "foobar"} > $out
  '';
}
```
Hydra log tells us:
```
hydra-eval-jobs returned exit code 1:
error: access to path '/nix/store/2mw4z1764mb481w5f1hagwbbz5c15a7d-qdp23mf2x02sc63nhaxld6kw95pdhs5s-git-export/lib' is forbidden in restricted mode
(use '--show-trace' to show detailed location information)
```
The path to import was prefixed by an additional hash.

Nix unstable itself allows to evaluate the job:
```
#! /usr/bin/env nix-shell
#! nix-shell -i bash -p nixUnstable

set -e

nixpkgs=$(readlink -f $(nix-instantiate --eval --expr '<nixpkgs>'))

nix-instantiate --eval --option restrict-eval true \
  -I nixpkgs=$nixpkgs \
  --expr "$(cat release.nix)" -A job
```

A workaround is to replace `${path}/lib` with `<nixpkgs/lib>`.

Hydra based on the stable Nix do not have the problem.

All packages are taken from nixos-17.09. Hydra tells _2017-11-21 (using nix-unstable-1.12pre5873_b76e282d)_

**Comment by ctheune** [comment]
I've just started looking into a similar issue we've been having.

Our hydra is still running on 17.09, though (c632884e64e) with nix 1.11.16.

The weird thing is, that I'm tracking down the change that broke it for us. I don't think we touched our hydra and it's also related to an import:
hydra-eval-jobs returned exit code 1:
error: access to path '/nix/store/m7rvsc7kljfcj56xnx3p7ypsclsnwra0-nixpkgs-c1d9aff-src' is forbidden in restricted mode
(use '--show-trace' to show detailed location information)

(Currently visible at https://hydra.flyingcircus.io/jobset/flyingcircus/fc-15.09-dev#tabs-errors)

What is weird for me is that this breaks on our staging branch, too, which hasn't seen a change, so I guess that this _is_ somehow related to some change on Hydra  then ...

**Comment by ctheune** [comment]
Oh, interesting. We're on the same Hydra and nix version then. I just noticed the footer: Hydra 2017-11-21 (using nix-unstable-1.12pre5873_b76e282d).

So I guess hydra uses its own version of nix then. I wonder whether we accidentally updated this when this might have been updated in the 17.09 branch pointing to a specific hydra version.

**Comment by ctheune** [comment]
Weird. I think we've been using 2017-09-14 before, as I can see that sitting in the store. However, I'm not seeing any change in the nixpkgs repo that has ever included that version ... consider me confused now. :)

**Comment by dalaing** [comment]
I updated our NixOS server the other day, which updated Hydra.  Since then, all of our projects that use cabal2nix have been failing with a similar error to the one mentioned in this issue.  I'm about to attempt a downgrade now.

**Comment by dalaing** [comment]
I'm struggling to downgrade. I did a GC before I realised this issue was hitting me, so it's not in the store.  I've done a package override to try to wind Hydra back, but it's not compiling for me. 

Grizzly details [here](https://gist.github.com/dalaing/c87af0da55a3708920ebb4c8769f214f)

It looks like Hydra depends on a particular version of nixUnstable but that version isn't given explicitly, so getting winding back to an arbitrary version of Hydra is going to be difficult.

**Comment by ctheune** [comment]
See my last comment. Did you try building using nix-1.12pre5619_346aeee1? That works for me.

**Comment by dalaing** [comment]
I'm still pretty new to NixOS, so it's not 100% clear to me how to shoehorn that into my configuration.nix so that Hydra gets built with that nix.

My Hydra set up looks something like [this](https://gist.github.com/dalaing/4023355b488040ec2a740bc1171b7551) and I've rolled back Hydra using the changes to configuration.nix from my last comment.

I'm guessing I should override the attributes of the overridden Hydra, so that the nixUnstable attribute points to that particular version of Nix.  Am I close? :)

**Comment by dalaing** [comment]
OK, I think I have this sorted now thanks to some help from the IRC channel. As usual, I was making things a bit too complicated for myself :)

**Comment by 4e6** [comment]
It seems that `nixUnstable` version was bumped in https://github.com/NixOS/nixpkgs-channels/commit/08d1f139729a18efe568d16001dab1b897fa1d15
Pinning nixpkgs to previous commit fixed the issue for me.

**Comment by ryantrinkle** [comment]
@4e6 What commit did you end up pinning to?  I'm running into this as well, now; looking for a workaround or fix.

**Comment by 4e6** [comment]
@ryantrinkle currently it is set to https://github.com/NixOS/nixpkgs/commit/e79033b572a13a7b78ec7dc428f09e065bf26869

**Comment by ck3d** [comment]
compare following:
```
"${pkgs.path}/nixos"
```
is not the same as
```
pkgs.path + "/nixos"
```
and the second way to expand a path is possible in restricted mode.
