### ISSUE TITLE
No declarative jobsets evaluated due to "builtin" requirement

### ISSUE THREAD

**Issue by sorki** [NixOS/hydra#540]
When using declarative jobsets and recent hydra I've had to add an explicit "localhost" machine with "builtin" as a system due to jobs waiting for "builtin:local" feature. 
```
          { hostName = "localhost";
            maxJobs = 1;
            supportedFeatures = [ "kvm" "nixos-test" ];
            systems = [ "builtin" "x86_64-linux" ];
            #systems = [ "x86_64-linux" ];
            mandatoryFeatures= [ "local" ];
            speedFactor = 1;
          }   
```
I think this might be related to 

https://github.com/NixOS/nix/commit/6ddfe9a999027f9867bbf61ae92c19c591c89a86

**Comment by dtzWill** [comment]
Hitting this as well when jobset uses `<nix/fetchurl>`, as is done in bootstrapping nixpkgs.

**Comment by dtzWill** [comment]
Awesome, thanks!
