### ISSUE TITLE
evaluation failed: Too many heap sections

### ISSUE THREAD

**Issue by xeji** [NixOS/hydra#549]
Eval of Jobset nixos:release-18.03 failed with:

```
Errors occurred at 2018-03-23 16:40:16.

hydra-eval-jobs returned signal 6:
Too many heap sections: Increase MAXHINCR or MAX_HEAP_SECTS
```

I have seen this error several times recently, also in other jobsets.

**Comment by ixmatus** [comment]
Yes, you can get around this by increasing the initial heap size; e.g. in our configuration (you may not need this much memory, btw):

```
    hydra-evaluator = {
      # This allows Hydra to evaluate very large derivations if necessary
      environment."GC_INITIAL_HEAP_SIZE" = "15G";
    };
```
