### ISSUE TITLE
Job constantly aborting in Hydra

### ISSUE THREAD

**Issue by copumpkin** [NixOS/hydra#586]
https://hydra.nixos.org/build/79018129#tabs-buildsteps

I keep seeing it start, then abort, then it tries again. Any idea what's up? @edolstra @grahamc

**Comment by edolstra** [comment]
Looks like the queue runner is constantly crashing.
```
# journalctl -u hydra-queue-runner --since today | grep 'terminate called'
Aug 08 08:05:40 chef hydra-queue-runner[16151]: terminate called after throwing an instance of 'std::bad_alloc'
Aug 08 08:53:43 chef hydra-queue-runner[23282]: terminate called after throwing an instance of 'std::bad_alloc'
Aug 08 10:54:26 chef hydra-queue-runner[31129]: terminate called after throwing an instance of 'std::bad_alloc'
Aug 08 12:27:31 chef hydra-queue-runner[31616]: terminate called after throwing an instance of 'std::bad_alloc'
Aug 08 16:25:48 chef hydra-queue-runner[11967]: terminate called after throwing an instance of 'nix::Error'
Aug 08 17:11:10 chef hydra-queue-runner[22291]: terminate called after throwing an instance of 'std::bad_alloc'
Aug 08 17:13:49 chef hydra-queue-runner[10716]: terminate called after throwing an instance of 'std::bad_alloc'
Aug 08 18:20:36 chef hydra-queue-runner[13837]: terminate called after throwing an instance of 'std::bad_alloc'
```

**Comment by edolstra** [comment]
I suspect the `std::bad_alloc` is coming from a S3 TransferManager thread. Unfortunately the core dump is uninformative due to https://gcc.gnu.org/bugzilla/show_bug.cgi?id=55917.

**Comment by dtzWill** [comment]
Bah, that's lame.  FWIW I found I needed to remove the transfermanager
usage entirely (no multi-part uploads) to resolve a similar problem for me
after it was introduced.

I think there was some concern re:lifetime of the transfermanager across
instances of it, but don't remember where that ended up.

Anyway if reverting that resolves it for you as well, might be worth
running that until the debugging finds a better solution.

Might be worth trying, hope that helps!

~Will

**Comment by copumpkin** [comment]
Any idea why this would suddenly start happening? The last update to nixos-18.03 was a few days ago and built chromium just fine. Now it seems to crash consistently. Did someone deploy a change to hydra between now and then?

**Comment by copumpkin** [comment]
The jobset is starting to pile up as a result of this: https://hydra.nixos.org/jobset/nixos/release-18.03

**Comment by ngortheone** [comment]
I've also been wondering why my recent changes aren't showing up in the channel. Can anyone look into this bug or revert the change that made it appear?

**Comment by copumpkin** [comment]
Thanks @edolstra!
