### ISSUE TITLE
When services.hydra.minimumDiskFree is reached, queue-runner stops without explaining why

### ISSUE THREAD

**Issue by clacke** [NixOS/hydra#614]
We spent some time trying to figure out what was killing it.

The hydra-queue-runner log could contain a line of "reached minimum available disk space, exiting." or something to that effect.

**Comment by Taneb** [comment]
Seconded, this has bitten me in the past

**Comment by Ma27** [comment]
There's a systemd unit named `hydra-check-space.service` that iteratively checks that the minimum disk space requirement is met and logs whenever `hydra-queue-runner.service` or `hydra-evaluator.service` needs to be stopped.

Do you think that's sufficient if it's documented sufficiently?

**Comment by clacke** [comment]
When trouble-shooting, you're very unlikely to go check the logs of `hydra-check-space` to find out if that's why your process keeps stopping. It needs to be logged in the logs of those processes that stop.

**Comment by kquick** [comment]
Proposed https://github.com/NixOS/hydra/pull/777 does not solve the issue where the message is not logged against the service that is stopped, but it does handle restarting the service if space becomes available.  This helps in situations where the builds get ahead of the GC.
