### ISSUE TITLE
Disable some persistently failing GNU jobs

### ISSUE THREAD

**Issue by rgmorris** [NixOS/hydra#621]
Hi,

Following on from issue #620, the following GNU jobs have been failing completely for many months, so I would suggest disabling them (although I don't have any involvement with any of these). From https://hydra.nixos.org/project/gnu :

ccd2cue
datamash-master
glibc-hurd
gnumach-master
gnumach-user-level-drivers
octave-default

Thanks!

**Comment by rgmorris** [comment]
PS also: rcs-master

**Comment by rgmorris** [comment]
> PS also: rcs-master

Of course, as soon as I write that, that one starts working again, for the first time in six month! :)

**Comment by aycanirican** [comment]
LOL :D

**Comment by edolstra** [comment]
Thanks, done!
