### ISSUE TITLE
missing parsed-derivations.hh file

### ISSUE THREAD

**Issue by ninegua** [NixOS/hydra#625]
https://github.com/NixOS/hydra/blob/3ef253c65f03cc7ede70ca753cd654eb6f771635/src/hydra-queue-runner/state.hh#L13

Apparently this file is not in repository, and is giving me build errors. Am I missing something here?

**Comment by edolstra** [comment]
You need to build against a newer unstable version of Nix. Nixpkgs 18.09 should have a sufficiently new version.
