### ISSUE TITLE
Show machine name for a succesful build

### ISSUE THREAD

**Issue by danbst** [NixOS/hydra#671]
Successful build: https://hydra.nixos.org/build/95144506
Unsuccessful build: https://hydra.nixos.org/build/94502574

In first case it is not know which machine did the build. Would be great to figure out, whether build failure is machine related or something another.

**Comment by edolstra** [comment]
You can see the machines that did the build under the `Build steps` tab: https://hydra.nixos.org/build/95144506#tabs-buildsteps
