### ISSUE TITLE
Case folding mismatch with PostgreSQL 8.4

### ISSUE THREAD

**Issue by civodul** [NixOS/hydra#71]
See http://thread.gmane.org/gmane.linux.distributions.nixos/10326 for the original report.

Note that I don't know if the problem relates to this specific version of PG, or if there are other parameters to consider.

**Comment by domenkozar** [comment]
@civodul is this still an issue?

**Comment by civodul** [comment]
Domen Kožar <notifications@github.com> skribis:

> @civodul is this still an issue?

I don’t think so, thanks for checking!  :-)

Ludo’.
