### ISSUE TITLE
Allow aggregate jobs to be created from a list of job names

### ISSUE THREAD

**Issue by edolstra** [NixOS/hydra#715]
Evaluating an aggregate job takes as much memory as the sum of its constituents - no constituent expression can be garbage-collected while the top-level expression is reachable. For example, the `tested` job in NixOS's `release-combined.nix` takes > 12 GB. 

As an alternative, we could support aggregates to be specified as a list of job names, e.g.
```
{
  tested = {
    type = "hydraAggregate";
    constituents =
      [ "nixos.iso_plasma5.x86_64-linux"
        "nixos.iso_minimal.aarch64-linux"
        ...
      ];
  };
}
```

`hydra-eval-jobset` can then lookup the constituent's in the JSON output of `hydra-eval-jobs` and create a derivation that depends on the `drvPaths` of the constituents.

**Comment by vcunat** [comment]
Well, we do have evaluation now, but the `tested` jobsets get aborted after all constituents succeeding ([example link](https://hydra.nixos.org/build/113080249)).  For unstable-small it started in the small range `1e0222cd1f6..895042956f2` containing the change, so it seems clear to have triggered the problem.

**Comment by edolstra** [comment]
Looks like we're generating a bad derivation (`...drv.drv`).

**Comment by edolstra** [comment]
Fixed in https://github.com/NixOS/nix/commit/edee6169bf772ba101be7cd2dcb5aa7814415466.
