### ISSUE TITLE
gnu/emacs-trunk builds failing with "unexpected worker error"

### ISSUE THREAD

**Issue by rgmorris** [NixOS/hydra#716]
Hi,

Since about a day ago, https://hydra.nixos.org/jobset/gnu/emacs-trunk builds are failing with an evaluation error, eg:

`hydra-eval-jobs returned signal 134:
unexpected worker error: derivation '/nix/store/846hica1l3kpk9b5liw7js05hcjmbqm7-bootstrap-tools.drv' has incorrect output '/nix/store/n9acaakxahkv1q3av11l93p7rgd4xqsf-bootstrap-tools', should be '/nix/store/pvyfj9p8hjjmrkdrf13xg9gyrlrpzzyh-bootstrap-tools'
unexpected worker error: derivation '/nix/store/81vz7p33wqd9bijljwbniml47kgciwn0-bootstrap-tools.drv' has incorrect output '/nix/store/bb8vnqjnacib02kxr2jdnsya4s960irq-bootstrap-tools', should be '/nix/store/gxgsd6c8cngy1bb6q0qibxd27n89d4bz-bootstrap-tools'
unexpected handler thread error: unexpected EOF reading a line
unexpected worker error: error parsing derivation '/nix/store/m53k41mmvcavzbkv85nljkpspqf2isv5-ld-wrapper.sh': expected string 'Derive(['
unexpected worker error: error parsing derivation '/nix/store/072184hqi2mk5535faivca0vz8ig8pvz-setup-hook.sh': expected string 'Derive(['
`

I assume this is some internal problem?
Thanks for looking at this.

**Comment by edolstra** [comment]
Somehow it spontaneously started working again...
