### ISSUE TITLE
Jobsets from new GitHub PRs are not appearing in jobsets list

### ISSUE THREAD

**Issue by Br1ght0ne** [NixOS/hydra#751]
We have our Hydra (https://hydra.holo.host) set up to build PRs for https://github.com/Holo-Host/holo-nixpkgs in project [`holo-nixpkgs`](https://hydra.holo.host/project/holo-nixpkgs/).

It is set up declaratively. Jobsets are set up in [`jobsets.nix`](https://github.com/Holo-Host/holo-nixpkgs/blob/develop/jobsets.nix), JSON spec is [here](https://github.com/Holo-Host/holo-nixpkgs/blob/develop/profiles/logical/holo/hydra/master/specs/holo-nixpkgs.json).

When the project is created via Hydra web UI, `.jobsets` get evaluated, and all existing (open) PRs appear in jobsets list of `holo-nixpkgs`. When new PRs are opened against the repo, `.jobsets` gets re-evaluated (confirmed that `github-pulls-sorted.json` and `jobsets.json` are re-generated and contain the new jobsets), but these jobsets don't appear in `holo-nixpkgs` jobsets list.

---

Hydra server info:
- configuration: https://github.com/Holo-Host/holo-nixpkgs/blob/develop/profiles/logical/holo/hydra/master/default.nix#L66
- nixpkgs commit: https://github.com/NixOS/nixpkgs/commit/c5d5561f772f9ed9de272e3ccb7426de6e862dd1

**Comment by filalex77** [comment]
Update: after last attempt to recreate the project, `.jobsets` successfully evaluates, but no jobsets appear *at all*, even for branches (`master`, `develop`, etc.).
`.jobsets` build log: https://hydra.holo.host/build/4244
