### ISSUE TITLE
The database connection limit is too low

### ISSUE THREAD

**Issue by HackerFoo** [NixOS/hydra#758]
The hardcoded limit of 128 is too low for clusters that can run more than that number of jobs:

https://github.com/NixOS/hydra/blob/16ecd4f59d26ec5cdb50fac4f29487568b105f2d/src/hydra-queue-runner/hydra-queue-runner.cc#L51

It would be useful to make all arbitrary limits configurable.

**Comment by grahamc** [comment]
This line is actually defining a configurable, though?

**Comment by HackerFoo** [comment]
Huh, I was patching Hydra anyway and I missed that. At any rate, it seems like hydra.nixos.org is usually pegged at 128.

**Comment by grahamc** [comment]
Cool, what are you patching Hydra for? I've never looked at this option, but am thinking we should increase it, especially since we often have individual machines which can do nearly 100 builds :).

**Comment by HackerFoo** [comment]
The [remaining patch](https://github.com/HackerFoo/hydra-vtr-config/blob/master/hydra-defaults.patch) is to remove the default `timeout` and `maxSilent` limits, because I couldn't get the meta attributes to keep long quiet builds from timing out.

I'm running [Hydra cluster](https://hydra.vtr.tools/) with 20 96-core builders (1920 cores total, plus a 16-core machine to coordinate them) for running tests on various configurations of [VTR](https://verilogtorouting.org/), an open source FPGA CAD tool.

When I only had 10 builders up, I noticed that only ~12 jobs would run at a time, and so I was changing suspicious constants to find the bottleneck; I guess I should have gone back and looked closer at the code after fixing it. Now I can run the full 1920 jobs at once.

Here's [the configuration and notes](https://github.com/HackerFoo/hydra-vtr-config) if you're interested. I also had to submit a [PR](https://github.com/NixOS/nix/pull/3522) to Nix earlier because I was hitting the `FD_SETSIZE` limit with a large distributed nix-build. I'm not sure if that limit is affected by the way Hydra works, but that's why the [overlay](https://github.com/HackerFoo/hydra-vtr-config/blob/0385a874538d3035ffd7ea0feb86ec505bb2d93b/configuration.nix#L125-L135) is there.
