### ISSUE TITLE
ERROR:  null value in column "type" violates not-null constraint when adding a declarative jobset

### ISSUE THREAD

**Issue by knl** [NixOS/hydra#761]
When I try to add a declarative jobset, `.jobsets` job gets created, but it has an evaluation error:

```
DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed:
ERROR:  null value in column "type" violates not-null constraint

DETAIL:  Failing row contains (.jobsets, 118, hydra, hydra jobsets, src, hydra/jobsets.nix, null,
 null, null, 1589536378, 1, 0, 0, , 3, 30, 100, null, null, 1589536379, null, null). [for Statement 
"UPDATE jobsets SET checkinterval = ?, description = ?, enableemail = ?, nixexprinput = ?, 
nixexprpath = ?, type = ? WHERE ( ( name = ? AND project = ? ) )" with ParamValues: 1='30', 
2='hydra jobsets', 3='0', 4='src', 5='hydra/jobsets.nix', 6=undef, 7='.jobsets', 8='hydra'] at 
/nix/store/lsf81ip9ybxihk5praf2n0nh14a6i9j0-hydra-0.1.19700101.DIRTY/libexec/hydra/lib/Hydra/Helper/AddBuilds.pm
line 50
```

As the declarative jobset worked before Hydra introduced flakes (#730 by @edolstra), I suspect that is to blame. I fixed the issue by adding `type = 0` to the spec.json file, but my understanding of the code is that it [should not be necessary](https://github.com/NixOS/hydra/pull/730/files#diff-aed16ca3806cd6863503b1d62c3bb152R226).

What hinted me to look into `type` parameter of the job was `6=undef`.

NOTE: This behavior happens **on a newly deployed hydra from the latest master**. Old hydra is unaffected, even tho they both run the same version.

**Comment by knl** [comment]
This might be related to #751

**Comment by knl** [comment]
Upon more checking, I see that in `AddBuild.pm` (https://github.com/NixOS/hydra/blob/master/src/lib/Hydra/Helper/AddBuilds.pm#L30L48) Hydra does the following:

```
    my @allowed_keys = qw(
        enabled
        hidden
        type
        flake
        description
        nixexprinput
        nixexprpath
        checkinterval
        schedulingshares
        enableemail
        emailoverride
        keepnr
    );
    my %update = ( name => $jobsetName );
    foreach my $key (@allowed_keys) {
        $update{$key} = $declSpec->{$key};
        delete $declSpec->{$key};
    }
```

But none of the fields is with defaults, so if one is missing flake or type (like any old setup will), then it will result in an error when fed later into `update_or_create` on jobsets, as type will be `undef`.

**Comment by basvandijk** [comment]
What about filtering out undefined values such that the DB will use its configured defaults?

As in use the following in the `foreach` loop:
```
if (defined $declSpec->{$key}) {
  $update{$key} = $declSpec->{$key};
}
```

**Comment by knl** [comment]
> What about filtering out undefined values such that the DB will use its configured defaults?
> 
> As in use the following in the `foreach` loop:
> 
> ```
> if (defined $declSpec->{$key}) {
>   $update{$key} = $declSpec->{$key};
> }
> ```

Would that help? It just means the field will not show up in `%update` which means `create_or_update` gets something that misses a value. Since `type` is defined as `not null`, it will again result in the same problem, no?

**Comment by basvandijk** [comment]
Most `not null` values have a default defined:

```
hydra=> \d jobsets
                                 Table "public.jobsets"
      Column      |  Type   | Collation | Nullable |               Default
------------------+---------+-----------+----------+-------------------------------------
 name             | text    |           | not null |
 project          | text    |           | not null |
 description      | text    |           |          |
 nixexprinput     | text    |           |          |
 nixexprpath      | text    |           |          |
 errormsg         | text    |           |          |
 errortime        | integer |           |          |
 lastcheckedtime  | integer |           |          |
 triggertime      | integer |           |          |
 enabled          | integer |           | not null | 1
 enableemail      | integer |           | not null | 1
 hidden           | integer |           | not null | 0
 emailoverride    | text    |           | not null |
 keepnr           | integer |           | not null | 3
 checkinterval    | integer |           | not null | 300
 schedulingshares | integer |           | not null | 100
 fetcherrormsg    | text    |           |          |
 forceeval        | boolean |           |          |
 starttime        | integer |           |          |
 type             | integer |           |          | 0
 flake            | text    |           |          |
 id               | integer |           | not null | nextval('jobsets_id_seq'::regclass)
```

Unfortunately `emailoverride` doesn't seem to have a default (or maybe it's the empty string) so my solution might not work.

**Comment by basvandijk** [comment]
It's also worth mentioning that the schema of the `jobsets` table defined in [`src/lib/Hydra/Schema/Jobsets.pm`](https://github.com/NixOS/hydra/blob/a614199449e5a9541babe42bfc7977624c1137de/src/lib/Hydra/Schema/Jobsets.pm#L151) defines the `type` column to be `not null`. However there's no corresponding migration. So our Hydra DB still allows `null` as can be seen above.
