### ISSUE TITLE
Hydra fails to use substitutes on non-NixOS installation

### ISSUE THREAD

**Issue by b-bondurant** [NixOS/hydra#783]
I'm running Hydra on Ubuntu 20.04, and it seems to be building every single dependency from source rather than using the NixOS binary cache. Normal (non-Hydra) builds using e.g. `nix-build` or `nix-shell` have no issues fetching substitutes. I've tried looking around for similar issues, but none of the solutions I've found have worked for me.

Output of `nix-shell -p nix-info --run "nix-info -m"`:
```
 - system: `"x86_64-linux"`
 - host os: `Linux 5.4.0-37-generic, Ubuntu, 20.04 LTS (Focal Fossa)`
 - multi-user?: `yes`
 - sandbox: `yes`
 - version: `nix-env (Nix) 2.3.4`
 - channels(build): `"nixpkgs-20.03.2107.70717a337f7"`
 - channels(root): `"nixpkgs-20.03.2107.70717a337f7"`
 - nixpkgs: `/nix/var/nix/profiles/per-user/root/channels/nixpkgs`
```
and the contents of my nix.conf (build is the user under which I'm running Hydra):
```
build-users-group = nixbld
trusted-users = root build hydra-queue-runner
builders-use-substitutes = true
trusted-substituters = https://cache.nixos.org
substituters = https://cache.nixos.org
trusted-public-keys = cache.nixos.org-1:6NCHdD59X431o0gWypbMrAURkbJ16ZPMQFGspcDShjY=
cores = 0
max-jobs = 4
secret-key-files = /etc/nix/cache-key
substitute = true
```
Note: I'm sure I've added some unnecessary things to nix.conf (as well as the redundant root/user channels) - I basically started adding anything that seemed like it might possibly be relevant once my first few attempts didn't work.

My Hydra version is 2020-02-10, although I've also had this problem in an Ubuntu 20.04 VM with Hydra 2020-04-16. The Hydra builds in question use nixpkgs 20.03 from `git://github.com/NixOS/nixpkgs-channels nixos-20.03`. And I haven't run into this issue with the same builds in Hydra on NixOS.

**Comment by edolstra** [comment]
Make sure that `hydra.conf` contains the line `use-substitutes = 1`. By default Hydra doesn't use substitutes.

**Comment by b-bondurant** [comment]
Oh, I didn't even know there was a hydra.conf. Should I create it in /etc/nix or does it already exist somewhere?

**Comment by b-bondurant** [comment]
Ah, found the environment variable to set in hydra-module.nix. I put `hydra.conf` in `/var/lib/hydra` (although presumably you could put it anywhere that's owned by the user running Hydra), and then added `export HYDRA_CONFIG=/var/lib/hydra/hydra.conf` to my `.profile`. Thanks!
