### ISSUE TITLE
Behaviour of `upload_logs_to_binary_cache = true`

### ISSUE THREAD

**Issue by xbreak** [NixOS/hydra#785]
Is it the expected behaviour that logs are not available in Hydra web site if I set `upload_logs_to_binary_cache = true`?

What if I want to persist logs _and_ have them accessible in Hydra here: 
![image](https://user-images.githubusercontent.com/13489144/85045527-5d2ea880-b18f-11ea-9a8e-8a4e0f525ca9.png)
Is that not supported?

It seems hydra.nixos.org have both accessible, but if I set `upload_logs_to_binary_cache = true` on our own instance the logs are no longer accessible in Hydra.

Thanks in advance!

**Comment by edolstra** [comment]
You need to set `log_prefix`, e.g. `log_prefix = https://nix-cache.s3.amazonaws.com/`.

**Comment by xbreak** [comment]
Perfect, thanks!
