### ISSUE TITLE
Output is colored when terminal is not a tty

### ISSUE THREAD

**Issue by dasJ** [NixOS/hydra#792]
**Describe the bug**

Pretty similar to NixOS/nix#2648, but this time for nix error messages.
Output is colored even when piped (which looks pretty ugly).

Screenshot from our Hydra:

![image](https://user-images.githubusercontent.com/4971975/86926512-11d23f00-c12a-11ea-8ba9-0858273fe3a1.png)

**Steps To Reproduce**

1. `nix-build -E '(import <nixpkgs> {}).AAAAAASomeThingsFailToEvaluate' | cat`
2. See color being preserved

**Expected behavior**

No colored output should happen when the output is not a terminal.

**nix-env (Nix) 2.4pre20200622_334e26b**

**Additional context**

You can compare the reproduce stuff above with `ls --color=auto | cat`

cc @volth @ajs124
Also cc @bburdette since you seem to be the error-handling guy ;)

**Comment by volth** [comment]
> Oh… so is Hydra just pretending to be a tty? I'll move the issue, then

Obviously, to reliable kill all the child processes on exit.
That's why I wanted to untangle controlling over emoting ASCI-codes from `istty()`.
Terminal might be there for another reason than "I want colored output"
