### ISSUE TITLE
Hydra's database seems dead

### ISSUE THREAD

**Issue by pinage404** [NixOS/hydra#835]
I'm trying to get the ARM image on Hydra, but it seems dead

I get this error on every pages https://hydra.nixos.org/

> DBIx::Class::Storage::DBI::catch {...} (): DBI Connection failed: DBI connect('dbname=hydra;host=10.254.1.9;user=hydra;','',...) failed: could not connect to server: Connection refused
Is the server running on host "10.254.1.9" and accepting
TCP/IP connections on port 5432? at /nix/store/q8aix495ic9dc05di4khzfkl4b7m0rs4-hydra-perl-deps/lib/perl5/site_perl/5.32.0/DBIx/Class/Storage/DBI.pm line 1517. at /nix/store/4myymgl21z45dv6ys5c73qadr3lw9jry-hydra-0.1.20201102.73dfef3/libexec/hydra/lib/Hydra/Helper/CatalystUtils.pm line 420

![image](https://user-images.githubusercontent.com/6325757/99190755-b44d9f00-2768-11eb-97f6-b04b88676215.png)

I don't know if i report this issue on the good repo

**Comment by cole-h** [comment]
cc @NixOS/infra

**Comment by pinage404** [comment]
it seems good, now

thanks =)

**Comment by cole-h** [comment]
[From #nixos-infra on IRC](https://logs.nix.samueldr.com/nixos-infra/2020-11-15#1605461932-1605461397;):

```
09:29 <gchristensen> full disk, cleared out some older snapshots
09:31 <gchristensen> should be fixed
09:37 <gchristensen> https://gist.github.com/grahamc/3edccda26e134fc8f2b1230fcf86cf61 before / after data
09:38 <gchristensen> in "before" there are snapshots taking up a lot of space called rpool/safe/postgres@2020-02-06T03:40Z which is in a different snapshot format from recent snapshots rpool/safe/postgres@2020-11-15T16:30:00Z -- znapzend only pruned the ones matching the recent name, causing lots of very old data to keep a significant amount of disk space.
09:38 <gchristensen> up to 335G free
09:38 <gchristensen> just from deleting those very old snaps
```
