### ISSUE TITLE
ERROR: null value in column "type" violates not-null constraint is back

### ISSUE THREAD

**Issue by dhess** [NixOS/hydra#889]
#761 is back, or something like it, anyway. This just started appearing on our Hydra since Hydra 0.1.20210308.ebf1cd2:

```
Mar 10 16:22:35 hydra-b hydra-evaluator[41419]: DBIx::Class::Storage::DBI::_dbh_execute(): DBI Exception: DBD::Pg::st execute failed: ERROR:  null value in column "type" violates not-null constraint
Mar 10 16:22:35 hydra-b hydra-evaluator[41419]: DETAIL:  Failing row contains (62358, projectName, 0, null, null, null, hackworthltd, null, , null). [for Statement "INSERT INTO jobsetevalinputs ( altnr, dependency, eval, name, path, revision, sha256hash, type, uri, value) VALUES ( ?, ?, ?, ?, ?, ?, ?, ?, ?, ? )" with ParamValues: 1='0', 2=undef, 3='62358', 4='projectName', 5='', 6=undef, 7=undef, 8=undef, 9=undef, 10='hackworthltd'] at /nix/store/cmqblv437mp57yz5lwvkzcqca4ldf3r5-hydra-0.1.20210308.ebf1cd2/bin/.hydra-eval-jobset-wrapped line 793
Mar 10 16:22:35 hydra-b hydra-evaluator[25828]: evaluation of jobset ‘hackworthltd:.jobsets (jobset#1)’ failed with exit code 1
```

So far this is only affecting new GitHub PR builds, but existing builds are still working fine.

**Comment by dhess** [comment]
I figured this was probably related to 9e018d54431b5f23fc9c8c4823c210cc1a90bc40  so I reverted to a2717b3d7e69ca0f757a6a2d577d5ee23cca2e99 and sure enough, things are working again.

I suppose this means I need to add a `projectName` field to to my declarative inputs? @dasJ can you provide an example?

(It would be really helpful to have an example declarative jobspec somewhere, as setting these up has been sort of folklore for as long as I've been using Hydra :) )

**Comment by dasJ** [comment]
@dhess Nope, while you can (but you don't have to), I actually introduced a bug :/ #814 fixes that in `src/script/hydra-eval-jobset`. Sorry for that

**Comment by dasJ** [comment]
I'll get back to you once I managed to create a more comprehensive example. But #814 also contains some documentation on that matter, maybe that helps as well.

**Comment by dasJ** [comment]
@dhess have a look at https://git.helsinki.tools/helsinki-systems/hydra-nixos

Our corresponding Hydra config:

![image](https://user-images.githubusercontent.com/4971975/110696799-cfe32680-81eb-11eb-8df6-330ba4821dc3.png)

This should evaluate the unstable-small and 20.09-small channels for you :)

**Comment by grahamc** [comment]
PR: https://github.com/NixOS/hydra/pull/891
