### ISSUE TITLE
uncaught exception building ‘...’ on ‘...’

### ISSUE THREAD

**Issue by lopsided98** [NixOS/hydra#898]
After undating Hydra to the version currently in NixOS unstable (2021-03-10 (using nix-2.4pre20210317_8a5203d)), I'm seeing a huge number of errors like the following in the `hydra-queue-runner` log:

```
performing step ‘/nix/store/cb8nlqxwvqya6mcraxany6xscaqz79ym-ros-melodic-rviz-mesh-plugin-1.0.1-r1.drv’ 1 times on ‘localhost’ (needed by build 542802 and 0 others)
copying 0 paths...
outputs of ‘/nix/store/cb8nlqxwvqya6mcraxany6xscaqz79ym-ros-melodic-rviz-mesh-plugin-1.0.1-r1.drv’ substituted or already valid on ‘localhost’
marking step 8 of build 542802 as orphaned
uncaught exception building ‘/nix/store/cb8nlqxwvqya6mcraxany6xscaqz79ym-ros-melodic-rviz-mesh-plugin-1.0.1-r1.drv’ on ‘localhost’: basic_string::_M_create
will retry ‘/nix/store/cb8nlqxwvqya6mcraxany6xscaqz79ym-ros-melodic-rviz-mesh-plugin-1.0.1-r1.drv’ after 131225s
performing step ‘/nix/store/r99jz4gj2iq1v0hj08785cj92pypj8gi-ros-melodic-openzen-sensor-1.2.0-r1.drv’ 1 times on ‘localhost’ (needed by build 542873 and 0 others)
copying 0 paths...
outputs of ‘/nix/store/r99jz4gj2iq1v0hj08785cj92pypj8gi-ros-melodic-openzen-sensor-1.2.0-r1.drv’ substituted or already valid on ‘localhost’
marking step 8 of build 542873 as orphaned
uncaught exception building ‘/nix/store/r99jz4gj2iq1v0hj08785cj92pypj8gi-ros-melodic-openzen-sensor-1.2.0-r1.drv’ on ‘localhost’: basic_string::_M_create
will retry ‘/nix/store/r99jz4gj2iq1v0hj08785cj92pypj8gi-ros-melodic-openzen-sensor-1.2.0-r1.drv’ after 131228s
performing step ‘/nix/store/ysza0h20717gmabcpspz1m6f01sn40fq-ros-melodic-robot-one-0.1.1-r1.drv’ 1 times on ‘localhost’ (needed by build 543103 and 0 others)
copying 0 paths...
outputs of ‘/nix/store/ysza0h20717gmabcpspz1m6f01sn40fq-ros-melodic-robot-one-0.1.1-r1.drv’ substituted or already valid on ‘localhost’
marking step 8 of build 543103 as orphaned
uncaught exception building ‘/nix/store/ysza0h20717gmabcpspz1m6f01sn40fq-ros-melodic-robot-one-0.1.1-r1.drv’ on ‘localhost’: basic_string::_M_create
will retry ‘/nix/store/ysza0h20717gmabcpspz1m6f01sn40fq-ros-melodic-robot-one-0.1.1-r1.drv’ after 131229s
performing step ‘/nix/store/cf3fbdb4s8ambdh2480229n16hj688sk-ros-melodic-rostate-machine-0.0.2-r3.drv’ 1 times on ‘localhost’ (needed by build 543106 and 0 others)
copying 0 paths...
outputs of ‘/nix/store/cf3fbdb4s8ambdh2480229n16hj688sk-ros-melodic-rostate-machine-0.0.2-r3.drv’ substituted or already valid on ‘localhost’
marking step 8 of build 543106 as orphaned
uncaught exception building ‘/nix/store/cf3fbdb4s8ambdh2480229n16hj688sk-ros-melodic-rostate-machine-0.0.2-r3.drv’ on ‘localhost’: basic_string::_M_create
will retry ‘/nix/store/cf3fbdb4s8ambdh2480229n16hj688sk-ros-melodic-rostate-machine-0.0.2-r3.drv’ after 131227s
performing step ‘/nix/store/40fq788ks8vid0ly2ka53l73z808rlc9-ros-melodic-novatel-oem7-driver-2.1.0-r1.drv’ 1 times on ‘localhost’ (needed by build 543002 and 0 others)
copying 0 paths...
outputs of ‘/nix/store/40fq788ks8vid0ly2ka53l73z808rlc9-ros-melodic-novatel-oem7-driver-2.1.0-r1.drv’ substituted or already valid on ‘localhost’
marking step 8 of build 543002 as orphaned
uncaught exception building ‘/nix/store/40fq788ks8vid0ly2ka53l73z808rlc9-ros-melodic-novatel-oem7-driver-2.1.0-r1.drv’ on ‘localhost’: std::bad_alloc
will retry ‘/nix/store/40fq788ks8vid0ly2ka53l73z808rlc9-ros-melodic-novatel-oem7-driver-2.1.0-r1.drv’ after 131228s
```

This only seems to occur for localhost builds. I also noticed that the update has causes hundreds of builds to seem to be queued on localhost (i.e. they appear on the machine status page), although only a small number are actually building at once. I think this behavior might be related to the errors shown above.

**Comment by grahamc** [comment]
cc @shlevy I suspect your recent patch might have had some unforeseen consequences, can you take a look?

**Comment by tomberek** [comment]
Seeing a similar `bad_alloc`
```
Apr 02 06:44:20 perkeep hydra-queue-runner[11130]: will retry ‘/nix/store/sls5ybh8w7a8j05djvl0b53wc6k15w99-name.drv’ after 14588s
Apr 02 06:44:20 perkeep hydra-queue-runner[11130]: uncaught exception building ‘/nix/store/sls5ybh8w7a8j05djvl0b53wc6k15w99-name.drv’ on ‘root@3.333.111.94’: std::bad_alloc
Apr 02 06:44:20 perkeep hydra-queue-runner[11130]: marking step 6 of build 4486 as orphaned
Apr 02 06:44:20 perkeep hydra-queue-runner[11130]: outputs of ‘/nix/store/sls5ybh8w7a8j05djvl0b53wc6k15w99-name.drv’ substituted or already valid on ‘root@3.333.111.94’
Apr 02 06:44:19 perkeep hydra-queue-runner[11130]: performing step ‘/nix/store/sls5ybh8w7a8j05djvl0b53wc6k15w99-name.drv’ 1 times on ‘root@3.333.111.94’ (needed by build 4486 and 0 others)
Apr 02 05:24:46 perkeep hydra-queue-runner[11130]: cleaning orphaned step 5 of build 4486
```

This occurs only when running `distributedBuild = true` and on a remote machine. @lopsided98 were you running a "remote build on localhost"?

**Comment by lopsided98** [comment]
I have a `localhost` entry in my machines list, as well as some remote builders. I can't find any instances of the `bad_alloc` error for a remote builder in my logs.

**Comment by Ma27** [comment]
I think we can rule out #890 as issue. Since I have the same issue, I tried to revert it like this:

```
commit d637d4b55c6bb84f6ab70d61e75e5a04066a57f0
Author: Maximilian Bosch <maximilian@mbosch.me>
Date:   Tue Apr 13 14:19:02 2021 +0200

    Revert "Bump Nix version"
    
    This reverts commit 930f05c38eeac63ad6c3e3250de2667e2df2e96e.

diff --git a/flake.lock b/flake.lock
index 12abd38b..82427e9f 100644
--- a/flake.lock
+++ b/flake.lock
@@ -5,11 +5,11 @@
         "nixpkgs": "nixpkgs"
       },
       "locked": {
-        "lastModified": 1617795613,
-        "narHash": "sha256-dDDZcE3feC8we6azs99pWSz/uqYNPG3DJSNnjgJ6JsQ=",
+        "lastModified": 1613747933,
+        "narHash": "sha256-Q6VuNRdr87B4F3ILiM6IlQ+bkIYbQTs6EEAtwNrvl1Y=",
         "owner": "NixOS",
         "repo": "nix",
-        "rev": "906adadacd2d1c98346a2f42c0b42a32d2806d94",
+        "rev": "548437c2347159c4c79352283dd12ce58324f1d6",
         "type": "github"
       },
       "original": {
@@ -19,11 +19,11 @@
     },
     "nixpkgs": {
       "locked": {
-        "lastModified": 1614309161,
-        "narHash": "sha256-93kRxDPyEW9QIpxU71kCaV1r+hgOgP6/aVgC7vvO8IU=",
+        "lastModified": 1602702596,
+        "narHash": "sha256-fqJ4UgOb4ZUnCDIapDb4gCrtAah5Rnr2/At3IzMitig=",
         "owner": "NixOS",
         "repo": "nixpkgs",
-        "rev": "0e499fde7af3c28d63e9b13636716b86c3162b93",
+        "rev": "ad0d20345219790533ebe06571f82ed6b034db31",
         "type": "github"
       },
       "original": {
diff --git a/src/hydra-queue-runner/build-remote.cc b/src/hydra-queue-runner/build-remote.cc
index 966e27ca..92beb0b3 100644
--- a/src/hydra-queue-runner/build-remote.cc
+++ b/src/hydra-queue-runner/build-remote.cc
@@ -264,11 +264,8 @@ void State::buildRemote(ref<Store> destStore,
            a no-op for regular stores, but for the binary cache store,
            this will copy the inputs to the binary cache from the local
            store. */
-        if (localStore != std::shared_ptr<Store>(destStore)) {
-            StorePathSet closure;
-            localStore->computeFSClosure(step->drv->inputSrcs, closure);
-            copyPaths(ref<Store>(localStore), destStore, closure, NoRepair, NoCheckSigs, NoSubstitute);
-        }
+        if (localStore != std::shared_ptr<Store>(destStore))
+            copyClosure(ref<Store>(localStore), destStore, step->drv->inputSrcs, NoRepair, NoCheckSigs);
 
         /* Copy the input closure. */
         if (!machine->isLocalhost()) {
diff --git a/src/hydra-queue-runner/queue-monitor.cc b/src/hydra-queue-runner/queue-monitor.cc
index 26d780b2..e2dc95f6 100644
--- a/src/hydra-queue-runner/queue-monitor.cc
+++ b/src/hydra-queue-runner/queue-monitor.cc
@@ -509,9 +509,7 @@ Step::ptr State::createStep(ref<Store> destStore,
                         // FIXME: should copy directly from substituter to destStore.
                     }
 
-                    StorePathSet closure;
-                    localStore->computeFSClosure({*path}, closure);
-                    copyPaths(ref<Store>(localStore), destStore, closure, NoRepair, CheckSigs, NoSubstitute);
+                    copyClosure(ref<Store>(localStore), destStore, {*path});
 
                     time_t stopTime = time(0);

```

But I still have the same problem:

```
Apr 13 13:00:21 hydra hydra-queue-runner[4916]: marking step 389 of build 3 as orphaned
Apr 13 13:00:21 hydra hydra-queue-runner[4916]: uncaught exception building ‘/nix/store/4rxjh4ll5qmv3drp2pzfmahnmq5j3j0k-nginx.conf.drv’ on ‘roflmayr’: std::bad_alloc
Apr 13 13:00:21 hydra hydra-queue-runner[4916]: will retry ‘/nix/store/4rxjh4ll5qmv3drp2pzfmahnmq5j3j0k-nginx.conf.drv’ after 64s
Apr 13 13:00:21 hydra hydra-queue-runner[4916]: step ‘/nix/store/4rxjh4ll5qmv3drp2pzfmahnmq5j3j0k-nginx.conf.drv’ is now runnable
Apr 13 13:00:21 hydra hydra-queue-runner[4916]: dispatcher woken up
Apr 13 13:00:21 hydra hydra-queue-runner[4916]: dispatcher woken up
Apr 13 13:00:21 hydra hydra-queue-runner[4916]: dispatcher sleeping for 58s
Apr 13 13:00:21 hydra hydra-queue-runner[4916]: killing process 5245
Apr 13 13:00:21 hydra hydra-queue-runner[4916]: marking step 392 of build 3 as orphaned
Apr 13 13:00:21 hydra hydra-queue-runner[4916]: uncaught exception building ‘/nix/store/y2fk90kr8q106kydy9gak0di7gz2h3cx-system-path.drv’ on ‘roflmayr’: basic_string::_M_create
Apr 13 13:00:21 hydra hydra-queue-runner[4916]: will retry ‘/nix/store/y2fk90kr8q106kydy9gak0di7gz2h3cx-system-path.drv’ after 69s
Apr 13 13:00:21 hydra hydra-queue-runner[4916]: step ‘/nix/store/y2fk90kr8q106kydy9gak0di7gz2h3cx-system-path.drv’ is now runnable
Apr 13 13:00:21 hydra hydra-queue-runner[4916]: dispatcher woken up
Apr 13 13:00:21 hydra hydra-queue-runner[4916]: dispatcher sleeping for 58s
```

**Comment by Ma27** [comment]
Ok, it seems to be related (on my side at least) to the daemon protocol of Nix. Will try to deploy a newer Nix tonight and see what happens :)

**Comment by Ma27** [comment]
I have the same problem with Hydra at ffc4be6743c654f8796d3f3e3a913fe47ffb3481, Nix at `2.4pre20210407_906adad` and `nixpkgs` at 20.09 based on `628be63860a3bcd1be3a3d5017848b1d34756a0f`. It bothers me a bit that there don't seem to be too many people out there having the same issue even though I'm not aware of any workaround (and hence it seems rather "blocking" - to me at least). But unless I screwed up my configuration, this has to be a bug in how Hydra communicates with Nix I'm afraid :/

**Comment by lopsided98** [comment]
I haven't tested yet, but I just realized that my remote builder is running stable Nix (2.3.10), which is probably why this issue doesn't occur there.

**Comment by lopsided98** [comment]
I can confirm that upgrading my remote builder to `2.4pre20210326_dd77f71` triggers the bug, and it also triggers the symptom of huge number of builds being queued on the machine.

**Comment by grahamc** [comment]
Note that  since Nix's APIs are unstable and Hydra depends on them so much, should be built with exactly the version pinned: https://github.com/NixOS/hydra/blob/master/flake.lock#L11-L12 and I wouldn't be surprised if a mismatch was the problem here.

**Comment by lopsided98** [comment]
It seems like the problem is the Nix daemon version in this case, which we can't really expect to be pinned to the same version on all builders. Also, @Ma27 tried the pinned version and still experienced the problem.

**Comment by grahamc** [comment]
Interesting. I think most of hydra.nixos.org's builders run Nix stable from 20.09.

**Comment by grahamc** [comment]
It sounds like your machines might just be really low on RAM?

**Comment by lopsided98** [comment]
I'm not surprised that hydra.nixos.org doesn't experience this problem then, since it only happens with builders running Nix unstable.

I am 99% certain that these machines aren't out of RAM. The bug starts occurring immediately after starting the queue runner, before any memory intensive builds have started. The machines I'm testing with aren't very memory constrained anyway, with 32 GB of RAM on the Hydra server and 16 GB on the builder. It also wouldn't explain why the bug never occurs on builders running Nix stable.

**Comment by Ma27** [comment]
> I can confirm that upgrading my remote builder to 2.4pre20210326_dd77f71 triggers the bug, and it also triggers the symptom of huge number of builds being queued on the machine.

Ah, fair point, will try this out :) 

if this doesn't succeed, I'd try to reproduce the problem locally and try to bisect Hydra & Nix.

> It sounds like your machines might just be really low on RAM?

I think we can rule this out pretty much: the machine in question is a bare-metal thing with 64GB RAM and 12 build cores and no alerts from Prometheus.

**Comment by Ma27** [comment]
I can confirm that using Nix 2.3 for the daemon fixes the problem. Not really sure what's the core problem here though. Maybe something for @edolstra and @regnat to look at :)

**Comment by grahamc** [comment]
Interesting. I guess I'm a bit surprised bad_alloc is the thing, since I think that would only fail if the memory was highly fragmented, or you ran out of memory?

Maybe the protocol changed sufficiently and it is trying to allocate some outrageous amount of memory? Maybe hooking up a debugger could help us understand the bad_alloc message.

**Comment by Ma27** [comment]
Since I decided against using Nix 2.3 on this server (this misses a patch I contributed to nixUnstable which is more or less impossible to backport), that's what I gotta do...

But first, I'll have to try reproducing the issue locally :)

**Comment by grahamc** [comment]
It'd be cool if the next version of the protocol used protobufs or something with an existing tooling :).

**Comment by Ma27** [comment]
Ok nice, I can reproduce this locally with a store set to a non-`/nix/store` location and my builder declared in a file for `NIX_REMOTE_SYSTEMS`. Guess I gotta play `gdb` then %)

**Comment by regnat** [comment]
> Maybe the protocol changed sufficiently and it is trying to allocate some outrageous amount of memory?

That could be given how the protocol works. In particular when reading a string Nix [starts by allocating the size that's given to him](https://github.com/NixOS/nix/blob/master/src/libutil/serialise.cc#L339-L347). So if things are a bit mangled it could very indeed try to allocate some nonsical amount of memory.

@Ma27 is the repro easy-enough to be shared here?

**Comment by Ma27** [comment]
@regnat it should be sufficiently easy:

* I'm currently working on the Hydra git checkout of ffc4be67, so all other dependencies should be provided there via flakes.
* Do `nix develop` & compile the project as described in the manual.
* Add a `machines`-file (to an arbitrary location) with contents like this:
  ```
  builder-ng x86_64-linux /home/ma27/.ssh/id_rsa 10 4 kvm,nixos-test,local,builtin,big-parallel
  ```
  (`builder-ng` is configured in my `~/.ssh/config`, just a remote server)
* Set `export NIX_REMOTE_SYSTEMS=./machines` in `nix develop`
* Remove the `NIX_REMOTE_SYSTEMS=""` declaration from `foreman/start-queue-runner.sh`
* Add something like `store_uri = file:///home/ma27/Projects/hydra/.hydra-data/mystore` to `.hydra-data/hydra.conf`
* Start all services with e.g. `foreman start`.
* Create & Evaluate a non-trivial jobset on `localhost:63333` (feel free to use https://github.com/Ma27/nixpkgs/blob/networkd-containers/jobset.nix - this one worked perfectly fine on my server as soon as I downraded Nix to `nixStable`).
* As soon as the evaluation is finished, you should be seeing stuff like this in the stderr of `foreman start`:
  ```
  17:26:51 hydra-queue-runner.1 | checking the queue for builds > 0...
  17:26:52 hydra-queue-runner.1 | performing step ‘/nix/store/x1x2avf9sn3d95c055021dhkbnjccpsb-run-nixos-vm.drv’ 1 times on ‘builder-ng’ (needed by build 35 and 0 others)
  17:26:53 hydra-queue-runner.1 | copying 0 paths...
  17:26:53 hydra-queue-runner.1 | outputs of ‘/nix/store/x1x2avf9sn3d95c055021dhkbnjccpsb-run-nixos-vm.drv’ substituted or already valid on ‘builder-ng’
  17:26:53 hydra-queue-runner.1 | marking step 20 of build 35 as orphaned
  17:26:53 hydra-queue-runner.1 | uncaught exception building ‘/nix/store/x1x2avf9sn3d95c055021dhkbnjccpsb-run-nixos-vm.drv’ on ‘builder-ng’: basic_string::_M_create
  17:26:53 hydra-queue-runner.1 | will retry ‘/nix/store/x1x2avf9sn3d95c055021dhkbnjccpsb-run-nixos-vm.drv’ after 63s

  ```

**Comment by Ma27** [comment]
Btw @regnat are there any fancy tools or tricks to debug issues related to Nix's protocols (currently having a hard time getting forward)? Asking because you seem to contribute way more code to this than I do :)

**Comment by regnat** [comment]
> Btw @regnat are there any fancy tools or tricks to debug issues related to Nix's protocols (currently having a hard time getting forward)? Asking because you seem to contribute way more code to this than I do :)

I wish there were 😬

The best workflow I've found so far has been to use [rr](http://rr-project.org/) to replay one side of the of the transaction (reverse debugging being incredibly useful for this kind of stuff).

I've also occasionally (hex-)dumped the protocol messages and tried to parse manually to understand what was going on. But I wouldn't recommend that **at all** for public sanity reasons

**Comment by Ma27** [comment]
Ok, I guess I found the problem! :tada:  

Before `cmdQueryPathInfos`, there's a `cmdBuildDerivation` which sends back more stuff since ~January which is not caught by Hydra. Gotta grab some lunch now and test-deploy this to my new Hydra (only tested/fixed it in my dev setup now) and file a PR if that's it :)
