### ISSUE TITLE
Add instructions for how to associate the application/nix-package MIME type with the nix-install-package in http://hydra.nixos.org/jobset/nixpkgs/trunk/channel/latest

### ISSUE THREAD

**Issue by gregkar** [NixOS/hydra#90]
In the page above it is suggested that one associates the application/nix-package MIME type with nix-install-package, in order to be able to perform one-click installs. On ubuntu, this is straightforward to do for Firefox, which has its own file associations, but not for Chrome, which uses the file associations of Ubuntu. Moreover, nix-install-package does not show up in the "Open with" list of ubuntu (presumably because it is not installed through the ubuntu package manager). To add this association to Ubuntu, the easiest way is to download a nix package (e.g., right-click on one of the packages and "save link as"), and then run "mimeopen -d package-file-name.nixpkg". Please add some instructions about this on the page above.

**Comment by gilligan** [comment]
I'm afraid this is a tad bit too specific to be included in the hydra configuration.
