### ISSUE TITLE
Some of my permissions on hydra.nixos.org have disappeared

### ISSUE THREAD

**Issue by peti** [NixOS/hydra#900]
I used to be able to stop and restart jobs on `hydra.nixos.org`. I also used to be able to move builds to the front of the queue. A couple of weeks ago, however, I lost those privileges. Is there any particular reason why those abilities were removed from my user?

**Comment by grahamc** [comment]
Based on https://github.com/NixOS/nixos-org-configurations/wiki/Hydra-Accounts I added the restart-jobs, cancel-build, and bump-to-front roles. Not sure why or when your access was dropped, though.
