### ISSUE TITLE
The default machine file doesn't include localhost's declared features

### ISSUE THREAD

**Issue by regnat** [NixOS/hydra#936]
If hydra doesn't have a specified machine file, it’ll default to an [auto-generated one](https://github.com/NixOS/hydra/blob/107d60027fa22c3b919cce3e8565affbbd8aed3b/src/hydra-queue-runner/hydra-queue-runner.cc#L156-L159) with only `localhost` as a remote builder.
This generated machine file will specify the system and max-jobs according to the Nix configuration. However it doesn’t specify any `system-features` for it, meaning that building a derivation with a non-empty `requiredSystemFeatures` requires an explicit machine file (even if the nix conf specifies the relevant system features).

**Comment by grahamc** [comment]
What do you think a good solution is?

**Comment by regnat** [comment]
What do you think a good solution is?

I think we can get the system features from the nix API like
`maxBuildJobs` and `thisSystem` and inject them into the generated
file.

**Comment by Ericson2314** [comment]
I think this would be a good opportunity to try to bring the store options (vs global options) and machines files (for hydra and nix remote building, right?) closer together.
