### ISSUE TITLE
Can't delete any projects

### ISSUE THREAD

**Issue by cole-h** [NixOS/hydra#949]
If you spin up a local Hydra instance, create a project, and then try to delete that project, you'll be confronted with the following error:

```
{UNKNOWN}: Can't locate object method "jobsetevals" via package "Hydra::Model::DB::Projects" at /home/vin/workspace/vcs/hydra/src/script/../lib/Hydra/Controller/Project.pm line 81. at /home/vin/workspace/vcs/hydra/src/script/../lib/Hydra/Controller/Project.pm line 84 
```

Applying the following diff allows deletion to succeed:

```diff
diff --git a/src/lib/Hydra/Controller/Project.pm b/src/lib/Hydra/Controller/Project.pm
index f02dcc34..2fbbd93c 100644
--- a/src/lib/Hydra/Controller/Project.pm
+++ b/src/lib/Hydra/Controller/Project.pm
@@ -78,7 +78,7 @@ sub project_DELETE {
     requireProjectOwner($c, $c->stash->{project});
 
     $c->model('DB')->schema->txn_do(sub {
-        $c->stash->{project}->jobsetevals->delete;
+        # $c->stash->{project}->jobsetevals->delete;
         $c->stash->{project}->builds->delete;
         $c->stash->{project}->delete;
     });

```

but I don't know the implications of this diff.

**Comment by grahamc** [comment]
With this patch applied, can you write a test which: creates a project with a jobset, trigger an evaluation, build the queued builds, and then tries calling the HTTP API to delete? I'm curious to know if it will succeed with this patch applied, and if the cascade logic is all set.
