### ISSUE TITLE
Build pull request branches

### ISSUE THREAD

**Issue by zefhemel** [NixOS/hydra#95]
It would be very useful if Hydra would automatically build and test branches for which pull requests are issued, similar to https://github.com/litl/leeroy for Jenkins and Travis CI, i.e. a user issues a pull request (e.g. against nixpkgs), Hydra builds the branch for various platforms and post the status (success, failure) to the pull request as a comment.

This would really help in improving support for the platforms we care about (e.g. Linux, Mac) and specifying exactly which platforms are supported for a build.

**Comment by domenkozar** [comment]
This would help a lot, I'll look into it.

**Comment by domenkozar** [comment]
We are building https://github.com/hercules-ci/hercules to address this.

**Comment by Gabriel439** [comment]
It seems like Hydra has pull request support now (see: https://github.com/NixOS/hydra/commit/c6f07534359dd567b6dfe9397dc22e1f90925397 and comments on that revision).  Is documentation all that is missing?

**Comment by gilligan** [comment]
This has been implemented as gabriel pointed out correctly above.
