### ISSUE TITLE
Direct links to tabs with dynamically loaded contents stopped working

### ISSUE THREAD

**Issue by rbvermaa** [NixOS/hydra#959]
Example: https://hydra.nixos.org/jobset/disnix/disnix-trunk#tabs-jobs

**Comment by grahamc** [comment]
Probably related:

https://github.com/NixOS/hydra/pull/677/files#diff-207897a1d5d220a06cec051938c06eaa35abe361386b33476783881cf9f85bddR134

https://github.com/NixOS/hydra/pull/677/files#diff-207897a1d5d220a06cec051938c06eaa35abe361386b33476783881cf9f85bddR63

h/t @samueldr for pointing these out

**Comment by grahamc** [comment]
I've confirmed it is fixed on hydra.nixos.org. You might need to hard-refresh to get the update.
