### ISSUE TITLE
NixOps Network

### ISSUE THREAD

**Issue by zefhemel** [NixOS/hydra#96]
It would be very cool if people can deploy their own Hydra to a virtualbox or EC2 using NixOps with a few commands. Perhaps a network.nix can be created for this purpose?

**Comment by copumpkin** [comment]
:+1:, related to #197

**Comment by domenkozar** [comment]
https://github.com/peti/hydra-tutorial

**Comment by gilligan** [comment]
I would say that considering how easy the setup is with the nixos module now and the instructions provided in the README this can be closed. I don't think there has to be explicit nixops support.
