### ISSUE TITLE
How to turn off restricted mode.

### ISSUE THREAD

**Issue by locallycompact** [NixOS/hydra#986]
Hi, I'm getting this when evaluating a git repo.

```
error: access to URI 'https://github.com/locallycompact/haskell.nix/archive/179091d6c96cd609367e4a3013167868d58e63b5.tar.gz' is forbidden in restricted mode
error: worker error: error: access to URI 'https://github.com/locallycompact/haskell.nix/archive/179091d6c96cd609367e4a3013167868d58e63b5.tar.gz' is forbidden in restricted mode
```

I've tried with `allowed-uris = "https://github.com"` and that doesn't work. How do I just turn this mode off?

**Comment by locallycompact** [comment]
Never mind, it needed a minute to believe its config.

**Comment by danjl1100** [comment]
((Apologies for the noise.)) Found this issue from google, and misunderstood the solution as adding the option to `services.hydra.extraConfig`.


After more searching when that didn't work, found this comment from edolstra which clarified this setting goes in `nix.extraOptions` (applies to nix itself, not hydra)

https://github.com/NixOS/nix/issues/5039#issuecomment-910229409
```
  nix.extraOptions =
    ''
      allowed-uris = https://github.com/ https://git.savannah.gnu.org/
    '';
```
